### ISSUE TITLE
Wish a android building

### ISSUE THREAD

**Issue by meicj** [andpor/react-native-sqlite-storage#1]
Wish a android building

**Comment by brodybits** [comment]
I am planning to build an abstraction layer to support the sqlite plugin on multiple frameworks such as Cordova and React Native. Unfortunately I cannot promise when.

**Comment by andpor** [comment]
I will think of something for Android...

**Comment by zhuchaowe** [comment]
android support +1

**Comment by brodybits** [comment]
There is already a possible solution to use the sqlite storage plugin with React Native for Android: [react-native-cordova-plugin](https://github.com/axemclion/react-native-cordova-plugin) already supports it for Android once I fix litehelpers/Cordova-sqlite-storage#382.

**Comment by andpor** [comment]
Android support also added to react-native-sqlite-storage v 2.1.0

**Comment by brodybits** [comment]
Thanks for your efforts to support this!
