### ISSUE TITLE
Transaction Rollback

### ISSUE THREAD

**Issue by barbarosh** [andpor/react-native-sqlite-storage#10]
I tested rollback transaction if have broken query. On android. I put query to undefined table and got exception but previous query doesn`t rollback. This is problem implemented as a module or SQLite?

**Comment by andpor** [comment]
can you post your sample code and highlight expected vs actual results?

**Comment by barbarosh** [comment]
I make this tomorrow

**Comment by andpor** [comment]
@barbarosh  Alex - since you haven't updated this thread for a while I assume you were able to resolve the issue? I will close this unless you let me know otherwise. Cheers.

**Comment by barbarosh** [comment]
@andpor  I did not answer for a long time, sorry. But I had a lot of things I could not continue to investigate this issue. I can not say that it is fixed, as after a new release, I did not check.

**Comment by andpor** [comment]
Since I have not heard otherwise , assume this is not an issue..

**Comment by andpor** [comment]
@barbarosh  I just fixed a bug in this area for Promise runtime. Issue #39

**Comment by barbarosh** [comment]
@andpor It is pretty cool ! Thanks !
