### ISSUE TITLE
Question: how to use the android-native-Implementation instead of the "android"-Implementation?

### ISSUE THREAD

**Issue by MrsBookik** [andpor/react-native-sqlite-storage#100]
As described in the README, one can use react-native-sqlite-storage as follows:

MainApplication.java:

```java
import org.pgsqlite.SQLitePluginPackage;

public class MainApplication extends Application implements ReactApplication {
  ......

  /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new SQLitePluginPackage(),   // register SQLite Plugin here
        new MainReactPackage());
    }
}
```

But when i try to switch to the android-native-Implementation with "io.liteglue.SQLitePluginPackage", it won't compile because of a **error: package io.liteglue does not exist**

> .../MainApplication.java:15: error: package io.liteglue does not exist
> import io.liteglue.SQLitePluginPackage;
>                   ^
> .../MainApplication.java:65: error: cannot find symbol
>             new SQLitePluginPackage(),
>                 ^
>   symbol: class SQLitePluginPackage
> 2 errors
> 

What I did was simply to change the import line to the liteglue-implementation:

```java
import io.liteglue.SQLitePluginPackage;;

public class MainApplication extends Application implements ReactApplication {
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new SQLitePluginPackage(),   // register SQLite Plugin here
        new MainReactPackage());
    }
}
```

It seems that more things are necessary ...

How to do that correctly?

**Comment by andpor** [comment]
you need to open android-native project instead of android.

**Comment by atennapel** [comment]
in android/settings.gradle
```
include ':react-native-sqlite-storage'
project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android-native')
```

**Comment by andpor** [comment]
is this before or after ?

**Comment by atennapel** [comment]
You replace the `sqlite-storage` lines with this, instead of `android` you just have `android-native`, the rest is the same. In `settings.gradle` there should only be these two lines of `sqlite-storage`.

**Comment by andpor** [comment]
yes, as in [README](https://github.com/andpor/react-native-sqlite-storage#step-2---update-gradle-settings). You replace android with android-native - that is what you are supposed to do to make it work.

**Comment by agentilela** [comment]
Apologies for resurrecting such an old thread, but as these steps have been completely removed from the README, can we assume that the android-native implementation is deprecated?

**Comment by ashifsadiq** [comment]
> ```java
>    import org.pgsqlite.SQLitePluginPackage;
>     @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>         new SQLitePluginPackage(),   // register SQLite Plugin here
>         new MainReactPackage());
>     }
> ```
