### ISSUE TITLE
Thanks for writing this!

### ISSUE THREAD

**Issue by almost** [andpor/react-native-sqlite-storage#104]
I'm the author of [react-native-sqlite](https://github.com/almost/react-native-sqlite) which also has the "react-native-sqlite" name on NPM. My library was never finished and I recommend people use your project instead. I was just wondering you you wanted to take over the NPM name, it seems silly that the shorter named project is the one you SHOULDN'T use :) I think it's possible to alias names so both could work. 

No worries if you're not interested, just thought I'd offer. And thanks again for writing this library, I'm using it myself right now!

**Comment by andpor** [comment]
Hi Thomas - appreciate the idea and want to take advantage but not sure how to do this...would you know?

**Comment by andpor** [comment]
@almost - hey Thomas, any ideas on how to transfer the name ?

**Comment by idris** [comment]
All you have to do is have @almost add @andpor as an admin on the `react-native-sqlite` project on npm.  Then @andpor will have permission to push new versions.

**Comment by almost** [comment]
Oh I totally missed your replies before! @andpor I've made you a collaborator on NPM. You're welcome to do as you wish with it. Maybe it's worth emailing npm and seeing if they'll let you forward the old name to it.

You're also welcome to remove me as a collaborator once you've got it all setup since I've had no hand in this project!

**Comment by andpor** [comment]
@almost I finally got around to doing this and uploaded latest version of the library to react-native-sqlite npm repo. Thanks for doing this...if you have time and feel like it please contribute to the project...Thanks Andrew
