### ISSUE TITLE
How to get database in Document path?

### ISSUE THREAD

**Issue by hoangdoan267** [andpor/react-native-sqlite-storage#105]
I have downloaded my db from my server and save it to ../Documents/data.db. But when I call

`let db = SQLite.openDatabase({name: 'data', createFromLocation: path}, this.openCB, this.errorCB)`

it throws an error:  Cannot read a property "open" of undefined

**Comment by andpor** [comment]
you did not link the libraries properly and the native module is not found. Readme has all steps.
