### ISSUE TITLE
React-native-windows support?

### ISSUE THREAD

**Issue by matthiasleitner** [andpor/react-native-sqlite-storage#106]
Hi,

just wanted to check if there are any plans on supporting [react-native-windows](https://github.com/ReactWindows/react-native-windows)? If not can you give suggestions on how to contribute?

Thanks

**Comment by andpor** [comment]
no plans for windows. Do you have some ideas how this should work? I have not looked at this at all to be quite honest.

**Comment by zerglingno1** [comment]
https://github.com/craftzdog/react-native-sqlite-2
if want to using sqlite on react-native-windows , please take a look

**Comment by andpor** [comment]
merged - thank you !
