### ISSUE TITLE
Full path of db show 0 bytes file

### ISSUE THREAD

**Issue by hoangdoan267** [andpor/react-native-sqlite-storage#108]
I have use this block of code to open my database from data folder
```
    var db = SQLite.openDatabase(
      {name: 'sampleDB', createFromLocation : "~data/sampleDB.db"},
      this.successCB ,
      this.errorCB)

```

It always show me an error: `{ code: 5, message: 'no such table: quiz' }`

Built path to pre-populated DB asset from app bundle was corrected when I checked
http://2.pik.vn/2016e3a6116b-4056-46e4-9ca9-0d3501fffcfe.png

But the path to open db show me an empty file
http://2.pik.vn/201695d5843d-cbe0-4110-998c-61625270cc33.png

These are my project and folder structures
http://2.pik.vn/201663c7a203-83fa-445f-a632-30978049d1af.png

(http://2.pik.vn/2016459bc8f8-0f8b-45ba-9efa-921328a7d7b3.png

**Comment by lamjack** [comment]
same problem.

**Comment by andpor** [comment]
can u attach a screenshot showing www and dat contents?

**Comment by andpor** [comment]
looks like sampleDB.db is empty? Acoording to your code that is the name of input file..

**Comment by andpor** [comment]
Lack of feedback from reporter. Assume local config issue. Closing this.
