### ISSUE TITLE
[ios] no such table

### ISSUE THREAD

**Issue by lamjack** [andpor/react-native-sqlite-storage#109]
According to the document, 

i create a folder called 'www' first, and put my sqlite db in it, then i added my www folder in xcode.

<img width="974" alt="2016-12-29 5 17 03" src="https://cloud.githubusercontent.com/assets/8164447/21540535/abf16f3e-cdea-11e6-88da-df51ab795dc0.png">

it's my code,

<img width="912" alt="2016-12-29 5 18 51" src="https://cloud.githubusercontent.com/assets/8164447/21540564/e889e1f6-cdea-11e6-8892-330446016bbe.png">

and the db's content,

<img width="978" alt="2016-12-29 5 20 03" src="https://cloud.githubusercontent.com/assets/8164447/21540586/174e6d72-cdeb-11e6-9c14-1591968e02ba.png">

and i try to visit the db in a component, but show me no such table error, any idea?

<img width="1187" alt="2016-12-29 5 21 32" src="https://cloud.githubusercontent.com/assets/8164447/21540610/4be577ba-cdeb-11e6-91f7-9cb63eee34e4.png">

**Comment by andpor** [comment]
Suggest you follow the debug log from xcode and try to figure of what is going on. You can attach one as well. Start from scratch as db's had already been created or delete it...

**Comment by lamjack** [comment]
@andpor im clone your example repository and double check all step, it's fixed. The xcode add file problem.

**Comment by neemssoni** [comment]
@lamjack and @andpor can you explain me the solution, i did not get the solution.

**Comment by andpor** [comment]
@neemssoni - seems to be caused by developer error
