### ISSUE TITLE
libSQLite.a missing

### ISSUE THREAD

**Issue by lanzer** [andpor/react-native-sqlite-storage#11]
Having trouble getting or compiling the libSQL.a file.  Can you give some pointers on how to obtain the file?

Same for the libsqlite3.0.dylib file.  Not sure where to find it.

Thank you

**Comment by andpor** [comment]
libSQL.a is an artifact of the project. You add it to your parent project as highlighted in instr.
libsqlite.3 is a existing system level library you can choose from to add to your project.
