### ISSUE TITLE
 Duplicate interface definition for class 'RCTBridge'

### ISSUE THREAD

**Issue by songyu719** [andpor/react-native-sqlite-storage#112]
when i import react-native-sqlite-storage xcode show me this 
 Duplicate interface definition for class 'RCTBridge'

**Comment by itinance** [comment]
I'll guess your using RN 0.40. Therefor you need this PullRequest for compatibility with RN => 0.40 

https://github.com/andpor/react-native-sqlite-storage/pull/110

**Comment by songyu719** [comment]
thanks from china
