### ISSUE TITLE
Deprecation errors when running "npm install --save react-native-sqlite-storage"

### ISSUE THREAD

**Issue by circuit-monkey** [andpor/react-native-sqlite-storage#114]
Mac OS 10.12.2
Node 6.9.4

I ran "npm install --save react-native-sqlite-storage" from inside a new project folder, and that resulted in the following deprecation warnings:

npm WARN deprecated node-uuid@1.3.3: use uuid module instead
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
HelloWorld@0.0.1 /Users/mac/Desktop/HelloWorld
└─┬ react-native-sqlite-storage@3.1.2 
  ├─┬ rnpm@1.5.2 
  │ ├── glob@6.0.4 
  │ ├── lodash@3.10.1 
  │ ├── rnpm-plugin-install@1.1.0 
  │ ├─┬ rnpm-plugin-link@1.8.0 
  │ │ ├── glob@7.1.1 
  │ │ ├── lodash@3.10.1 
  │ │ ├─┬ mock-fs@3.12.1 
  │ │ │ └── rewire@2.5.2 
  │ │ └─┬ to-camel-case@1.0.0 
  │ │   └─┬ to-space-case@1.0.0 
  │ │     └── to-no-case@1.0.2 
  │ └─┬ update-notifier@0.6.3 
  │   ├─┬ boxen@0.3.1 
  │   │ ├── filled-array@1.1.0 
  │   │ └── widest-line@1.0.0 
  │   ├─┬ configstore@2.1.0 
  │   │ ├─┬ dot-prop@3.0.0 
  │   │ │ └── is-obj@1.0.1 
  │   │ ├── osenv@0.1.4 
  │   │ ├── uuid@2.0.3 
  │   │ └── xdg-basedir@2.0.0 
  │   ├── is-npm@1.0.0 
  │   ├─┬ latest-version@2.0.0 
  │   │ └─┬ package-json@2.4.0 
  │   │   ├─┬ got@5.7.1 
  │   │   │ ├─┬ create-error-class@3.0.2 
  │   │   │ │ └── capture-stack-trace@1.0.0 
  │   │   │ ├── duplexer2@0.1.4 
  │   │   │ ├── is-redirect@1.0.0 
  │   │   │ ├── is-retry-allowed@1.1.0 
  │   │   │ ├── lowercase-keys@1.0.0 
  │   │   │ ├── node-status-codes@1.0.0 
  │   │   │ ├─┬ read-all-stream@3.1.0 
  │   │   │ │ └─┬ readable-stream@2.2.2 
  │   │   │ │   └── isarray@1.0.0 
  │   │   │ ├─┬ readable-stream@2.2.2 
  │   │   │ │ └── isarray@1.0.0 
  │   │   │ ├── timed-out@3.1.3 
  │   │   │ ├── unzip-response@1.0.2 
  │   │   │ └─┬ url-parse-lax@1.0.0 
  │   │   │   └── prepend-http@1.0.4 
  │   │   ├─┬ registry-auth-token@3.1.0 
  │   │   │ └─┬ rc@1.1.6 
  │   │   │   ├── deep-extend@0.4.1 
  │   │   │   ├── ini@1.3.4 
  │   │   │   └── strip-json-comments@1.0.4 
  │   │   └── registry-url@3.1.0 
  │   └── semver-diff@2.1.0 
  └─┬ xcode@0.8.4 
    ├── node-uuid@1.3.3 
    ├── pegjs@0.6.2 
    └─┬ simple-plist@0.0.4 
      └─┬ plist@1.1.0 
        ├── base64-js@0.0.6 
        ├── util-deprecate@1.0.0 
        └─┬ xmlbuilder@2.2.1 
          └── lodash-node@2.4.1

**Comment by itinance** [comment]
Warnings are no errors

**Comment by itinance** [comment]
But you are right that versions of dependencies should be updated

**Comment by circuit-monkey** [comment]
Thanks, I need to be more careful with the words that I choose!
