### ISSUE TITLE
Demo code not working

### ISSUE THREAD

**Issue by circuit-monkey** [andpor/react-native-sqlite-storage#115]
Mac OS 10.12.2
Node 6.9.4

I installed the library on my system and added the demo code in the following manner: 

https://gist.github.com/circuit-monkey/e03ead559922470ae3ed516302d3fe57

I am now getting the following error in the simulator: 

![image](https://cloud.githubusercontent.com/assets/1028163/22037630/a1d41482-dd00-11e6-9ad7-174843b7aefd.png)

**Comment by andpor** [comment]
what code is on line 36?

**Comment by circuit-monkey** [comment]
Posting my code here was not working correctly for some reason. 

I've added a link to a gist that shows it correctly.

**Comment by andpor** [comment]
This is not a demo code but your own code. Apologies but I can't do the syntax debugging for you.

**Comment by itinance** [comment]
@circuit-monkey  You should learn javascript :) Line 36 should be something like:

function errorCB(err) {
  console.log("SQL Error: " + err);
}

Line 38 is a comma after the bracket, remove it.

The following lines should be fixed in the same schema

**Comment by circuit-monkey** [comment]
Sorry, but I was using code found on the front page of this project. I honestly thought that that was supposed to be the demo code. I guess that there is another file that I should be referring to? Removing commas still resulted in the same errors.

**Comment by andpor** [comment]
Working demo code is under test directory. Readme file has code snippets only.
