### ISSUE TITLE
Slow performance on Android

### ISSUE THREAD

**Issue by thedjinn** [andpor/react-native-sqlite-storage#116]
Hi! After testing our product on several devices I noticed that react-native-sqlite-storage is about three times slower on Android when compared to iOS (on similar hardware). We are doing lots of insert/update statements inside a single transaction and see that most time is spent inside `executeSql`.

**Comment by andpor** [comment]
It is what it is for now. You are quite welcome to improve the performance and submit a PR :)

**Comment by andpor** [comment]
Let's begin with an understanding that iOS is much much faster than majority of Android deployments. Only top notch hardware with Android on it can come into true comparison with iOS - that is just the way it is. That is why performance hungry apps like Pokemon Go for example, run pretty much on all iOS devices but only on select few Android devices, performance and hardware features are key.

That said if you feel there is opportunity to improve the code to make the sqlite runs faster please do so by all means. Will be happy to accept your contribution.

**Comment by andpor** [comment]
This module is open to performance improvements contributions from the community...

**Comment by iamrohitagg** [comment]
Any workarounds to improve the speed on Android? Android takes 3x times than iOS for me.
