### ISSUE TITLE
InvalidStateError: DOM Exception 11: This transaction is already finalized. Transactions are committed after its success or failure handlers are called. If you are using a Promise to handle callbacks, be aware that implementations following the A+ standard adhere to run-to-completion semantics and so Promise resolution occurs on a subsequent tick and therefore after the transaction commits.

### ISSUE THREAD

**Issue by MrsBookik** [andpor/react-native-sqlite-storage#117]
When using transactions i get the following exception:

> InvalidStateError: DOM Exception 11: This transaction is already finalized. Transactions are committed after its success or failure handlers are called. If you are using a Promise to handle callbacks, be aware that implementations following the A+ standard adhere to run-to-completion semantics and so Promise resolution occurs on a subsequent tick and therefore after the transaction commits

Assuming, _**db**_ is the database instance that i get in success-handler of openDatabase, here comes the code to reproduce the error. I use this library with SQLite.enablePromise(false).
What i wanted to achieve is to check first, if a specific record is already existing, and depending on this result, perform a UPDATE or a INSERT-statement.

```
  objectExists( id, table, idColumn = 'id' ) {
    const sql = `SELECT id FROM ${table} WHERE ${idColumn}=? LIMIT 1`;

    return new Promise((resolve, reject) => {
      db.transaction( tx => {
        console.log(1, tx);
        tx.executeSql( sql, [id], (tx, res) => {
          console.log(2, tx, res);
          const existing = res.rowsAffected > 0;
          console.log('Existing', existing);
          return resolve({tx, existing});
        })
      })
    })
  }

  persistShop( shop : Shop ) {
    return this.objectExists( shop.public_id, 'shop', 'public_id' )
      .then( ({tx, existing}) => {
        console.log(3, tx, existing )
        // for now just make an insert regardless wheter this record exists or not because it is broken anways
        const sql = `
          INSERT INTO shop VALUES (public_id, name, picture_url, created)
          VALUES (?, ?, ?, ?)
        `;
        return tx.executeSql( sql, [shop.public_id, shop.name, shop.picture_url, time() ]);
      })
      .catch( (a,b,c) => {
        console.log(4, "CATCH persistShop",a,b,c)
      })
  }

```

The output on console is:

> 1 SQLitePluginTransaction {db: SQLitePlugin, error: undefined, success: undefined, txlock: true, readOnly: false…}
> 2 SQLitePluginTransaction {db: SQLitePlugin, error: undefined, success: undefined, txlock: true, readOnly: false…} Object {rows: Object, rowsAffected: 0, insertId: undefined}
> Existing false
> 3 SQLitePluginTransaction {db: SQLitePlugin, error: undefined, success: undefined, txlock: true, readOnly: false…} false
> 4 "CATCH persistShop" Object {message: "InvalidStateError: DOM Exception 11: This transact…tick and therefore after the transaction commits.", code: 11} undefined undefined
> 

What happens here is that i can't re-use the transaction after the first call to tx.executeSql.

How to do such consecutive sql-statements within a transaction?

**Comment by narychen** [comment]
Because transaction is finished and you cannot use it further more.
see the specification here on https://github.com/litehelpers/Cordova-sqlite-storage
```
WARNING: It is NOT allowed to execute sql statements on a transaction after it has finished. Here is an example from the Populating Cordova SQLite storage with the JQuery API post at http://www.brodybits.com/cordova/sqlite/api/jquery/2015/10/26/populating-cordova-sqlite-storage-with-the-jquery-api.html:
```

**Comment by keithito** [comment]
My understanding is that it's impossible to use the Promise-based interface to do a SELECT then UPDATE in the same transaction because the promise returning the SELECT results will always resolve after the transaction has finished. Is that correct?

**Comment by danderson00** [comment]
I am wondering the same thing as @keithito. It would appear so. Maybe one day I'll find the time to look at fixing this...

**Comment by zhuyifan2013** [comment]
> Because transaction is finished and you cannot use it further more.

@narychen So why return `tx` in promise function  like this : `tx.executeSql( sql, [id], (tx, res))`

**Comment by narychen** [comment]
You do not need to return the promise in transaction, just call it

**Comment by GuilhermeLessa** [comment]
any solution for transaction through promises?
