### ISSUE TITLE
sqlBatch performance gains

### ISSUE THREAD

**Issue by narychen** [andpor/react-native-sqlite-storage#118]
I'm using an old version which doesn't have sqlBatch api.
I saw it was added in v2.1.5.
Just wondering how much performance gains it will bring compare to the 
old normal transaction api when you make a lot inserts or updates.
Should I change to the new version and use sqlBatch instead or it is
just a helper api, not a performance improvement?

**Comment by andpor** [comment]
sqlBatch is more of a semantic and usability enhancement. It allows you to provide an array of SQL statements which will be wrapped inside a transaction.

**Comment by narychen** [comment]
I see. Thanks a lot.
