### ISSUE TITLE
Semantic Issues

### ISSUE THREAD

**Issue by circuit-monkey** [andpor/react-native-sqlite-storage#119]
Deleting the project and then recreating it is has resulted in the following build errors on XCode 8.2.1:

![error](https://cloud.githubusercontent.com/assets/1028163/22195782/6081ffe8-e152-11e6-9d3f-fa629b02d9dc.jpg)

I've tried deleting the Derived Data with no luck.

**Comment by itinance** [comment]
This is due to RN 0.40 breaking changes.
As long as https://github.com/andpor/react-native-sqlite-storage/pull/110 is not released, you have to patch it manually.

**Comment by circuit-monkey** [comment]
Using 0.39 worked like a charm. Thank you very much.

**Comment by georgiana-gligor** [comment]
If you must use RN 0.40 and have this issue, please be aware that the `master` branch has the fix code already, but it hasn't been released yet.

So what you can do to solve the problem in this current state, is to edit `package.json` to not use the latest release, but use the latest code from `master` branch instead. Therefore you want to replace the line

```
"react-native-sqlite-storage": "^3.1.3",
```
with
```
"react-native-sqlite-storage": "git+https://github.com/andpor/react-native-sqlite-storage.git",
```

Please note that this is a really temporary fix, and when the author will package a new release, it is highly advisable to use it in your `package.json` again.

**Comment by andpor** [comment]
I will cut RN 4.0 compatible release this week.

**Comment by andpor** [comment]
3.2.0 released today.
