### ISSUE TITLE
Can't execute multiple selects

### ISSUE THREAD

**Issue by donald-jackson** [andpor/react-native-sqlite-storage#12]
Hi there,

I'm probably missing something painfully obvious here but for the life of me I can't figure this out. I am executing a select after I open the database - the version select works and returns the version number I expect. I am keeping my own 'Version' table like in the examples.

Once the database is 'ready' - I then do my normal work and proceed to select from the other tables (Service) in this case, but it never returns any data. In actual fact the methods just die during execution.

I've tried this using Promise and Callback methods and the result is the same - it appears I have some sort of stale transaction floating around which is preventing me from getting the data I need.

My code is below - I'm sure it isn't pretty as I've tried various different ways to execute this. If someone could advise me on best practices to avoid issues like this (if its not an actual issue) I'd be very appreciative.

    var database_name = "authio-verity.db";
    var database_version = "1.0";
    var database_displayname = "Authio Database";
    var database_size = 200000;
    var database_current_version = 0;
    var database_latest_version = 1;
    var database_ready_callback = null;
    var db;

    var AuthioDB = {
        openErrorCallback() {
            database_ready_callback(false);
        },

        openDatabase(readyCallback) {
            var that = this;
            database_ready_callback = readyCallback;
            db = SQLite.openDatabase(database_name, database_version, database_displayname, database_size, function() {
                that.populateDatabase(db);
            }, this.openErrorCallback);
        },

        populateDatabase(db){
            var that = this;

            db.executeSql('SELECT version_id FROM Version ORDER BY version_id DESC LIMIT 1', [], function(results) {
                console.log("Post version query (success)");
                var len = results.rows.length;
                for (let i = 0; i < len; i++) {
                    let row = results.rows.item(i);
                    database_current_version = row.version_id;
                }

                this.setState(this.state);

                db.transaction(that.upgradeTables, function() {
                    database_ready_callback(false);
                }, function() {
                    database_ready_callback(true);
                });

            }, function() {
                console.log("Post version query (failed)");
                db.transaction(that.upgradeTables, function() {
                    database_ready_callback(false);
                }, function() {
                    console.log("Upgrade success");
                    database_ready_callback(true);
                });
            });

            //database_ready_callback(true);
        },

        upgradeTables(tx) {
            console.log("Database running version "+database_current_version);
            if(database_current_version < 1) {
                tx.executeSql("CREATE TABLE IF NOT EXISTS Version ( " +
                    "version_id INTEGER PRIMARY KEY" +
                    ");", []);
                tx.executeSql("CREATE TABLE IF NOT EXISTS Service (" +
                    "id INTEGER PRIMARY KEY, " +
                    "name TEXT" +
                    ");", []);
                tx.executeSql("INSERT INTO Version (version_id) VALUES (?)", [1]);
            }
        },

        addService(callback, obj) {
            var that = this;
            db.transaction(tx).then(() => {
                callback(true);
            });
        },

        addAccountTransaction(tx, obj) {
            tx.executeSql("INSERT INTO Service (name) VALUES (?)", [obj.name]);
        },

        getServices(callback) {
            db.executeSql("SELECT id FROM Service", [], function(results) {
                console.log("Got service results "+JSON.stringify(results));
                var len = results.rows.length;
                console.log("len = "+len);
                for (var i = 0; i < len; i++) {
                    let row = results.row.item(i);
                    console.log("row "+i+" = "+row.id);
                }

                callback(results);
            });
        },

        executeQuery(query, params) {
            console.log("Executing query "+query);
            return db.executeSql(query, params);
        },

        executeQueryCallback(query, params, callbackSuccess, callbackFailure) {
            db.executeSql(query, params, callbackSuccess, callbackFailure);
        },

        executeTransaction(func, callback) {
            console.log("Executing transaction on AuthioDB");
            db.transaction(func).then((results) => {
                callback(true, results);
            }).catch((error) => {
                callback(false);
            });
        },
        closeDatabase(){
            var that = this;
            if (db) {
                console.log("Closing database ...");
                //db.close();
            } else {
            }
        },

        getDbResource() {
            return db;
        }
    }

**Comment by andpor** [comment]
Hi Donald 

avoid doing stuff on the db open status callback - wait for db instance to be returned and then invoke this.populateDatabase(db)

try removing this.setState(this.state); or recoding this stmt to that.setState(that.state); in populateDatabase.

var that = this is not there by accident 

you can either do var that = this or use a bind(this)_ on the method.

**Comment by andpor** [comment]
otherwise the sample you sent is not complete..where is getService getting called from. What is the param to openDatabase for example?

**Comment by andpor** [comment]
This code "works" i.e. I see return values from getServices...

React Native is bad in terms of eating up bad references to this it seems...


-----

openErrorCallback(message) {
        
    },

    populateDatabase(db){
        var that = this;

        db.executeSql('SELECT version_id FROM Version ORDER BY version_id DESC LIMIT 1', [], function(results) {
            console.log("Post version query (success)");
            var len = results.rows.length;
            for (let i = 0; i < len; i++) {
                let row = results.rows.item(i);
                database_current_version = row.version_id;
            }

            that.setState(that.state);

            db.transaction(that.upgradeTables, function() {
                console.log("upgradeTables failed");
            }, function() {
                console.log("upgradeTables success");
                that.getServices(() => {});
            });

        }, function() {
            console.log("Post version query (failed)");
            db.transaction(that.upgradeTables, function() {
                console.log("Upgrade failed");
            }, function() {
                console.log("Upgrade success");
            });
        });

        
    },

    upgradeTables(tx) {
        console.log("Database running version "+database_current_version);
        if(database_current_version < 1) {
            tx.executeSql("CREATE TABLE IF NOT EXISTS Version ( " +
                "version_id INTEGER PRIMARY KEY" +
                ");", []);
            tx.executeSql("CREATE TABLE IF NOT EXISTS Service (" +
                "id INTEGER PRIMARY KEY, " +
                "name TEXT" +
                ");", []);
            tx.executeSql("INSERT INTO Version (version_id) VALUES (?)", [1]);
        }
    },

    addService(callback, obj) {
        var that = this;
        db.transaction(tx).then(() => {
            callback(true);
        });
    },

    addAccountTransaction(tx, obj) {
        tx.executeSql("INSERT INTO Service (name) VALUES (?)", [obj.name]);
    },

    getServices(callback) {
        db.executeSql("SELECT id FROM Service", [], function(results) {
            console.log("Got service results "+JSON.stringify(results));
            var len = results.rows.length;
            console.log("len = "+len);
            for (var i = 0; i < len; i++) {
                let row = results.row.item(i);
                console.log("row "+i+" = "+row.id);
            }

            callback(results);
        });
    },

    executeQuery(query, params) {
        console.log("Executing query "+query);
        return db.executeSql(query, params);
    },

    executeQueryCallback(query, params, callbackSuccess, callbackFailure) {
        db.executeSql(query, params, callbackSuccess, callbackFailure);
    },

    executeTransaction(func, callback) {
        console.log("Executing transaction on AuthioDB");
        db.transaction(func).then((results) => {
            callback(true, results);
        }).catch((error) => {
            callback(false);
        });
    },

    getDbResource() {
        return db;
    },


    loadAndQueryDB(){
        var that = this;
        that.state.progress.push("Opening database ...");
        that.setState(that.state);
        //database_ready_callback = readyCallback;
        db = SQLite.openDatabase(database_name, database_version, database_displayname, database_size, function() {
            console.log("db opened");
        }, that.openErrorCallback);
        this.populateDatabase(db);
    },

**Comment by donald-jackson** [comment]
Hi Andrzej, 

Thanks for taking the time to help. It appears I have misunderstood the purpose of the open callbacks. I thought that the entire nature of this module was asynchronous - ie: you can only use once the open callback has executed, which is why I was doing things in there.

I'll try it again now by just using the populate/etc methods outside of the callback - because my entire structure was basically executing in a chained callback.

Thanks again.

**Comment by shanitiwari01** [comment]
I follow the below blog to integrate SQLite storage on this blog provided ExecuteQuery function and how to use it because based on promise it handles multiple select queries.

`/**
  * Execute sql queries
  * 
  * @param sql
  * @param params
  * 
  * @returns {resolve} results
  */
  ExecuteQuery = (sql, params = []) => new Promise((resolve, reject) => {
    db.transaction((trans) => {
      trans.executeSql(sql, params, (trans, results) => {
        resolve(results);
      },
        (error) => {
          reject(error);
        });
    });
  });`


https://medium.com/infinitbility/react-native-sqlite-storage-422503634dd2
