### ISSUE TITLE
Issue with test code

### ISSUE THREAD

**Issue by circuit-monkey** [andpor/react-native-sqlite-storage#120]
I've created a new project and followed the steps to install / link this library. 

The issue that I have is when I replace the code in index.ios.js with the example code:

https://gist.github.com/circuit-monkey/2562e02d4f3fc92e35bce1fa5dcc8df4

Then I get the following errors in the simulator: 

![image](https://cloud.githubusercontent.com/assets/1028163/22228001/0ed527c6-e1d7-11e6-9301-28bb38c0aa73.png)

**Comment by circuit-monkey** [comment]
changing like 9 to: 

> var React = require('react');

And line 21 to: 

> } = require('react-native');

allowed me to run the example code.

**Comment by andpor** [comment]
@itinance - can you please check if the example code needs any adjustments ?

**Comment by itinance** [comment]
will do in upcoming days

**Comment by andpor** [comment]
Nevermind actually - I thought this issue was referring to the samples but it seems it refers to original test code. I will take a look.

**Comment by andpor** [comment]
This is fixed in 3.2.1 release.
