### ISSUE TITLE
no such table: test - prepopulated database example

### ISSUE THREAD

**Issue by circuit-monkey** [andpor/react-native-sqlite-storage#122]
I have react-native-sqlite-storage saved/linked from master branch.

I've copied the example.db from PrepopulatedDatabaseExample into the correct place: 

iOS: ./www/example.db

I've also copied the index.ios.js from PrepopulatedDatabaseExample:

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

let SQLite = require('react-native-sqlite-storage')

export default class ReactNative_GrammarApp extends Component {

  constructor(props) {
    super(props)

    this.state = {
      record: null
    }

    let db = SQLite.openDatabase({name: 'test.db', createFromLocation : "~example.db", location: 'Library'}, this.openCB, this.errorCB);
    db.transaction((tx) => {
      tx.executeSql('SELECT * FROM test', [], (tx, results) => {
          console.log("Query completed");

          // Get rows with Web SQL Database spec compliance.

          var len = results.rows.length;
          for (let i = 0; i < len; i++) {
            let row = results.rows.item(i);
            console.log(`Record: ${row.name}`);
            this.setState({record: row});
          }
        });
    });

  }

  errorCB(err) {
    console.log("SQL Error: " + err);
  }

  successCB() {
    console.log("SQL executed fine");
  }

  openCB() {
    console.log("Database OPENED");
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          This is an example with sqlite3 and a prepopulated database. Enjoy!
        </Text>
        <Text style={styles.instructions}>
          {this.state.record !== null ? 'Success: ' + this.state.record.name : 'Waiting...'}
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('ReactNative_GrammarApp', () => ReactNative_GrammarApp);
```

When I run it in the simulator it just says "Waiting..." and here is what the console output looks like: 

![screen shot 2017-01-30 at 4 21 54 am](https://cloud.githubusercontent.com/assets/1028163/22410655/ba8312ec-e6a3-11e6-82b5-b3955fa1dcaf.png)

**Comment by andpor** [comment]
Take a look at the output in XCode and see what it reveals..

**Comment by andpor** [comment]
And follow the [documentation for opendatabase call](https://github.com/andpor/react-native-sqlite-storage#step-6---adjust-opendatabase-call)

**Comment by JKonTiki** [comment]
I had the exact same issue for the longest time - but just solved it almost inexplicably. On the open database call:
`
let db = SQLite.openDatabase({name: 'test.db', createFromLocation : "~example.db", location: 'Library'}, this.openCB, this.errorCB);
`
try changing the name property of your database to something random and arbitrary. for me the name of my file was literally the ONE thing that would break it. try something like this:
`
let db = SQLite.openDatabase({name: 'test', createFromLocation : "~example.db", location: 'Library'}, this.openCB, this.errorCB);
`

**Comment by devteam2015** [comment]
I had the same issue, and after following @JKonTiki's suggestion, somehow it is working now. 

First, I thought my path configuration was wrong, so I followed @andpor's instruction very carefully again. But it still didn't work. When I changed the name of db, it worked. If I test with the original db name again, it still doesn't work. My DB name was just a plain word... I don't really know what happened, but maybe I guess the name of DB must be different from the pre-populated db's name?

**Comment by andpor** [comment]
This stmt is incorrect.

let db = SQLite.openDatabase({name: 'test.db', createFromLocation : "~example.db", location: 'Library'}, this.openCB, this.errorCB);

**Comment by phaeton2040** [comment]
I think I have the same issue. 
I'm working on android app. I place my database file `birdsDB` to `android/app/src/main/assets/www`.
In my index.android.js I wrote
    this.dbName = 'birdsDB';
    this.db = SQLite.openDatabase({name : this.dbName, createFromLocation: 1},
      () => {
        console.log('DB created');
      },
      () => {
        console.log('error while creating DB')
      });

This is what I see in my debugger:
![image](https://cloud.githubusercontent.com/assets/5227957/22780909/70120b4c-eed1-11e6-88c9-c63be254b67e.png)

What am I doing wrong?

**Comment by andpor** [comment]
@phaeton2040 - look at native debugger rather than Javascript. It will reveal more information about what it is you may be doing setting up wrong.

**Comment by phaeton2040** [comment]
@andpor what is native debugger? Is it this project - https://github.com/jhen0409/react-native-debugger

**Comment by andpor** [comment]
Android Studio debugger console....or XCode debugging console

**Comment by andpor** [comment]
Closing this as this is most likely not an issue with the module itself but rather dev error.

**Comment by bhumit1709** [comment]
I am getting weird behaviour where it works on iOS simulator but fails on iOS device.

**Comment by iSimar** [comment]
Getting this error..

when its look the file with the log `Looking for prepopulated DB at: <path_a_to_file>`
I see the file is there and its not of size 0

but when it does  `Opening db in mode READ_WRITE, full path: <path_b_to_file>`

the size of the file at <path_b_to_file> is 0

**Comment by vankhanhpr** [comment]
Solution:Close your editor and open again, remove the app in your decives and run again.

**Comment by hyumus** [comment]
SQLite.openDatabase({name:"testDB.sqlite3",createFromLocation:1,location:'Library'}) . 
this solved my problem. testDB.sqlite3 file size is 24 MB. testDB.sqlite and testDB.db not working, but testDB.sqlite3 is working.

**Comment by VidyaCKabber** [comment]
vankhanhpr's soluction working for me. Thank you 👍 .

Solution:Close your editor and open again, remove the app in your device and run again.

**Comment by KotlyarovBoris** [comment]
> Solution:Close your editor and open again, remove the app in your decives and run again.
It works. Thanks you 👍 .
```javascript
db = await SQLite.openDatabase({
            name: 'test',
            createFromLocation: '~database.db',
            location: 'Library',
        });
```

**Comment by fahadhaq** [comment]
I can get it to work with deleting the app while I am making changes to my app. But would the end user need to delete the app from their device when they update to new version of my app to get the new column?
