### ISSUE TITLE
React/RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by kumarpatel** [andpor/react-native-sqlite-storage#124]
"react-native-sqlite-storage": "^3.1.2"
"react-native": "^0.35.0"

after npm install,

in `3.1.2`, SQLite.h file had `#import "RCTBridgeModule.h"`
https://github.com/andpor/react-native-sqlite-storage/blob/3.1.2/src/ios/SQLite.h#L16

this was changed in `3.2.0` to `#import <React/RCTBridgeModule.h>`
https://github.com/andpor/react-native-sqlite-storage/blob/3.2.0/src/ios/SQLite.h#L16

After npm install, why am I getting `3.2.0` code, when my package json is listed to use `3.1.2` for `react-native-sqlite-storage`???

**Comment by kumarpatel** [comment]
nvm. Didn't notice the caret `^`
Closing.

**Comment by alainib** [comment]
i have the same error 

     #import <React/RCTBridgeModule.h>           'React/RCTBridgeModule.h' file not found

my versions :  

    "react-native": "0.55.4",
    "react-native-sqlite-storage": "^3.3.10",


i added to podfile  `  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'`   and made `react-native link`

**Comment by RuanYang2016** [comment]
me too

**Comment by Gaurang-786** [comment]
any update ?
