### ISSUE TITLE
Cannot find database file after SQLite.openDatabase

### ISSUE THREAD

**Issue by phaeton2040** [andpor/react-native-sqlite-storage#126]
SQLite.openDatabase command creates databases. The data can be inserted and selected. But I cannot find any .sqlite file in my project.

Also `createFromLocation` option doesn't seem to work for me. Database created this way is empty.

**Comment by andpor** [comment]
_"SQLite.openDatabase command creates databases. The data can be inserted and selected. But I cannot find any .sqlite file in my project."_ not sure why you are expecting to find any file in your project....database file will be created in the location that you provide in open call or in default location if you do not. In any event, it will never be in your project...

_"Also createFromLocation option doesn't seem to work for me. Database created this way is empty."_- use native debugger to figure out what you are not doing properly.
