### ISSUE TITLE
Importing a pre-populated database

### ISSUE THREAD

**Issue by Lichwa** [andpor/react-native-sqlite-storage#127]
Here's how I'm trying to open db:
```javascript
const filePath = `${fs.DocumentDirectoryPath}/ck-szczecinek.mbtiles`
const exists = await fs.exists(filePath)
console.log('db exists', filePath, exists)

this.mbTilesDB = sqlite.openDatabase({
    name: 'ck-szczecinek.mbtiles',
    createFromLocation: filePath,
    readOnly: true
}, onSuccess, onError)
```

in console I'm getting:
```
'db exists', '/data/user/0/com.cyfrowakraina/files/ck-szczecinek.mbtiles', true
```
so it means db is there, however `onSuccess` callback is never called.

Am I doing something wrong?

**Comment by andpor** [comment]
As always, I recommend you take a look at the debugger output in whatever IDE you are using (XCode/Android Studio) and try to figure out what is going on.

**Comment by Lichwa** [comment]
Im asking here because sadly there isn't anything in debugger output :/

`onError` doesn't get called either. DB itself weights 150MB could it be that it's too big?

**Comment by Lichwa** [comment]
Ok i finally found the solution. For whatever reason `createFromLocation` didn't get resolved to absolute path but concatenated to `/data/user/0/com.cyfrowakraina/files/data/user/0/com.cyfrowakraina/files/tiles.db` instead.
Is that by design?

**Comment by andpor** [comment]
Yes - it is by design. I am puzzled as to why you are not seeing any debugging stmt in XCode or Android. Native side prints lots of useful information there. Have you looked at the debug console of your IDE?

**Comment by Lichwa** [comment]
Yes I eventually found error in Android Studio I filterered logs to only display RN errors as I didn't expect it to be native error, so it was my mistake. I think that docs could use some update as details like this one aren't really described here.

Anyways thanks for help 👍

**Comment by andpor** [comment]
You mean the fact that there is logging in native IDE console or something else?

**Comment by colewinans** [comment]
@Lichwa what was your solution? I'm having the same issue.

**Comment by manjuy124** [comment]
@colewinans 
Did you fix dis issue?

**Comment by SnehalAgrawal** [comment]
Can you please look into the answer [here](https://github.com/andpor/react-native-sqlite-storage/issues/164#issuecomment-468774393) in issue [Example to access prepopulated database #164](https://github.com/andpor/react-native-sqlite-storage/issues/164)

**Comment by infinitbility** [comment]
When you want pre-populate database then every time you have to create a new database file and delete previous database or re build application.

check out below documentation

https://infinitbility.com/react-native-sqlite-storage-examples-of-query
