### ISSUE TITLE
TEXT insert

### ISSUE THREAD

**Issue by jefferyvincent** [andpor/react-native-sqlite-storage#134]
Hello, I am haveing issues with this module when I try to INSERT anything other than an INTEGER or INT. 

// Create
tx.executeSql('CREATE TABLE IF NOT EXISTS Test( '
              + 'id INTEGER PRIMARY KEY NOT NULL, '
              + 'ball_1 INTEGER, '
              + 'ball_2 INTEGER, '
              + 'ball_3 INTEGER, '
              + 'ball_4 INTEGER, '
              + 'ball_5 INTEGER, '
              + 'ball INTEGER,'
              + 'timestamp TEXT ) ; ');

// Insert
this.db.executeSql('INSERT INTO Test (ball_1, ball_2, ball_3, ball_4, ball_5, ball, timestamp) VALUES ('+obj.ball_1+','+obj.ball_2+','+obj.ball_3+','+obj.ball_4+','+obj.ball_5+','+obj.ball+','+obj.timestamp+');').catch((error) =>{
      console.log("Received error: ", error.message);
      throw error;
});

This timestamp column will fail to write and throw and error that the column does not exist. I was trying to input the following text within the obj.timestamp "11/23/2016" or just "test" and it would throw an error telling me that the column does not exist.

**Comment by andpor** [comment]
The sample code is test directory has a variety of table formats and it all works just fine. Suggest you have a look there.

**Comment by jefferyvincent** [comment]
I am not sure I follow. I am creating a table named Test and then trying to insert TEXT into it and it's not inserting.

**Comment by andpor** [comment]
There are working examples in test directory with column type TEXT with pre-populated data. The demo's do work.

**Comment by andpor** [comment]
I modified the sample code changing one of the columns to be TEXT type. Seems to work fine both inserting and retrieving...

tx.executeSql('CREATE TABLE IF NOT EXISTS Employees( '
            + 'employe_id INTEGER PRIMARY KEY NOT NULL, '
            + 'name TEXT, '
            + 'office INTEGER, '
            + 'department INTEGER, '
            + 'FOREIGN KEY ( office ) REFERENCES Offices ( office_id ) '
            + 'FOREIGN KEY ( department ) REFERENCES Departments ( department_id ));').catch((error) => {
            that.errorCB(error)
        });

**Comment by asessa** [comment]
@jefferyvincent data is not escaped automatically, try to wrap your obj.timestamp with an apostrophe.

```
// Insert
this.db.executeSql('INSERT INTO Test (ball_1, ball_2, ball_3, ball_4, ball_5, ball, timestamp) VALUES ('+obj.ball_1+','+obj.ball_2+','+obj.ball_3+','+obj.ball_4+','+obj.ball_5+','+obj.ball+',\''+obj.timestamp+'\');').catch((error) =>{
console.log("Received error: ", error.message);
throw error;
});
```

**Comment by andpor** [comment]
Not response. Closing this as an issue with user code.
