### ISSUE TITLE
react-native 0.17 android error

### ISSUE THREAD

**Issue by onzag** [andpor/react-native-sqlite-storage#14]
I follow your steps faithfully using the standard project... But I get this:

```
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* Where:
Build file '/media/Storage/easyship/android/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'easyship'.
> Could not find method compile() for arguments [project ':react-native-sqlite-storage'] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@501df9bd.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.629 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

Any idea what that could be and how to solve it?

**Comment by barbarosh** [comment]
@onzag I use 0.17 with with module and all work fine.

**Comment by onzag** [comment]
Yes it was my fault....

**Comment by MonkeyWGlasses** [comment]
It seems, as if I have made the same mistake. @onzag can you tell me what you did wrong?

**Comment by itinance** [comment]
@MonkeyWGlasses you should read the installation-section for android again and again and ensure that you did every step.

**Comment by MonkeyWGlasses** [comment]
Allright, trying for a couple more hours I noticed the mistake.

For those coming after me:
There are more than one build.gradle files in an React Native project. Make sure to make the insert from Step 3 in 'android/app/build.gradle' and not in 'android/build.gradle'.
