### ISSUE TITLE
Code dosn't work?

### ISSUE THREAD

**Issue by zuber303** [andpor/react-native-sqlite-storage#142]
Hi. I'm not sure why my code doesn't work.
My code:
`import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    TextInput,
    Button,
    View
} from 'react-native';

SQLite = require('react-native-sqlite-storage');
SQLite.DEBUG(true);
SQLite.enablePromise(true);

let db;
export default class SqliteComponent extends Component {

    constructor() {
        super();
        this.state = {
            countryName:'',
            progress:''
        };
        this.startDB();

    }
    startDB(){

            SQLite.openDatabase({name: 'test.db', createFromLocation : "~example.db", location: 'Library'}).then((DB) => {
                db = DB;
                this.setState({
                    progress:this.state.progress+"Database OPEN"
                });
            }).catch(error => {
               console.log(error);
               this.setState({
                    progress:error
                });

            });
    }

    createDB(){

        db.executeSql('CREATE TABLE IF NOT EXISTS countrys( '
            + 'country_id INTEGER PRIMARY KEY NOT NULL, '
            + 'name VARCHAR(30) )');
    }
    adValue(){
        db.executeSql('INSERT INTO countrys (name) VALUES ("Polska")');
    }

    showValue(){
        db.executeSql('SELECT name FROM countrys').then((results) => {
            let len = results.rows.length;
            for (let i = 0; i < len; i++) {
                let row = results.rows.item(i);
                this.setState({
                    countryName:this.state.countryName+row.name,
                });
            }

        }).catch((error) => {
            console.log(error);
        });
    };
    
    render() {
        return (
            <View>
                <Button
                    color={'royalblue'}
                    onPress={this.createDB}
                    title="Create DB"
                />
                <Button
                    color={'orange'}
                    onPress={this.adValue}
                    title="Add"
                />
                <Button
                    color={'brown'}
                    onPress={this.showValue}
                    title="Show"
                />

                <Text>{this.state.countryName}</Text>
                <Text>{this.state.progress}</Text>
            </View>
        )
    }

}
AppRegistry.registerComponent('SqliteComponent', () => SqliteComponent);`

And information that I get from console log:

> 03-22 13:55:55.248  3386  3545 I ReactNativeJS: OPEN database: test
.db
03-22 13:55:55.249  3386  3545 I ReactNativeJS: SQLite.open({"name"
:"test.db","createFromLocation":"~example.db","location":"Library",
"dblocation":"libs","assetFilename":"~example.db"})
03-22 13:55:56.531  3386  3545 I ReactNativeJS: SQLite.backgroundEx
ecuteSqlBatch({"dbargs":{"dbname":"test.db"},"executes":[{"qid":111
1,"sql":"SELECT 1","params":[]},{"qid":1111,"sql":"CREATE TABLE IF
NOT EXISTS countrys( country_id INTEGER PRIMARY KEY NOT NULL, name
VARCHAR(30) ); ","params":[]}]})
03-22 13:56:08.196  3386  3545 I ReactNativeJS: SQLite.backgroundEx
ecuteSqlBatch({"dbargs":{"dbname":"test.db"},"executes":[{"qid":111
1,"sql":"SELECT 1","params":[]},{"qid":1111,"sql":"INSERT INTO coun
trys (name) VALUES (\"Polska\")","params":[]}]})
03-22 13:56:11.047  3386  3545 I ReactNativeJS: SQLite.backgroundEx
ecuteSqlBatch({"dbargs":{"dbname":"test.db"},"executes":[{"qid":111
1,"sql":"SELECT 1","params":[]},{"qid":1111,"sql":"SELECT name FROM
 countrys","params":[]}]})
03-22 13:56:11.051  3386  3545 I ReactNativeJS: { [TypeError: undef
ined is not an object (evaluating 'results.rows.length')]
03-22 13:56:11.051  3386  3545 I ReactNativeJS:   line: 76888,
03-22 13:56:11.051  3386  3545 I ReactNativeJS:   column: 21,
03-22 13:56:11.051  3386  3545 I ReactNativeJS:   sourceURL: 'http:
//10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=
true&minify=false' }
03-22 13:57:06.646  3386  3545 I ReactNativeJS: 'Setting debug to:'
, true
03-22 13:57:06.646  3386  3545 I ReactNativeJS: Promise based runti
me ready
03-22 13:57:06.646  3386  3545 I ReactNativeJS: [React Transform HM
R] Patching SqliteComponent
> 

I don't know what means that information in console:

> 3-22 13:56:08.196  3386  3545 I ReactNativeJS: SQLite.backgroundEx
ecuteSqlBatch({"dbargs":{"dbname":"test.db"},"executes":[{"qid":111
1,"sql":"SELECT 1","params":[]},{"qid":1111,"sql":"INSERT INTO coun
trys (name) VALUES (\"Polska\")","params":[]}]})

Is it success or error?
And when I click button "SHOW" then console shows this error:
 { [TypeError: undef
ined is not an object (evaluating 'results.rows.length')]

Can you tell me why it doesn't work?

Thank you.

**Comment by andpor** [comment]
You should try to use the demo code from the test directory as starting point. No sure what the issue is with your code. Apologize - not enough time to debug..
