### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by zerglingno1** [andpor/react-native-sqlite-storage#144]
Please port sqlite for windows too !

**Comment by metalmalte** [comment]
+1

**Comment by zerglingno1** [comment]
https://github.com/craftzdog/react-native-sqlite-2
our company support this repo for windows support please take a look

**Comment by Ash-faq** [comment]
@zerglingno1 react-native-sqlite-2 does not have the per populated db

**Comment by andpor** [comment]
@zerglingno1 windows implementation is now provided in this module courtesy of @dryganets . I will publish a new version on npm soon.
