### ISSUE TITLE
A wired bug caused by the database name

### ISSUE THREAD

**Issue by Symous** [andpor/react-native-sqlite-storage#145]
Hello,I worked on Android platform with Android Studio.

I named my sqlite database as "my.db" and run my react-native program to the physical phone(Android 5.1),when I try to operate the database(open and excute sql),it give me an error "no such table tableName". It very confused me since I have follow the step of adding a database and operating it. 

But when I renamed the database file from "my.db" to "mydb",it worked well when I open and excute sql!

I also have found that If I name the database file as "my.db" ,I need to uninstall the react-native app from my phone and re-install it so it can work well.

Please find out that whether it is a bug or not.Thanks.

**Comment by andpor** [comment]
i have not seen any issues where a db name would cause any kind of issue. There was probably something else at play in your setup.
