### ISSUE TITLE
how set collate?

### ISSUE THREAD

**Issue by Deboracgs** [andpor/react-native-sqlite-storage#149]
I need set collate of database for utf8_unicode_ci, how make this?

**Comment by itinance** [comment]
You you confused this with mysql? 

Btw, Sqlite3 only supports UTF-8 and UTF-16, while [UTF-8 seems](http://www.sqlite.org/c3ref/open.html) to be the default value.

Have also a look here: http://www.sqlite.org/pragma.html#pragma_encoding

**Comment by andpor** [comment]
This is not MySQL - this SQLite.
