### ISSUE TITLE
"postlink" doesn't run on Windows

### ISSUE THREAD

**Issue by ChristianTucker** [andpor/react-native-sqlite-storage#150]
The rnpm postlink command issues error `Error: spawn UNKNOWN` on Windows, removing the postlink command causes the build to freeze at 99% on Android (Left it there for over 10 hours)

Manual installation instructions should be included for these reasons.

**Comment by qualifyapp** [comment]
Should add that running rnpm link on Linux/Mac doesn't add anything to the android project.
