### ISSUE TITLE
Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by Borisboky** [andpor/react-native-sqlite-storage#152]
I have an problem on IOS. I get **Cannot read property 'open' of undefined**. On Android it works fine.

My project tree in XCode is as follows:

<img width="1716" alt="screen shot 2017-04-10 at 16 02 40" src="https://cloud.githubusercontent.com/assets/13819165/24868372/1898ced2-1e10-11e7-9eb3-98bed9e33d6c.png">

I'm probably making mistake somewhere on the linking.

Any advice?

**EDIT**

<img width="248" alt="screen shot 2017-04-11 at 09 46 14" src="https://cloud.githubusercontent.com/assets/13819165/24898075/ccd507cc-1e9b-11e7-800c-bc993f042387.png">

**Comment by itinance** [comment]
You should show the linker issues. Click on the red circle at the top

**Comment by Borisboky** [comment]
I've edited my question.

**Comment by andpor** [comment]
i can't tell what is wrong but you seem to have linking issue as @itinance had said. Try to follow manual instructions step by step.
