### ISSUE TITLE
Implicit declaration of function'sqlite3_key' is invalid in C99

### ISSUE THREAD

**Issue by sil218** [andpor/react-native-sqlite-storage#155]
HI i am getting this error while building, 

The app is still running via react-native run-ios, however I am unable to build using xcode

**Comment by pop-xiaodong** [comment]
is same for me.
i comments some code, success
![wx20170421-154422](https://cloud.githubusercontent.com/assets/14698280/25267968/8b3fb4fe-26a9-11e7-8c01-327c0c4559c8.png)
![wx20170421-154434](https://cloud.githubusercontent.com/assets/14698280/25267978/8d94ac1e-26a9-11e7-81a0-d32cb900e6f9.png)

**Comment by csummers** [comment]
I'm experiencing the same issue both in xCode and via `react-native run-ios`.  Looks like this was introduced in this commit: https://github.com/andpor/react-native-sqlite-storage/commit/cb4fe3e2b8c2be7eacce8aadcdb4a7786be46917#diff-18e1e1df7d1a850a00875114330b66b8L220

**Comment by andpor** [comment]
This should be commented out by default. I will take  a look...thanks for reporting.

**Comment by andpor** [comment]
Fixed in 3.3.1
