### ISSUE TITLE
Where to store android database?

### ISSUE THREAD

**Issue by metalmalte** [andpor/react-native-sqlite-storage#156]
I have a pre-populated database and stored this under /project/android/app/src/main/assets/www.
Unfortunately the logs tell me the databse has been opened successfully but I can't read from any of the tables. Non were found. Did I store the db file in the wrong directory?

**Comment by itinance** [comment]
./android/app/src/main/assets instead of /android/app/src/main/assets/www

The www-subfolder is only required for iOS

**Comment by itinance** [comment]
Also you have to recompile your android project after moving the file

**Comment by metalmalte** [comment]
Thanks 👍
