### ISSUE TITLE
How to do database schema migration?

### ISSUE THREAD

**Issue by MingLoan** [andpor/react-native-sqlite-storage#157]
Please assist.

**Comment by itinance** [comment]
I have a table called "version" that consists of only one column: version. And it contains only one record: the current internal version-number for my schema. It startet with 1.

Then, on every app-start i read the version that is present in the database and compare it with my expected current schema-version, that comes shipped with my app-update. 

I have a loop like this (not really code, just to give you an idea of it):
```

const CURRENT_SCHEMA_VERSION = 4

version = getCurrentDbVersion();
while(version < CURRENT_SCHEMA_VERSION) {
case 1: migrateV1toV2(); break;
case 2: migrateV2toV3(); break;
// ... and so on
}

```
These functions called "migrateV1toV2()" contains several sql-statements containg all these _ALTER TABLE_-statements and _CREATE INDEX_ and some _UPDATE_ and everything else that was needed to upgrade from a schema to its next version. I call them iteratively ONLY from one version to the next, never for all. 
Important is, that every migrate-function updates the version itself with: UPDATE version SET version=2; for instance

**Comment by paldepind** [comment]
@itinance Thank you for answering. Just for reference that is also the [solution described here](https://github.com/litehelpers/Cordova-sqlite-storage#database-schema-versions).

I'm wondering if it wouldn't make more sense to store the version number using [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html)? Using SQLite to store a single table with a single collumn and a single row seems like overkill to me?
