### ISSUE TITLE
String operators

### ISSUE THREAD

**Issue by FranciscoMSM** [andpor/react-native-sqlite-storage#165]
Hi!

I'm trying to run this query

```
    SELECT
      ar.id AS article_id,
      ar.number AS article_number,
      ar.text AS article_text
    FROM articles ar
    WHERE ar.text LIKE "%12%"
```

But somehow I get always 0 results, I'm running the exactly same query on DB Browser for Sqlite and It returns me a bunch of results. What are the available string/text operators?

Thanks! Great work so far 👍 

EDIT: I dont know why, working 👍

**Comment by jgtoriginal** [comment]
I know this might be an old thread, but I just stumbled upon the very same issue.
And since there's no documentation anywhere about it, I'll just post here how I did solve it.
So as other people who might face the same issue can see a way of sorting it out.

```
    db.transaction(function (txn) {
        txn.executeSql(
                "SELECT
                        ar.id AS article_id,
                        ar.number AS article_number,
                        ar.text AS article_text
                        FROM articles ar
                WHERE ar.text LIKE '%" + 12 + "%'"
        ), [], function (tx, res) {
                console.log(res)
        }
    });
```
