### ISSUE TITLE
[Request] Is there a user guide for document for all the functions?

### ISSUE THREAD

**Issue by ithieund** [andpor/react-native-sqlite-storage#177]
Hi,
Where can I find the document for usage instruction of all functions?

Thanks.

**Comment by andpor** [comment]
No, I am afraid there isn't one available...at some point when I have time perhaps...Sorry..

**Comment by zsubzwary** [comment]
@andpor it has been two years since the OP posted the issue.
Have anyone created some sort of Documentation?
