### ISSUE TITLE
Cannot set property 'progress' of undefined

### ISSUE THREAD

**Issue by abhijithp** [andpor/react-native-sqlite-storage#186]
I have an problem on Android. I get **Cannot set property 'progress' of undefined** 

![progress](https://user-images.githubusercontent.com/11426641/28610909-ac660c10-7207-11e7-8975-4d876523c488.png)

versions i use are:
react-native-cli: 2.0.1
react-native: 0.46.4

**Comment by andpor** [comment]
where?

**Comment by andpor** [comment]
Closing this issue as unrelated to this library.
