### ISSUE TITLE
[Question] How to add into create-react-native-app?

### ISSUE THREAD

**Issue by 6pm** [andpor/react-native-sqlite-storage#189]
I have installed a clean app by create-react-native-app and I want to attach SQLite database for Android.
By instruction, I must add some code into file './android/settings.gradle'. But this file doesn't exist.
Is it possible to use your module with [create-react-native-app](https://github.com/react-community/create-react-native-app)?

**Comment by andpor** [comment]
It can be used with any react-native app. You probably have to change some config after your app is generated by that package. The instructions should be helpful.

**Comment by Gujie-Novade** [comment]
Hey, so did you have to eject the app?
