### ISSUE TITLE
Clearing App Data Issue.

### ISSUE THREAD

**Issue by jojonarte** [andpor/react-native-sqlite-storage#19]
Hello I'm currently having a problem with our app using your module. It was for a function that should clear the App Data of our app. We're returned the error below:

undefined is not an object(evaluating NativeModules SQLite method)

Do you have any idea if this can be resolved?
![errrr](https://cloud.githubusercontent.com/assets/11880365/12351157/8325ad0a-bbb6-11e5-9ab5-d7de915df26b.png)

**Comment by andpor** [comment]
Looks like React Native is not able to find the implementation of native plugin. The Android native plugin is most likely not correctly set up in your app. Double check the instructions for Android.

That is all I can say given the information you provided.
