### ISSUE TITLE
[Question]How to create db with same name under different dir?

### ISSUE THREAD

**Issue by elledeng** [andpor/react-native-sqlite-storage#190]
How to create  db with same name under different dir?
ex:
create 1st db named sample.db under ~/user1/sample.db 
create 2nd db named sample.db under ~/user2/sample.db 

I tried with 

···
let db1 = SQLite.openDatabase({
    name: 'sample.db',
    createFromLocation : "~/user1/sample.db"
  }, () => {
  }, () => {
  });

let db2 = SQLite.openDatabase({
    name: 'sample.db',
    createFromLocation : "~/user2/sample.db"
  }, () => {
  }, () => {
  });

···

But it seem the db2 reused the db1 connection, and when I tried to create tableA in the 2 db, error occur for db2 with message: tableA already exists

**Comment by andpor** [comment]
I don't think you can have more than one database open with the same "name". It is supposed to be unique..
