### ISSUE TITLE
Abort existing transactions

### ISSUE THREAD

**Issue by NunoCardoso** [andpor/react-native-sqlite-storage#196]
Hi. 

I have a search bar that everytime the user adds a letter, it triggers a DB query. 

I need to abort existing DB transactions, to make sure only one (the more recent one) returns results. 

Do you have any recommendation/best practice to do that?

**Comment by NunoCardoso** [comment]
I tried all day to load a bundled DB on assets directory, on www directory, on db directory, with createFromLocation: 1, with createFromLocation: 'string', with different names, to no avail. I just can't find the assets folder in the apk. Is the code still working ?

**Comment by andpor** [comment]
yes...I suspect that your Android project is not configured properly to include assets directory from the project structure (assuming you followed directions and created one)...Google changes Gradle all the time... cannot keep up with it...

**Comment by andpor** [comment]
Closing as non-issue and lock of followup.
