### ISSUE TITLE
react-native-sqlite-storage install with latest react-native 

### ISSUE THREAD

**Issue by stoufa06** [andpor/react-native-sqlite-storage#200]
I have installed the lastest react native in linux machine and i have try to fallow the documentation to install react-native-sqlite-storage but seems these docs applies only for older react-native versions.
Android and ios folders and index.android.js and index.ios.js  does not exist!!
I have just started with react native and i am earlier stuck on this issue. 
Someone could help here
npm : 4.6.1
node : 8.6.0
react-native : 0.48.4

**Comment by andpor** [comment]
Module should work with latest RN...there are no such files in the module either afaik so I am not sure what it is that you are doing...

**Comment by stoufa06** [comment]
This is invalid ticket.  did not install react-native-cli
