### ISSUE TITLE
Main Queue Warning

### ISSUE THREAD

**Issue by Traviskn** [andpor/react-native-sqlite-storage#201]
I'm using this library in a react-native 0.49.3 app and am seeing this warning in the debugger console when I run the app on iOS: 

```shell
Module SQLite requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```
I don't see any warnings in the debugger console when running on Android.

Not a big problem right now but it looks like something that will need to be updated for future versions of react native.

**Comment by bugStatus** [comment]
![simulator screen shot - iphone 6 - 2018-05-02 at 17 15 30](https://user-images.githubusercontent.com/38912260/39521527-7475feee-4e2c-11e8-8b3b-e47b94941fd9.png)

What is the solution for this warning ?  how to get rid of it?

**Comment by andpor** [comment]
i will take a look a it..

**Comment by andpor** [comment]
https://github.com/andpor/react-native-sqlite-storage/pull/262
