### ISSUE TITLE
Select new database location

### ISSUE THREAD

**Issue by idotta** [andpor/react-native-sqlite-storage#203]
I'm sorry if this has been answered, but is there a way to change the location where the database will be created on Android? I could only find info on how to get a pre-populated database location, but nothing on where to create a new one. Thanks!

**Comment by santosh-indpro** [comment]
From the documentation >>

Opening a database

Opening a database is slightly different between iOS and Android. Where as on Android the location of the database file is fixed, there are three choices of where the database file can be located on iOS. The 'location' parameter you provide to openDatabase call indicated where you would like the file to be created. This parameter is neglected on Android.

WARNING: the default location on iOS has changed in version 3.0.0 - it is now a no-sync location as mandated by Apple so the release is backward incompatible.

To open a database in default no-sync location (affects iOS only)::

SQLite.openDatabase({name: 'my.db', location: 'default'}, successcb, errorcb);
To specify a different location (affects iOS only):

SQLite.openDatabase({name: 'my.db', location: 'Library'}, successcb, errorcb);
where the location option may be set to one of the following choices:

default: Library/LocalDatabase subdirectory - NOT visible to iTunes and NOT backed up by iCloud
Library: Library subdirectory - backed up by iCloud, NOT visible to iTunes
Documents: Documents subdirectory - visible to iTunes and backed up by iCloud
The original webSql style openDatabase still works and the location will implicitly default to 'default' option:

SQLite.openDatabase("myDatabase.db", "1.0", "Demo", -1);

**Comment by idotta** [comment]
I'm sorry, forgot to answer that! Thanks!
