### ISSUE TITLE
Linking issue with libreact-native-sqlite-storage.a in IOS

### ISSUE THREAD

**Issue by santosh-indpro** [andpor/react-native-sqlite-storage#204]
While using in XCODE getting following error. please suggest

Undefined symbols for architecture x86_64:
  "__RCTLogFormat", referenced from:
      -[SQLite init] in libreact-native-sqlite-storage.a(SQLite.o)
      -[SQLite echoStringValue:success:error:] in libreact-native-sqlite-storage.a(SQLite.o)
      -[SQLite open:success:error:] in libreact-native-sqlite-storage.a(SQLite.o)
      -[SQLite createFromResource:withDbname:] in libreact-native-sqlite-storage.a(SQLite.o)
      -[SQLite close:success:error:] in libreact-native-sqlite-storage.a(SQLite.o)
      -[SQLite attach:success:error:] in libreact-native-sqlite-storage.a(SQLite.o)
      -[SQLite delete:success:error:] in libreact-native-sqlite-storage.a(SQLite.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by santosh-indpro** [comment]
Wrong issue!

**Comment by Ramaraju1992** [comment]
@santosh-indpro  I'm facing the same issue how did u fix it.Please let me know
