### ISSUE TITLE
Feature request: stop insisting that pre-populated database be located in www

### ISSUE THREAD

**Issue by tomprogers** [andpor/react-native-sqlite-storage#209]
I understand that the library current requires devs to place the pre-populated database in a directory that is named precisely `www`.

While this works, there's no reasonable justification why anyone should be forced to do this. This library would be better if it did not insist on that folder name, and in fact it should not place any requirements on the location or name of the database (notwithstanding rules enforced by the underlying OS, such as iOS's default vs Library biz).

**Comment by andpor** [comment]
You are not forced to use www. [https://github.com/andpor/react-native-sqlite-storage#step-6---adjust-opendatabase-call](docs)
