### ISSUE TITLE
Is there a way to access the raw array from a query result?

### ISSUE THREAD

**Issue by pori** [andpor/react-native-sqlite-storage#21]
It does not appear possible at this moment. I don't believe that feature is part of the Web SQL Database spec, but it would certainly be convenient to be able to do so. 

The actual result array is [one step away](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js#L394) from being completely exposed in item(). I was thinking such a feature could be added to allow others to avoid any unnecessary hacking. Figured this would be okay considering the original spec is abandoned. :)

**Comment by andpor** [comment]
can you propose a change and submit a PR ...it should be naturally backward compatible...

**Comment by pori** [comment]
Will do!
