### ISSUE TITLE
SQLite connection

### ISSUE THREAD

**Issue by NiteshDhakal** [andpor/react-native-sqlite-storage#210]
**Cannot read property 'open'  of undefined.**

I have used this line:
var db = SQLite.openDatabase({name: 'test.db', createFromLocation: '~mydb.db'});
![screenshot from 2017-11-10 15-43-49](https://user-images.githubusercontent.com/25841307/32652960-372fd72a-c62e-11e7-8c6c-e6a0644611fd.png)

**Comment by rochapablo** [comment]
What do you got from callbacks? ```openDatabase({}, callsuccess, callerror)```

**Comment by garylin96** [comment]
I'm experiencing the same issue. I've tried including the success and error callbacks, but the exception is thrown before the callbacks are run.

In `sqlite.core.js:80`, the `exec` method is defined as:
```
plugin.exec = function(method, options, success, error) {
  if (plugin.sqlitePlugin.DEBUG){
    console.log('SQLite.' + method + '(' + JSON.stringify(options) + ')');
  }
  NativeModules["SQLite"][method](options,success,error);
};
```
where `NativeModules["SQLite"]` happens to be undefined.

I followed the iOS installation path with CocoaPods.
