### ISSUE TITLE
Open database error not firing

### ISSUE THREAD

**Issue by scgough** [andpor/react-native-sqlite-storage#213]
Hi,

Platform: **Android**
RN Version: **0.44.3**
This Plugin Version: **3.3.1** 

I'm experiencing an issue where the error callback on an unsuccessful `openDatabase` attempt isn't firing. 

The scenario I have is that I am updating in React-Native. I need to check for a legacy database on the app's first open after update and migrate data from the old database to the new database. 

The old database **may or may not exist** on the user's device. For example, if they are newly installing the app they won't have it. 

I would like to attempt to open said legacy database and if it fails to find it, skip the data migration process. 

When I test this in the scenario of the database not existing on my device I can see an error being caught in the SQLite native plugin code but **the error callback never gets fired on the JS side**. 

Here is the native side error: 
```
E/unknown:SQLitePlugin: unexpected error, stopping db thread
java.io.FileNotFoundException: www/mylegacydatabase.sqlite
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:316)
at android.content.res.AssetManager.open(AssetManager.java:290)
at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:383)
at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:49)
at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:923)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)
```

Has anyone experienced this? Is there a work-around/fix?

_This may also be affecting the success callback as well - unconfirmed as of yet_

**Comment by scgough** [comment]
**update** 
It seems like if you try and open a DB that isn't there (resulting in the above exception) you don't get the response to your specified error callback on the JS side. 

In addition, if you try and run some SQL over the closed instance (for example, to try and test if the db is there as you don't know either way) there is quite rightly an exception thrown **BUT** again, no callback is fired....so you're kind of stuck. 

I have found a way to get some kind of callback to the JS in this scenario. I've edited `SQLitePlugin.java` as follows:

```
private class DBRunner implements Runnable {
        final String dbname;
        final int openFlags;
        private String assetFilename;
        private boolean androidLockWorkaround;
        final BlockingQueue<DBQuery> q;
        final CallbackContext openCbc;
        
        ...
        public void run() {
            try {
                this.mydb = openDatabase(dbname, this.assetFilename, this.openFlags, this.openCbc);
            } catch (Exception e) {
                FLog.e(TAG, "unexpected error, stopping db thread", e);
                this.openCbc.error("database access exception"); //<- NEW CALLBACK PUSH HERE
                dbrmap.remove(dbname);
                return;
            }
        ...
```

I'm still testing but this _seems_ to fire my desired error callback on the `openDatabase` execution if the database in question doesn't exist. 

Any further help/advice would be appreciated still.

**Comment by andpor** [comment]
Have to try this myself...

**Comment by andpor** [comment]
Have you sorted this out? I cannot replicate the issue myself...

**Comment by scgough** [comment]
Hi @andpor - yes, the fix I outlined above sorted this issue for me. I've not had an issue since.

**Comment by andpor** [comment]
yes, you are right, the code does not handle this sequence with exceptions...will fix this in the repo ...

**Comment by andpor** [comment]
@scgough - openDatabase call is made with SQL flags to create a file if it does not exist. So the exception is not coming from there. The SQLiteException from openDatabase is caught, callback is invoked properly it seems. There were however several places where the pre-populated asset import logic was prone to exceptions which I attempted to fix. Would you be able to run some tests on a branch to see if it works for you?

asset-import-exception-handling

**Comment by scgough** [comment]
@andpor sorry for the delay getting back to you. At the moment, I'm not sure when I'll have time to run some tests. Sorry! I will try and get back to you ASAP

**Comment by andpor** [comment]
Please try version 3.3.5 - I tried to fix the issue you described.

**Comment by andrew-koster-** [comment]
I have the same issue. DB won't open, but I also don't get any kind of error callback.

**Comment by shumii** [comment]
Got the same issue trying on iOS. Success callback invoked even if I write jibberish as the DB name. No errors when opening, no errors when executing sql. Never used SQLite before - is it poor, or is it this react-native wrapper that's poor?
