### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by fahadhaq** [andpor/react-native-sqlite-storage#214]
Hi, Is there a way to do a bulk insert? I followed the Cordova example but it doesnt seem to be working.

https://github.com/reconka/Cordova-sqlite-storage-bulkinsert/blob/9e72c4ca44dd56df38233dbda42fcc6de80363d4/android/assets/www/js/index.js

here is my code
```
export function saveWelfareInfo(authenticationToken, welfareArr) {
  var sqlQuery = 'authenticationToken, enabled, title, tabname, tabimage, tabcontents, last_update_date, id, ethnicity_id, course, campus, app_profile_id'

  let db = OpenSqliteDatabase()
  db.transaction((tx) => {
    tx.executeSql('insert into welfare_list(' + sqlQuery + ') values(?,?,?,?,?,?,?,?,?,?,?,?)', welfareArr)
  tx.executeSql('SELECT * FROM welfare_list', [], (tx, results) => {
        console.log("Query completed");
        var len = results.rows.length;
        for (let i = 0; i < len; i++) {
          let row = results.rows.item(i);
          console.log('welfare_list Record: ', row);
        }
      });
  })
```

All my values get inserted into the AuthenticationToken column. What am I doing wrong?

Thanks in advance.

**Comment by maxammann** [comment]
https://stackoverflow.com/questions/47501193/react-native-sqlite-bulk-insert

**Comment by JayM96** [comment]
@fahadhaq can you paste your code to help others with bulk insert
.
