### ISSUE TITLE
TypeError: undefined is not a function(near '...sql.transaction...')

### ISSUE THREAD

**Issue by 925941723** [andpor/react-native-sqlite-storage#216]
I got the error like this:TypeError: undefined is not a function(near '...sql.transaction...')
my code is:
import SQLite from 'react-native-sqlite-storage';

SQLite.DEBUG(true);
SQLite.enablePromise(true);
var database_name = "test.db";//数据库文件
var database_version = "1.0";
var database_displayname = "MySQLite";
var database_size = -1;
var sql;
let tableName = 'user';

export default class InitSql {
     init(){
        sql = SQLite.openDatabase(
            database_name,
            database_version,
            database_displayname,
            database_size,
            ()=>{
                // this._successCB('open');
                this.createTable();
            },
            (err)=>{
                console.log("SQL Error: " + err);
            }
        );
    }

     create(){
         sql.transaction((tx)=>{
             tx.executeSql(`CREATE TABLE IF NOT EXISTS ${tableName}(
              ${UserBean.id} INTEGER PRIMARY KEY  AUTOINCREMENT,
              ${UserBean.num} VARCHAR,
              ${UserBean.name} VARCHAR)`
                 , [],_openCB,_errorCB)
         });
     }
}

when I used 'create' to create a table,I got this error.And I tried another way like this:
SQLite.openDatabase({name: 'my.db', location: 'default'}, (DB)=>{
    sql=DB;
}, errorcb);
And not work too.

**Comment by maxlxq** [comment]
db.transaction is not a function! 请问您解决了吗

**Comment by 925941723** [comment]
没有，我感觉是因为原生库没有连接上的问题。但是试过了知道的所有操作，还是不行

**Comment by maxlxq** [comment]
我运行了代码demo， 可以哟哦那个
`'use strict';

import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    ListView
} from 'react-native';
import SQLite from 'react-native-sqlite-storage';

SQLite.DEBUG(true);
SQLite.enablePromise(false);

const database_name = "Test.db";
const database_version = "1.0";
const database_displayname = "SQLite Test Database";
const database_size = 200000;
let db;

class TestSql extends Component{
    constructor(props){
        super(props);
        this.state={
            progress: [],
            dataSource: new ListView.DataSource({
                rowHasChanged: (row1, row2) => row1 !== row2,
            })
        };
    }

    componentWillUnmount(){
        this.closeDatabase();
    }

    addProgress=(str,t)=>{
        let p = t.state.progress;
        p.push(str);
        t.setState({progress:p});
    };

    errorCB=(err) => {
        console.log("error: ",err);
        this.addProgress("Error: "+ (err.message || err),this);

        return false;
    };

    successCB=()=>{
        this.addProgress("SQL executed ...",this);
    };

    openCB=()=>{
        this.addProgress("Database OPEN",this);

    };

    closeCB=()=>{
        this.addProgress("Database CLOSED",this);

    };

    deleteCB=()=>{
        this.addProgress("Database DELETED",this);
        this.addProgress("Database DELETED",this);

    };

    populateDatabase=(db)=>{
        let that = this;
        that.addProgress("Database integrity check",that);

        db.executeSql('SELECT 1 FROM Version LIMIT 1', [],
            function () {
                that.addProgress("Database is ready ... executing query ...",that);

                db.transaction(that.queryEmployees,that.errorCB,function() {
                    that.addProgress("Processing completed",that);

                });
            },
            function (error) {
                console.log("received version error:", error);
                that.addProgress("Database not yet ready ... populating data",that);

                db.transaction(that.populateDB, that.errorCB, function () {
                    that.addProgress("Database populated ... executing query ...",that);

                    db.transaction(that.queryEmployees,that.errorCB, function () {
                        that.addProgress("Transaction is now finished",that);
                        that.addProgress("Processing completed",that);

                        that.closeDatabase();
                    });
                });
            });
    };

    populateDB=(tx) => {
        this.addProgress("Executing DROP stmts",this);

        tx.executeSql('DROP TABLE IF EXISTS Employees;');
        tx.executeSql('DROP TABLE IF EXISTS Offices;');
        tx.executeSql('DROP TABLE IF EXISTS Departments;');

        this.addProgress("Executing CREATE stmts",this);

        tx.executeSql('CREATE TABLE IF NOT EXISTS Version( '
            + 'version_id INTEGER PRIMARY KEY NOT NULL); ', [], this.successCB, this.errorCB);

        tx.executeSql('CREATE TABLE IF NOT EXISTS Departments( '
            + 'department_id INTEGER PRIMARY KEY NOT NULL, '
            + 'name letCHAR(30) ); ', [], this.successCB, this.errorCB);

        tx.executeSql('CREATE TABLE IF NOT EXISTS Offices( '
            + 'office_id INTEGER PRIMARY KEY NOT NULL, '
            + 'name letCHAR(20), '
            + 'longtitude FLOAT, '
            + 'latitude FLOAT ) ; ', [], this.successCB, this.errorCB);

        tx.executeSql('CREATE TABLE IF NOT EXISTS Employees( '
            + 'employe_id INTEGER PRIMARY KEY NOT NULL, '
            + 'name letCHAR(55), '
            + 'office INTEGER, '
            + 'department INTEGER, '
            + 'FOREIGN KEY ( office ) REFERENCES Offices ( office_id ) '
            + 'FOREIGN KEY ( department ) REFERENCES Departments ( department_id ));', []);

        this.addProgress("Executing INSERT stmts",this);

        tx.executeSql('INSERT INTO Departments (name) VALUES ("Client Services");', []);
        tx.executeSql('INSERT INTO Departments (name) VALUES ("Investor Services");', []);
        tx.executeSql('INSERT INTO Departments (name) VALUES ("Shipping");', []);
        tx.executeSql('INSERT INTO Departments (name) VALUES ("Direct Sales");', []);

        tx.executeSql('INSERT INTO Offices (name, longtitude, latitude) VALUES ("Denver", 59.8,  34.);', []);
        tx.executeSql('INSERT INTO Offices (name, longtitude, latitude) VALUES ("Warsaw", 15.7, 54.);', []);
        tx.executeSql('INSERT INTO Offices (name, longtitude, latitude) VALUES ("Berlin", 35.3, 12.);', []);
        tx.executeSql('INSERT INTO Offices (name, longtitude, latitude) VALUES ("Paris", 10.7, 14.);', []);

        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Sylvester Stallone", 2,  4);', []);
        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Elvis Presley", 2, 4);', []);
        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Leslie Nelson", 3,  4);', []);
        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Fidel Castro", 3, 3);', []);
        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Bill Clinton", 1, 3);', []);
        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Margaret Thatcher", 1, 3);', []);
        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Donald Trump", 1, 3);', []);
        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Dr DRE", 2, 2);', []);
        tx.executeSql('INSERT INTO Employees (name, office, department) VALUES ("Samantha Fox", 2, 1);', []);
        console.log("all config SQL done");
    };

    queryEmployees=(tx) => {
        this.addProgress("Executing sql...",this);
        tx.executeSql('SELECT a.name, b.name as deptName FROM Employees a, Departments b WHERE a.department = b.department_id and a.department=?', [3],
            this.queryEmployeesSuccess,this.errorCB);
        //tx.executeSql('SELECT a.name, from TEST', [],() => {},this.errorCB);
    };

    queryEmployeesSuccess=(tx,results) =>{
        console.log("Query completed");
        let p = this.state.progress;
        let len = results.rows.length;
        for (let i = 0; i < len; i++) {
            let row = results.rows.item(i);
            p.push(`Empl Name: ${row.name}, Dept Name: ${row.deptName}`);
        }
        this.setState({progress:p});
    };

    loadAndQueryDB=()=>{
        this.addProgress("Opening database ...",this);
        db = SQLite.openDatabase(database_name, database_version, database_displayname, database_size, this.openCB, this.errorCB);
        this.populateDatabase(db);
    };

    deleteDatabase=()=>{
        this.addProgress("Deleting database",this);
        SQLite.deleteDatabase(database_name, this.deleteCB, this.errorCB);
    };

    closeDatabase=()=>{
        let that = this;
        if (db) {
            console.log("Closing database ...");
            console.log("Closing database");
            db.close(that.closeCB,that.errorCB);
        } else {
            console.log("Database was not OPENED");
        }
    };

    runDemo=()=>{
        this.setState({progress:["Starting SQLite Callback Demo"]});
        this.loadAndQueryDB();
    };

    renderProgressEntry=(entry)=>{
        return (<View style={listStyles.li}>
            <View>
                <Text style={listStyles.liText}>{entry}</Text>
            </View>
        </View>)
    };

    render(){
        let ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        return (<View style={styles.mainContainer}>
            <View style={styles.toolbar}>
                <Text style={styles.toolbarButton} onPress={this.runDemo}>
                    Run Demo
                </Text>
                <Text style={styles.toolbarButton} onPress={this.closeDatabase}>
                    Close DB
                </Text>
                <Text style={styles.toolbarButton} onPress={this.deleteDatabase}>
                    Delete DB
                </Text>
            </View>
            <ListView
                enableEmptySections={true}
                dataSource={ds.cloneWithRows(this.state.progress)}
                renderRow={this.renderProgressEntry}
                style={listStyles.liContainer}/>
        </View>);
    }
}

const listStyles = StyleSheet.create({
    li: {
        borderBottomColor: '#c8c7cc',
        borderBottomWidth: 0.5,
        paddingTop: 15,
        paddingRight: 15,
        paddingBottom: 15,
    },
    liContainer: {
        backgroundColor: '#fff',
        flex: 1,
        paddingLeft: 15,
    },
    liIndent: {
        flex: 1,
    },
    liText: {
        color: '#333',
        fontSize: 17,
        fontWeight: '400',
        marginBottom: -3.5,
        marginTop: -3.5,
    },
});

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    },
    instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
    },
    toolbar: {
        backgroundColor: '#51c04d',
        paddingTop: 30,
        paddingBottom: 10,
        flexDirection: 'row'
    },
    toolbarButton: {
        color: 'blue',
        textAlign: 'center',
        flex: 1
    },
    mainContainer: {
        flex: 1
    }
});

export default TestSql;`

**Comment by 925941723** [comment]
谢谢，我的问题应该是没有正确导入库文件，我再尝试下

**Comment by maxlxq** [comment]
好的，我也在试

**Comment by maxlxq** [comment]
解决了吗，我前几天发现修改为`SQLite.enablePromise(false);`就可以了

**Comment by 925941723** [comment]
好像是我的工程有问题，无论怎样都配置不上。同事直接Pod install 就完成了

**Comment by Duyao1314** [comment]
我也遇到这问题了,在创建数据库表的时候,怎么解决啊

**Comment by 925941723** [comment]
这个是ios工程的配置有问题，具体问题是怎样还不清楚。上次我们换台机子就行了，要是没有你可以试试建一个新的工程

**Comment by longdw** [comment]
如果设置SQLite.enablePromise(true);那么数据库创建就是异步的，db.transaction需要在数据库open success的回调里面去执行。

**Comment by divyathakkar4** [comment]
Facing same issue when try to fetch data from prepopulated database in www folder,
Getting Error:

> Unhandled JS Exception: undefined is not a function (near '...db.transaction...')

And this is my code Which I used to fetch data:

```
fetchDataDB(){
db = SQLite.openDatabase({name : "sqliteexample", createFromLocation : 1}, this.openCB, this.errorCB)

  db.transaction(function (tx) {
    tx.executeSql("SELECT * FROM Users", [], (tx, results) => {
        console.log("Query completed");
        var len = results.rows.length;
        console.log('len' + len)
        for (let i = 0; i < len; i++) {
          let row = results.rows.item(i);
          console.log(`word: ${row}`);
        }
      });
  });
}
```

**Comment by Amacelia** [comment]
Giving my two cents because I've reached this page (even though it's been three years since the original question, and two years since the last comment)

Seems as though you can do:
`SQLite.DEBUG(true);
SQLite.enablePromise(true);`


And then use this 'new promise' section to handle it:
`handlePPMDatabaseCalls() {
    return new Promise((resolve) => {
      db.transaction(function(tx) {
        //get last/most recent table name
        //read last 10 values from table
        tx.executeSql(
          'SELECT name FROM sqlite_master WHERE type="table"',
          [],
          function(tx, results) {
            var currTableNum = results.rows.length - 1;
            var currTableName = results.rows.item(currTableNum);
            console.log('PPM: ...reading last 10 values from table', currTableName);
            this.setState({tableName: currTableName});
          }
        );

        console.log('printing currtablename: ', this.state.tableName);

        tx.executeSql(
          'SELECT * FROM "?" ORDER BY ppm DESC LIMIT 10',
          [this.state.tableName],
          function(tx, results) {
            var total = 0;
            for (let i = 0; i < results.rows.length; i++) {
              total = total + results.rows.item(i);
              console.log('PPM: item to add: ', results.rows.item(i));
            }
            total = total / results.rows.length;
            console.log('PPM: setting ppmVal state: ', total);
            this.setState({ppmVal: total});
          }
        );
      });
    });
  }`

**Comment by swaroopaillinda** [comment]
Hi I ahe tried all solutions but anything did not work getting same error sql.transaction is undefined can you tell me how to resolve this

**Comment by gondooley** [comment]
I've uininstall and reinstalled the package and still no progress. DEBUG adds nothing in this case either. Please, if anyone has worked it out, can they let us know - I'm going nuts here.
