### ISSUE TITLE
No such table

### ISSUE THREAD

**Issue by fahadhaq** [andpor/react-native-sqlite-storage#218]
Hi, sorry to create a new post on this. I have tried all the suggestions but nothing seems to be working. I have followed the instruction on how to add pre-populated SQLite database several times and still getting 'no such table ' error. Here is my set up for the directory

<img width="428" alt="screen shot 2017-12-07 at 8 12 05 am" src="https://user-images.githubusercontent.com/2104888/33680616-104ede22-db27-11e7-9a0d-55c91ed83491.png">

<img width="425" alt="screen shot 2017-12-07 at 8 12 54 am" src="https://user-images.githubusercontent.com/2104888/33680618-128cdb12-db27-11e7-9082-6cb8878c4252.png">

Here is my code to openDB

```
let db = SQLite.openDatabase({ name: "test.db", createFromLocation: '~example.db', location: 'Library' }, this.openCB, this.errorCB);
        db.transaction((tx) => {
            tx.executeSql('SELECT * from test', [], (tx, results) => {
                console.log("Query completed");
            })
        })
```

Here is the log from XCode

[info][tid:com.facebook.react.JavaScript] OPEN database: test.db
[info][tid:com.facebook.react.SQLiteQueue][SQLite.m:179] Built path to pre-populated DB asset from app bundle subdirectory: /var/containers/Bundle/Application/26F87979-8A4F-4636-B690-3FAB114577E5/StudentCardApp.app/example.db
[info][tid:com.facebook.react.SQLiteQueue][SQLite.m:197] target database location: libs
[info][tid:com.facebook.react.JavaScript] new transaction is waiting for open operation
[info][tid:com.facebook.react.SQLiteQueue][SQLite.m:208] Opening db in mode READ_WRITE, full path: /var/mobile/Containers/Data/Application/D78A974F-353F-429F-85C9-7B943E11AC92/Library/test.db
[info][tid:com.facebook.react.SQLiteQueue][SQLite.m:235] Database opened
[info][tid:com.facebook.react.SQLiteQueue][SQLite.m:249] Good news: SQLite is thread safe!
[info][tid:com.facebook.react.SQLiteQueue][SQLite.m:255] open cb finished ok
[info][tid:com.facebook.react.JavaScript] Database OPENED
[info][tid:com.facebook.react.JavaScript] 'Error handler not provided: ', { message: 'no such table: test', code: 5 }
[info][tid:com.facebook.react.JavaScript] warning - exception while invoking a callback: {"line":91739,"column":25,"sourceURL":"/var/containers/Bundle/Application/26F87979-8A4F-4636-B690-3FAB114577E5/StudentCardApp.app/main.jsbundle","code":5}

**Comment by fahadhaq** [comment]
All good solved the issue

**Comment by dscx** [comment]
@fahadhaq what did you do to fix this? I am running into something similar.

**Comment by fahadhaq** [comment]
i think I changed the code to add a default location

`return SQLite.openDatabase({ name: "test.db", createFromLocation: '~test.db', location: 'Default' }, openCB, errorCB);`

Can you try this and let me know if that solves your problem. This was a while ago.

**Comment by dscx** [comment]
@fahadhaq thanks for the reply! It was a combination of this, and the physical file location in my project. 

If anyone finds this later, here's what worked for me:

`{` name: 'fileName.db', createFromLocation: '~fileName.sqlite', location: 'Library' }`

Also I had to create the www folder in the root of the whole project, not just the ios/android project, beforehand.

cheers!

**Comment by kaiyes** [comment]
@dscx  thanks mate. Adding the `location: 'Library'` solved my case too. My db was already in the www folder. Named `appName.sqlite`. Here are the full pics to help others. 
![screen shot 2018-07-16 at 12 39 31 pm](https://user-images.githubusercontent.com/5293742/42745592-6bceabde-88f5-11e8-9af8-43a03ae7a669.png)
![screen shot 2018-07-16 at 12 41 01 pm](https://user-images.githubusercontent.com/5293742/42745617-936e06da-88f5-11e8-9227-d18b627811a7.png)

**Comment by hyumus** [comment]
SQLite.openDatabase({name:"testDB.sqlite3",createFromLocation:1,location:'Library'}) . 
this solved my problem. testDB.sqlite3 file size is 24 MB. testDB.sqlite and testDB.db not working, but testDB.sqlite3 is working.
