### ISSUE TITLE
Full-text search using FTS3 or FTS4?

### ISSUE THREAD

**Issue by joshdhenry** [andpor/react-native-sqlite-storage#226]
Does this package support full-text search using FTS3 or FTS4?

**Comment by andpor** [comment]
This module is based on standard SQLite implementations on mobile devices. That said, if extensions you mention are built in to your device SQLite implementation, the module should be able to suppor the API calls.

**Comment by ataravati** [comment]
> This module is based on standard SQLite implementations on mobile devices. That said, if extensions you mention are built in to your device SQLite implementation, the module should be able to suppor the API calls.

@andpor Can you please elaborate on your answer? FTS is a very important feature. I think you should even have a section in your documentation for it.
