### ISSUE TITLE
Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by morfsys** [andpor/react-native-sqlite-storage#229]
I am trying to run a simple open db command on a component but for some reason I keep getting an error that say:
'Cannot read property 'open' of undefined'

Here is my simple component code:

`import React from 'react';
import { View, Text} from 'react-native';
import SQLite from 'react-native-sqlite-storage';
SQLite.DEBUG(true);
SQLite.enablePromise(true);
SQLite.enablePromise(false);
var db = SQLite.openDatabase({name:'newtest', createFromLocation: 1});

class LanguagesDB extends React.Component{
    render(){
        return (
            <View>
                <Text>Some text</Text>
            </View>
        )
    }
}

export default LanguagesDB;`

Also. I have made sure that my android/app/src/main/assets folder has a file named newtest.db with a table and values inside it.

What am I doing wrong here?

**Comment by andpor** [comment]
I can't tell. Please refer to documentation, looks like your project configuration is not correct.
