### ISSUE TITLE
How do I register the package in android?

### ISSUE THREAD

**Issue by christiansaiki** [andpor/react-native-sqlite-storage#23]
I didn't quite get how to install the Step 4 of the android instalation.
Do I need to change the MainActivity.java file or should I create another file?
Best Regards.

**Comment by christiansaiki** [comment]
I figured it out, the docs are outdated for React Native 0.18.0

To implement in the newest version of RN you have to edit MainActivity.java with the following code

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new SQLitePluginPackage(this));
    }
```

**Comment by andpor** [comment]
Yes, it could be your MainActivity.
