### ISSUE TITLE
Question: can I export/dump a table contents as a script?

### ISSUE THREAD

**Issue by scgough** [andpor/react-native-sqlite-storage#239]
Hello,
I want to be able to backup certain tables within my database so I can store them as a string (script) in iCloud/another key/value provider.

Is this possible?

for example, I might store: 

Key: `user`
Value: 
```
INSERT INTO User(name, email) values('bob','bob@mydomain.com');
INSERT INTO User(name, email) values('sue','sue@mydomain.com');
INSERT INTO User(name, email) values('pete','pete@mydomain.com');
INSERT INTO User(name, email) values('jim','jim@mydomain.com');
```

then, I can script a restore using it if a user were to change devices and install the app afresh.

**Comment by GulinSS** [comment]
@scgough could you publish your solution here? Same thing is needed for me. Need sync it somehow with clouds.

**Comment by scgough** [comment]
@GulinSS Hi - Sorry but I never did get a solution. If I remember correctly, the requirements for what I needed changed so I never persisted with this.
