### ISSUE TITLE
Cannot read property 'open' of undefined for react native 0.53.0 

### ISSUE THREAD

**Issue by giantss** [andpor/react-native-sqlite-storage#240]
This error appears when the plugin is initialized.
`Cannot read property 'open' of undefined` 
## environment
react native `0.53.0`
device  `ios Simulator` (Android did not try)

**Comment by ToJen** [comment]
Same, here for
```
react-native-cli: 2.0.1
react-native: 0.52.0
```

**Comment by giantss** [comment]
@ToJen Practice has proved that xcode simulator can not be used, real machine can be used normally

**Comment by ToJen** [comment]
I'm running this on an Android device.

**Comment by giantss** [comment]
I haven't used plugins on android phones yet.

**Comment by andpor** [comment]
There is no issue afaik. I run the test code inside both simulator and device on     
```
"react": "16.2.0",
"react-native": "0.52.1"
```
Both iOS and Android.

Any errors such as "open not found" etc are related to incorrect installation of the module in the project.

**Comment by ToJen** [comment]
Never mind, I was wrongly linking with `react-native link react-native-sqlite-storage` instead of using the linking instructions in the README. *faceplam*
