### ISSUE TITLE
 react-native link doesn't work

### ISSUE THREAD

**Issue by hrupin** [andpor/react-native-sqlite-storage#243]
Hello!

After yarn add react-native-sqlite-storage,
run react-native link 
i get:

>rnpm-install info Platform 'android' module react-native-android-sms-listener is already linked 
>rnpm-install info Platform 'ios' module react-native-i18n is already linked 
>rnpm-install info Platform 'android' module react-native-i18n is already linked 
rnpm-install info Platform 'ios' module react-native-sqlite-storage is already linked 
rnpm-install info Linking assets to ios project 
rnpm-install info Linking assets to android project 
rnpm-install info Assets have been successfully linked to your project 
rnpm-install info Platform 'android' module react-native-android-sms-listener is already linked 
rnpm-install info Platform 'ios' module react-native-i18n is already linked 
rnpm-install info Platform 'android' module react-native-i18n is already linked 
rnpm-install info Platform 'ios' module react-native-sqlite-storage is already linked 
rnpm-install info Linking assets to ios project 
rnpm-install info Linking assets to android project 
rnpm-install info Assets have been successfully linked to your project 

and the app is not going to

**Comment by umakantp** [comment]
And this happens with me too when I run link:-

Scanning folders for symlinks in E:\exp\watch-bse\node_modules (57ms)
rnpm-install ERR! Something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/facebook/react-native/issues

spawn UNKNOWN

**Comment by TPXP** [comment]
Making this module work with react-native link would avoid the hassle of setting it up manually. It's a quite common practice among React-Native module developers, adding this would be great !

**Comment by andpor** [comment]
agree...PR's are welcome (taking account both android and android-native implementations)

**Comment by creambyemute** [comment]
Rn-link in general is broken for me. Just link manually
