### ISSUE TITLE
no such table

### ISSUE THREAD

**Issue by martinblampied** [andpor/react-native-sqlite-storage#244]
Hi,

I've been getting "no such table" for the past hour when trying to load a sqlite .db from the bundle.

<img width="572" alt="screen shot 2018-04-04 at 11 13 15" src="https://user-images.githubusercontent.com/3713820/38302033-46593dc6-37f9-11e8-8c22-0835776f43a9.png">

<img width="262" alt="screen shot 2018-04-04 at 11 15 30" src="https://user-images.githubusercontent.com/3713820/38302134-8c1ae508-37f9-11e8-9c24-2bc32e6056da.png">

I have tried multiple variations of openDatabase but none work:

```
var db = SQLite.openDatabase({name : "decks", createFromLocation : "~decks.db"}, openCB, errorCB);
//var db = SQLite.openDatabase({name : "decks", createFromLocation: 1, location: 'Library' }, openCB, errorCB);
//var db = SQLite.openDatabase({ name: "decks.db", createFromLocation: '~decks.db', location: 'Default' }, openCB, errorCB);
//let db = SQLite.openDatabase({name: 'decks', createFromLocation : "~decks.db", location: 'Library'}, openCB, errorCB);
```

It always returns with:

Opening db in mode READ_WRITE, full path: /Users/martinblampied/Library/Developer/CoreSimulator/Devices/62030A49-ED82-46E0-8206-5839A6EF9730/data/Containers/Data/Application/2A946053-161E-456D-8815-0C397958E45C/Library/LocalDatabase/decks
RCTLog.js:48 Database opened
RCTLog.js:48 Good news: SQLite is thread safe!
DAL.js:22 Database OPENED
sqlite.core.js:82 SQLite.backgroundExecuteSqlBatch({"dbargs":{"dbname":"decks"},"executes":[{"qid":1111,"sql":"BEGIN","params":[]},{"qid":1111,"sql":"select * from pffydict limit 100","params":[]}]})
RCTLog.js:48 open cb finished ok
sqlite.core.js:475 Error handler not provided:  {message: "no such table: pffydict", code: 5}code: 5message: "no such table: pffydict"__proto__: Object
sqlite.core.js:572 warning - exception while invoking a callback: {"code":5}
sqlite.core.js:82 SQLite.backgroundExecuteSqlBatch({"dbargs":{"dbname":"decks"},"executes":[{"qid":1111,"sql":"ROLLBACK","params":[]}]})

When I look in simulator library I can see my db is 0kb:
<img width="580" alt="screen shot 2018-04-04 at 11 21 27" src="https://user-images.githubusercontent.com/3713820/38302381-5e8f2954-37fa-11e8-885c-9819945cb866.png">

It must be unable to copy my db for some reason? Any thoughts?

**Comment by martinblampied** [comment]
Eventually got this working with:
`let db = SQLite.openDatabase({name: 'Decks.sqlite', createFromLocation : "~www/Decks.sqlite", location: 'Library'}, this.openCB, this.errorCB);`

Standard React Native, nothing just works. Eventually exported my db as .sqlite not .db and make sure you close everything - stop xcode and all terminal window if you update database as everything was caching.

**Comment by hyumus** [comment]
SQLite.openDatabase({name:"testDB.sqlite3",createFromLocation:1,location:'Library'}) . 
this solved my problem. testDB.sqlite3 file size is 24 MB. testDB.sqlite and testDB.db not working, but testDB.sqlite3 is working.
