### ISSUE TITLE
parentheses in Readme, part 4, android 

### ISSUE THREAD

**Issue by Whispers12** [andpor/react-native-sqlite-storage#246]
Fix this issue

![image](https://user-images.githubusercontent.com/30667180/38617845-ba8a8950-3da0-11e8-8e4b-c7bd9886f359.png)

**Comment by Whispers12** [comment]
https://github.com/andpor/react-native-sqlite-storage/pull/245

**Comment by andpor** [comment]
This is incorrect. I reverted your PR. The original code sample is fine

{ return Arrays.<ReactPackage>asList(new SQLitePluginPackage(),new MainReactPackage()); }
