### ISSUE TITLE
Create Table

### ISSUE THREAD

**Issue by valmadsonvieira** [andpor/react-native-sqlite-storage#247]
I try create table with this code :
    db.transaction((tx) => {
      tx.executeSql("CREATE TABLE IF NOT EXISTS history ( id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, description TEXT )", [], (tx) => {
        });  
    }); 

but does not create. another option to create.

**Comment by andpor** [comment]
This is standard SQL. Please take a look at SQL spec to see what's supported for Table creation. See examples in this module for working CREATE Table statements.
