### ISSUE TITLE
Upgrade schema with application version

### ISSUE THREAD

**Issue by clovelCed** [andpor/react-native-sqlite-storage#248]
Hello,

I would like to add a column to a table that contains data.

Is it possible to update the table according to the versions of the application?

I wish to do something like this  : 

`@Override
public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
    // add new columns to migrate to version 2
    if (oldVersion < 2) { 
        db.execSQL("ALTER TABLE " + TABLE_NAME + "ADD COLUMN school VARCHAR(250)");
    }
    // add new columns to migrate to version 3
    if (oldVersion < 3) { 
        db.execSQL("ALTER TABLE " + TABLE_NAME + "ADD COLUMN age INTEGER");
    }
}`

I could update the schema according the application version.

Thanks

**Comment by andpor** [comment]
Yes, that should be possible, don't see why not.

**Comment by ajaysaini-sgvu** [comment]
@clovelCed  @andpor  What is the correct way of doing this ?
