### ISSUE TITLE
Could't run `pod install` because of capital Y in Podfile

### ISSUE THREAD

**Issue by mkappelhof** [andpor/react-native-sqlite-storage#251]
In the demo Podfile the Yoga name should probably be in lowercase since i got the following message (macos 10.13.4) when i ran `pod install`

`[!] The name of the given podspec 'yoga' doesn't match the expected one 'Yoga'`

`pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'` however worked fine

**Comment by andpor** [comment]
Wonder if there is anyone else experiencing the same issue...you are the first one to report the case significance...

**Comment by andpor** [comment]
Looks like the podfile definition is correct in this repo. see [](https://github.com/facebook/react-native/issues/12670)
