### ISSUE TITLE
advice about transaction() implementation

### ISSUE THREAD

**Issue by elanpang** [andpor/react-native-sqlite-storage#255]
I'm using this plugin for my app, but I read the core.js and have some advices in transaction();

SQLitePlugin.prototype.executeSql
the executeSql() function in SQLitePlugin is ok, it builds a SQLitePluginTransaction and exec immediately.

but, for blow funciton
SQLitePluginTransaction.prototype.executeSql 
I think this executeSql inside  transaction() fn callback maybe is not a convenient design.

1. it doesn't return the result immediately, so if the 2nd statement need the result, it is difficult, I saw the tx.executes check , but it means the function call plugin.exec() again, I didn't read the native source code yet, I dont know if it is a real transaction or has any performance issue.

2. it accepts callback param and looks like a async function, but in actully it is not real async, it was only used to collection a list of callbacks for transaction(), that's easy to feel strange and confuse.
maybe the callbacks should be the params of transaction(),
maybe transaction(fn, error, success)  should be designed like transaction(statementArray,error, success)
looks better, a batch executor.

3. for a real tansaction() function I think should provide a real sync executeSql() function for fn-tx, not accept callback and return the result  immediately, what about it?
the tansaction() function is async, but the param fn callback shouldn't be async, but tx.executeSql() inside is async(inactully it is not, but it returns result callback param),  I think this is a design issue, so if someone want to use Promise with it I think it will easy cause some issues.

**Comment by andpor** [comment]
thanks for suggestions.
