### ISSUE TITLE
no item return when inserting

### ISSUE THREAD

**Issue by joshuadiezmo** [andpor/react-native-sqlite-storage#256]
I try 

`db.transaction(tx => {
            tx.executeSql('INSERT INTO table (var1, var2) VALUES (?,?)', [1,2], (tx, results) =>{
let row = results.rows.item(0);
}, err => console.error(err));
        })`

then row is undefined.

**Comment by andpor** [comment]
is your SQL correct? what is the value you pass in for 'table' ? table is a reserved word in SQL afaik...

**Comment by andpor** [comment]
tx.executeSql('INSERT INTO table (var1, var2) VALUES (?,?)', [1,2], (tx, results) =>{ let row = results.rows.item(0); }, err => {console.error(err);}  );

SQL error is returned on error callback
{"message":"near \"table\": syntax error","code":5}

**Comment by andpor** [comment]
also syntax looks incorrect...this is correct...
        db.transaction(tx => { tx.executeSql('INSERT INTO table (var1, var2) VALUES (?,?)', [1,2]); }, (tx, results) => {
          let row = results.rows.item(0);
        }, err => {
          console.error(err)
        });

**Comment by andpor** [comment]
Closing as non-issue.
