### ISSUE TITLE
Can't open database on android

### ISSUE THREAD

**Issue by martinblampied** [andpor/react-native-sqlite-storage#257]
After spending about 4 hours messing around with this, moving files into www folder directories and 200 variations of openDatabase I finally got this working on iOS using: 

`db = SQLite.openDatabase({name: 'Decks.sqlite', createFromLocation : "~www/Decks.sqlite", location: 'Library'}, this.openCB, this.errorCB);`

However this doesn't work on Android. 

<img width="471" alt="screen shot 2018-05-20 at 16 18 49" src="https://user-images.githubusercontent.com/3713820/40280347-97799b64-5c49-11e8-8a55-347a23306f8e.png">

I've followed https://github.com/andpor/react-native-sqlite-storage-examples/tree/master/PrepopulatedDatabaseExample and tried multiple variations of the below command - none work:

```
db = SQLite.openDatabase({name: 'Decks.db', createFromLocation : "~Decks.sqlite", location: 'Library'}, this.openCB, this.errorCB);
db = SQLite.openDatabase({name: 'Decks.sqlite', location: 'default'}, this.openCB, this.errorCB);
db = SQLite.openDatabase({name : "Decks", createFromLocation : 1}, this.openCB, this.errorCB);
db = SQLite.openDatabase({name: 'test.db', createFromLocation : "~Decks.sqlite", location: 'Library'}, this.openCB, this.errorCB);
```

I can't see my db file on the simulator, looking inside data/app/com.decks. The file should be getting copied no?

<img width="720" alt="screen shot 2018-05-20 at 16 24 05" src="https://user-images.githubusercontent.com/3713820/40280386-4a9d898a-5c4a-11e8-9dd8-fa74441d808f.png">

This library is turning out to be a massive time sync. Any help would be appreciated..

**Comment by ertejaspatel** [comment]
Hi Is there any solution to this problem?

**Comment by andpor** [comment]
Did you check native logs? If you run the app from simulator you should see them in the IDE...it should have additional debugging information
