### ISSUE TITLE
Exception on echoTest > undefined is not an object (evaluating 'NativeModules["SQLite"][method]')]

### ISSUE THREAD

**Issue by cbellier** [andpor/react-native-sqlite-storage#258]
Hello,

I know there are already many closed issues with this error mentioned and that the solution is to follow thoroughly the documentation to manually link the library, but still, I cannot get it working...

When running the echoTest() function I get :

> [Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'NativeModules["SQLite"][method]')]
> - node_modules/react-native-sqlite-storage/lib/sqlite.core.js:84:26 in exec
> - node_modules/react-native-sqlite-storage/lib/sqlite.core.js:790:14 in echoTest
> - node_modules/react-native-sqlite-storage/sqlite.js:72:23 in <unknown>
> - node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
> - node_modules/promise/setimmediate/core.js:200:23 in doResolve
> - node_modules/promise/setimmediate/core.js:66:12 in Promise
> - node_modules/react-native-sqlite-storage/sqlite.js:59:32 in <unknown>
> * src/tools/database/players.js:18:11 in open
> * src/tools/database/players.js:61:2 in getAllPlayers
> * src/containers/Connect.js:22:8 in componentWillMount
> - node_modules/react-proxy/modules/createPrototypeProxy.js:44:35 in proxiedMethod
> - node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:6698:6 in callComponentWillMount
> - ... 18 more stack frames from framework internals
> 

I'm trying to use the library for Android app.
I'm under the following modules versions :

- "expo": "27.0.1"
- "react": "16.3.2"
- "react-native": "0.55.4"
- "react-native-sqlite-storage": "3.3.4"

Here is how I included the lib in Android files :

settings.gradle
```
rootProject.name = 'test'

include ':app'

include ':react-native-sqlite-storage'
project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android')
```

build.gradle

```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-sqlite-storage')
}
```

MainApplication.java

```
import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import org.pgsqlite.SQLitePluginPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new SQLitePluginPackage(),
          new MainReactPackage()
      );
    }
```

I tried removing node_modules and launching ./gradlew clean without success.

Am I missing something obvious ?
Thanks for your help.

**Comment by andpor** [comment]
try reversing the module list..

                .addPackage(new MainReactPackage())
                .addPackage(new SQLitePluginPackage())       // register SQLite Plugin here

**Comment by cbellier** [comment]
Thank you for fast answer.
I'm using the MainApplication.java technic to register the module.
I tried to reverse the module list in getPackages function but same result...

**Comment by cbellier** [comment]
Hey,
I got rid of expo and it's working fine now.
Thank you for the module !
