### ISSUE TITLE
Has anyone gotten this working in Xcode 7?

### ISSUE THREAD

**Issue by philharton** [andpor/react-native-sqlite-storage#26]
Followed the instructions but had to change things slightly here: https://github.com/andpor/react-native-sqlite-storage#step-2-xcode-sqlite-project-dependency-set-up

This step shows a "Frameworks" folder with "libsqlite3.0.dylib" under the main project. The Frameworks folder seems to be absent in the Xcode 7 side panel, but I was able to get it to build by going into the project Build Phases and adding "libsqlite3.0.tbd" as it seems that's the new way.

But when I run the example test code I get this:

![image](https://cloud.githubusercontent.com/assets/513325/12528046/8b912ff4-c1c5-11e5-8b9c-060cb7b933b6.png)

If I completely remove the react-native-sqlite-storage project from my Xcode project I get the same error, so it looks like the JS is trying to reference something in native that doesn't exist.

Running Xcode Version 7.2 (7C68)

**Comment by salbito** [comment]
I too am running into some issues with this library. Though I don't get as far as the OP. My install stops on attempting to use the 'open' method.

#### Things of Note
* React Native Version 0.18.0
* Xcode Version 7.2 (7C68)
* Attempted libsqllite.a install via the following means
  * libsqlite3.0.tbd in Build Phases
  * adding -libsqlite flag to Other Linker Flags

#### Stacktraces
<img width="1199" alt="screenshot 2016-01-23 16 18 34" src="https://cloud.githubusercontent.com/assets/178271/12529022/b5f621aa-c1ed-11e5-8547-70e471c38120.png">

#### Red Screen of Death
<img width="464" alt="screenshot 2016-01-23 16 18 11" src="https://cloud.githubusercontent.com/assets/178271/12529023/be73de6c-c1ed-11e5-8000-38213d04e861.png">

**Comment by andpor** [comment]
The library has been developed with React 14 not been tested with ReactNative 18. I should have included it in the README.

**Comment by andpor** [comment]
@philharton - the class not found SQLiteFactory is a JavaScript object. The code does not even get into native module resolution if it cannot find this variable so I doubt this has anything to do with XCode7.

**Comment by andpor** [comment]
@salbito - your error is different from @philharton . Looks like the native module for SQLite cannot be resolved somehow. You should not have to add any special linker or compiler flags. Adding libsqlite via the normal link with Libraries screen should do the trick. How are you adding libsqlite ? it should go to the PARENT project...can you provide screenshot of your project structure in XCode showing libsqlite library in it?

**Comment by salbito** [comment]
@andpor Hey thanks for the response. So...linking libsqlite is quite a bit different in Xcode 7. I'll keep trying and see what I come up with.

This issue seems to point at linking to a .tbd file over the .dylib. I'll take a look when I get home.
https://github.com/almost/react-native-sqlite/issues/21

**Comment by andpor** [comment]
@salbito @philharton - i have just installed everything from scratch and run the library in XCode7 and React 0.18.1 - everything works fine, no tweaking or code change is required. The only difference is that the ios sqlite library has tbd suffix instead of dynlib. I literally ran everything without making a single change to the library. I will close this thread.

**Comment by andpor** [comment]
![screen shot 2016-01-25 at 4 28 19 pm](https://cloud.githubusercontent.com/assets/10236571/12555661/7a56723a-c382-11e5-9c96-667146f4c894.png)

**Comment by andpor** [comment]
@philharton Frameworks is a grouping you add yourself to the project, it is not something you get by default in project structure. I like to put all my frameworks from iOS inside this group to keep things organized neatly...

**Comment by philharton** [comment]
@andpor I just tried again with a freshly init'ed React Native project and it worked, so there must have been a conflict with another package I was using (I'm thinking react-native-webpack-starter-kit may be the culprit). Will figure it out, thanks for your help and I really appreciate you making this package available to the community!
