### ISSUE TITLE
sqlite-storage don't save in .db ?

### ISSUE THREAD

**Issue by Valmadson** [andpor/react-native-sqlite-storage#261]
Hello everyone. I can insert, edit, delete in my .db, but when I will see it in .db folder in /android/app/src/main/assets/example.db, nothing is saved. the emulator create a database temporary ?

**Comment by andpor** [comment]
The actual database is created elsewhere. Please refer to the documentation. The database provided in the application is used for initializing the target database only. You can figure out the location of the actual database file if you put a breakpoint in your IDE on a line from SQLPlugin file ...

**Comment by raindev32** [comment]
this problem solved ?

because i face same issues like this..
