### ISSUE TITLE
How to setup react-native-sqlcipher-storage with Cipher?

### ISSUE THREAD

**Issue by Paradox-AT** [andpor/react-native-sqlite-storage#263]
https://github.com/axsy-dev/react-native-sqlcipher-storage

Please update the instructions to use the lib. The lib is no longer available in npm repo.
Also I am not able to link the lib into an ios project.

## Expected Behavior

The instructions should work as described in the documentation

## Current Behavior

The documented instructions no longer work

## Your Environment

* React Native SQLite Storage Version used: latest 
* React Native version used: 0.55.4

**Comment by andpor** [comment]
Are you sure you posted to the right repo?

**Comment by Paradox-AT** [comment]
Oops..! :P
