### ISSUE TITLE
How to deal with migrations

### ISSUE THREAD

**Issue by otaviogaiao** [andpor/react-native-sqlite-storage#264]
Hi. First of all, thanks for this amazing library. 
Sorry for opening an issue, since its not really a problem, just lack of knowledge. But I couldn't find any material online about it.

The questions is the following: How to deal with database structure changes that may happen in the future? I come from Ruby on Rails and there we have a migration thing, many files, one for each change in the database that runs in sequence. That makes sure we get a consistent database if we need to install the system again.

Is there anything like that for SQLite and React Native? How should I deal with possible database changes when an user updates my app? What are the steps to follow? Any material about this would be great.

Thank you very much.

**Comment by otaviogaiao** [comment]
I talked to some people and got a sense of what I will do: create a script to generate my database, put my migrations in an array, get the version of the database (1, 2, 3...), then run the parts of the array above my current version. That should do it. I'm calling this script every time the app loads.

**Comment by andpor** [comment]
yes indeed, that's the pattern...

**Comment by spruce-bruce** [comment]
I have this code that works for an example https://gist.github.com/spruce-bruce/97ed3d0fddab3a93082b71c228c7e5a8

**Comment by larkintuckerllc** [comment]
Ended up writing a bit on this; really just needed something simple.
https://medium.com/@johntucker_48673/react-native-sqlite-and-migrations-bc72b70e66fb
