### ISSUE TITLE
How to reach database file in Android ExternalStorage?

### ISSUE THREAD

**Issue by entronad** [andpor/react-native-sqlite-storage#267]
My database is downloaded to the ExternalStorage(RNFetchBlob.fs.dirs.SDCardApplicationDir) like "/storage/emulated/0/Android/data/com.xxxx/files/db3/db.db3", but it seems the createFromLocation param of SQLite.openDatabase() could only support InternalStorage(RNFS.DocumentDirectory), and do not support absolute path.
How could I reach database file in Android ExternalStorage?

**Comment by entronad** [comment]
I have found the way. Just use the origin methode:
`SQLite.openDatabase("myDatabase.db", "1.0", "Demo", -1);`
"myDatabase.db" could be any absolute path.

**Comment by aliwaqassi** [comment]
can you help me with this?
