### ISSUE TITLE
Docs absent about using Transaction in sqlite with this package

### ISSUE THREAD

**Issue by ranjeet3152** [andpor/react-native-sqlite-storage#270]
I need to use transaction with my sqlite code in react-native. I was not able to find any documentation or post about that so I am unsure how to proceed with it. I have seen code in package [addTransaction](https://github.com/andpor/react-native-sqlite-storage/blob/4b22adf9586ec3fb89650f1277787cf0e4a095f3/lib/sqlite.core.js#L115). It would be great if you can provide a code snippet or how addTransaction or startNextTransaction works and how to use them. It would be great help. 
If from your guidance I would be able to do that. I will give a PR about this in docs for people use.

**Comment by andpor** [comment]
Look at the demo code in test directory or check [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) repo.
