### ISSUE TITLE
test with react-native-slqite-storage

### ISSUE THREAD

**Issue by enieber** [andpor/react-native-sqlite-storage#274]
I tried test my code that use the lib react-native-sqlite-storage [this code](https://github.com/andpor/react-native-sqlite-storage/blob/4b22adf9586ec3fb89650f1277787cf0e4a095f3/lib/sqlite.core.js#L53-L55) return this error

> ReferenceError: window is not defined

this issue has relation with issue #168

**Comment by andpor** [comment]
Did you resolve your issue ?

**Comment by enieber** [comment]
hi @andpor this error has persist [because this line in sqlite.core.js](https://github.com/andpor/react-native-sqlite-storage/blob/8c935c4792f6ef323b6e6c42afb876611a1ba97b/lib/sqlite.core.js#L53-L55)
