### ISSUE TITLE
Install Dependencies With CocoaPods , run pod install error

### ISSUE THREAD

**Issue by aiynmm** [andpor/react-native-sqlite-storage#275]
I install dependencies as the md file saying, then have a error when run pod install.

Here is the error:
[!] Unable to find a specification for `yoga (= 0.55.4.React)` depended upon by `React/Core`

Here are versions info:
"react": "16.3.1",
"react-native": "0.55.4",

**Comment by xuechinahb** [comment]
add follow code to Podfile:
`pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
`
