### ISSUE TITLE
Unable to find a specification for `yoga (= 0.56.0.React)` depended upon by `React/Core`

### ISSUE THREAD

**Issue by sj602** [andpor/react-native-sqlite-storage#276]
I installed react-native-sqlite-storage on ios.
I followed installation guide but I encountered this issue.
I searched the issue and I did it following [this link](https://github.com/Alamofire/Alamofire/issues/1727), but it doesn't work.

## Current Behavior

I added 
'
pod 'React', :path => '../node_modules/react-native'
pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage
'
to my Podfile
and I did 'pod install'
pod console returns...

Unable to find a specification for `yoga (= 0.56.0.React)` depended upon by `React/Core`

## Your Environment

* React Native SQLite Storage Version used: 3.3.6
* React Native version used: 0.56.0
* Operating System and version (simulator or device): Mac OS
* IDE used: VS Code
* Link to your project:

**Comment by sj602** [comment]
I found the solution by adding this to Podfile.
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

**Comment by kaiyes** [comment]
thanks a lot @sj602  had the same issue and adding that line solved my problem. Cheers mate
