### ISSUE TITLE
undefined is not an object (evaluating 'NativeModules["SQLite"][method]')

### ISSUE THREAD

**Issue by thiagovictorino** [andpor/react-native-sqlite-storage#285]
Hi guys!

I know that have a lot of this same title issue here, but I think that maybe in 2018 has something different to do to make it happen.

My current versions are:

```
  "dependencies": {
    "expo": "^27.0.1",
    "fs": "0.0.1-security",
    "native-base": "^2.7.2",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-easy-toast": "^1.1.0",
    "react-native-router-flux": "^4.0.1",
    "react-native-sqlite-storage": "^3.3.6"
  }
```

I am trying to run this pack in my iOS project. I did everything that the documentation said and I got this erros:

 TypeError: TypeError: TypeError: undefined is not an object (evaluating 'NativeModules["SQLite"][method]')

```
This error is located at:
    in HomeScreen (at navigationStore.js:422)
    in Wrapped (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:574)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)
```

**Comment by andpor** [comment]
The error indicates bad installation/configuration of the plugin project. Some people have reported issues caused by Expo..not sure since you are not providing any information on how the plugin is configured in your project

**Comment by thiagovictorino** [comment]
Hi!

I decide to use Realm instead SQLite. But what andpor said make sense.

In Realm I had to use detached from Expo. Infact, I will never ue Expo again.

Closing this issue and hoping that this information could help anyone in the future.
