### ISSUE TITLE
SDK Build Tools revision is too low

### ISSUE THREAD

**Issue by stigi** [andpor/react-native-sqlite-storage#286]
ReactNative 0.56 changed the SDK level for android builds to 25. 

## Expected Behavior

Including the library as described in the Readme works for a newly created project on `react-native@0.56.0` and Gradle (or `react-native run-android` for that matter) is able to build the app.

## Current Behavior

The build fails with the following error:

`The SDK Build Tools revision (23.0.1) is too low for project ':react-native-sqlite-storage'. Minimum required is 25.0.0`

## Possible Solution

#279 mentioned a solution which does nothing but changing the setting on `react-native-sqlite-storage` inside `node_modules` and will be overwritten on a new npm/yarn install (not to mention a CI scenario or other collaborators).

A solution (I'll send a PR in a second) could be to fetch the SDK versions from the root project:

```gradle
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 26)
    buildToolsVersion safeExtGet('buildToolsVersion', '26.0.3')

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 26)
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}
```

## Steps to Reproduce (for bugs)

- `react-native init` with version 0.56
- `yarn add react-native-sqlite-storage` + Follow readme to add it to the Android project
- `cd android`
- `./gradlew assembleDebug` -> Fails

## Context

This blocks me from adding typeorm to my current react native project. Will block others who use the most current react-native version or who manually updated their sdk versions, too.

Also:

> Google Play will require that new apps target at least Android 8.0 (API level 26) from August 1, 2018, and that app updates target Android 8.0 from November 1, 2018. - [Source](https://developer.android.com/distribute/best-practices/develop/target-sdk)

## Your Environment
* React Native SQLite Storage Version used: `3.3.6`
* React Native version used: `0.56.0`

**Comment by andpor** [comment]
Your PR is merged.
