### ISSUE TITLE
Doing correct setup for iOS but can't open db, getting undefined this.database.transaction

### ISSUE THREAD

**Issue by Vicos4** [andpor/react-native-sqlite-storage#288]
## Expected Behavior

Following setup, linking manually, tried also linking with Cocoa Pods and rnpm link but none worked

I can open this database in another react-native project, and the library works, but I cannot create a new react-native project with sqlite and have it work.

## Current Behavior

getting Possible unhandled Promise rejection evaluating this.database.transaction.

## Steps to Reproduce (for bugs)

Create a new react-native project
Follow iOS Setup linking the libraries manually. 
Try opening a database.

## Your Environment

* React Native SQLite Storage Version used: 3.3.6
* React Native version used:0.56
* Operating System and version (simulator or device): Mac OS High Sierra 
* IDE used: Visual Studio Code and XCode 9.41

**Comment by Vicos4** [comment]
<img width="338" alt="screen shot 2018-09-04 at 11 24 06 pm" src="https://user-images.githubusercontent.com/10899905/45069327-fa434e80-b099-11e8-9bd8-5eab32d9113d.png">

**Comment by Vicos4** [comment]
<img width="337" alt="screen shot 2018-09-04 at 11 24 14 pm" src="https://user-images.githubusercontent.com/10899905/45069333-0202f300-b09a-11e8-85e5-3a888f3f9f05.png">

**Comment by Vicos4** [comment]
<img width="337" alt="screen shot 2018-09-04 at 11 24 19 pm" src="https://user-images.githubusercontent.com/10899905/45069339-06c7a700-b09a-11e8-9145-7d45c63dfaab.png">

**Comment by andpor** [comment]
can you attach screenshots showing your project configuration (relevant pieces) and XCode debug console output.

**Comment by Vicos4** [comment]
Here is the package.js file, index.js file, my db.js file and the method that I am calling is the getAll()

**Comment by Vicos4** [comment]
<img width="581" alt="screen shot 2018-09-13 at 8 27 28 pm" src="https://user-images.githubusercontent.com/10899905/45522842-986a9f00-b793-11e8-956a-47ca5cde208b.png">
<img width="570" alt="screen shot 2018-09-13 at 8 27 45 pm" src="https://user-images.githubusercontent.com/10899905/45522843-986a9f00-b793-11e8-8acb-587f3caaf637.png">
<img width="593" alt="screen shot 2018-09-13 at 8 27 52 pm" src="https://user-images.githubusercontent.com/10899905/45522844-986a9f00-b793-11e8-8f77-90bd1c684e3c.png">

**Comment by Vicos4** [comment]
<img width="614" alt="screen shot 2018-09-13 at 8 26 18 pm" src="https://user-images.githubusercontent.com/10899905/45522855-a6b8bb00-b793-11e8-8d43-ad12e3134443.png">
<img width="500" alt="screen shot 2018-09-13 at 8 27 06 pm" src="https://user-images.githubusercontent.com/10899905/45522856-a6b8bb00-b793-11e8-8194-57a1c9ae1869.png">
<img width="593" alt="screen shot 2018-09-13 at 8 27 52 pm" src="https://user-images.githubusercontent.com/10899905/45522858-a6b8bb00-b793-11e8-830b-54695b3e48a4.png">

**Comment by andpor** [comment]
really have not spent too much time on this but some things look interesting...

1. do not see the code that instantiates the database
2. do you think it is proper to refer to 'this' inside a static function getAll?

**Comment by andpor** [comment]
Closing for lack of followup. static function and use of this in it seems to be the culprit.
