### ISSUE TITLE
Any errors in code are suppressed if the call emanated from a DB callback

### ISSUE THREAD

**Issue by MossP** [andpor/react-native-sqlite-storage#29]
e.g.

```
aFunction: function(){
  DBHelper.doSomething("SQL HERE", this.successCB, this.errorCB)
},

successCB: function(response){
  // intentional crash..
  var x = b;
  // this error does not trigger a RSOD.
},

errorCB: function(){
},
```
Can this 'feature' be disabled? It makes debugging very difficult.

Thanks for a great component :+1:

**Comment by andpor** [comment]
@MossP  - not getting you point..can you elaborate more ?

**Comment by MossP** [comment]
Sorry. What I'm trying to say is.. If there is an error in a function and I call it normally, I will get the Red Screen of Death - with information to help me debug the error but; If I call the function that has the error from the successCallback then the error does not show. It silently disappears. No error is shown.

**Comment by brodybits** [comment]
@MossP if you need to detect the error for debugging, I suggest you wrap your code in a try/catch block.

**Comment by MossP** [comment]
@brodybits That would work if I knew where the errors were but, let's say i save a typo in file and that file is called somewhere - even at the end of a long chain of calls, and even a syntax error - from a DB callback then the whole thing fails silently with no clue as to what the error might be. This leads to lots of stepping through code when looking for possible errors.

React Native was written specifically with the Red Screen of Death to aid in debugging of errors but the whole thing gets suppressed by the component.

**Comment by andpor** [comment]
@MossP please suggest a solution..

**Comment by MossP** [comment]
Yeah, I see that, but I assume the component calls the callbacks inside a try catch. I'll need to go familiarise myself with the code more to be sure. This may be why any error in executed code are skipped over. I'm happy to look for a solution I just wasn't sure if it was something that had been intentionally done without considering the side effects.

Leave it with me.

**Comment by andpor** [comment]
I am going to close this issue for now since this is not something that is originated by the plugin code. If you manage to come up with a solution please submit a PR and I will merge for everyone's benefit.
