### ISSUE TITLE
How to use the versionCode ?

### ISSUE THREAD

**Issue by yuanmaole** [andpor/react-native-sqlite-storage#296]
my app Is online. and i use the sqlite and create a tabel with 12 feilds, but now i need add 2 feilds ，How to use the version code so that I can add 2 fields without delete table and use it normally.

**Comment by liweijieok** [comment]
I had the same problem.

**Comment by andpor** [comment]
Add appropriate tables for schema version management to your database.

**Comment by liweijieok** [comment]
Thx, I use  `AsyncStorage` to save the DB version. Every time I use the database for operation, first check whether the database version changes. If changed, the database is first modified on the field, and then operate on the specific data table.
