### ISSUE TITLE
Select returns undefined results

### ISSUE THREAD

**Issue by BAndonovski** [andpor/react-native-sqlite-storage#299]
I have a simple case scenario where I create the database and the table, add a couple of records, and when I try to query them, I get `undefined` response.

## Expected Behavior
I expect to get the rows I just added

## Current Behavior
I get an `undefined` response

## Steps to Reproduce (for bugs)
```javascript
const db = await sql.openDatabase({ name: 'database.db', location: 'Documents' });
await db.executeSql(`create table if not exists Test(
      id text primary key not null,
      name text not null,
    )`);
await db.executeSql(`insert into Test(id, name), ("id", "name")`);
const res = await db.executeSql('select * from users;'); //res === undefined
```

## Your Environment
* React Native SQLite Storage Version used: "react-native-sqlite-storage": "^3.3.6",
* React Native version used: "react-native": "0.57.0",
* Operating System and version (simulator or device): macOS Mojave, Xcode 10, iPhone Xs Max

**Comment by ricardodrs** [comment]
@BAndonovski any soluction?

**Comment by BAndonovski** [comment]
@ricardodrs yup, you need to call 
```
sql.enablePromise(true);
```

before anything else to get this to work. Couldn't find it in the docs, but scanning through the code made this obvious.
