### ISSUE TITLE
Storing Large string

### ISSUE THREAD

**Issue by ricardodrs** [andpor/react-native-sqlite-storage#300]
Hello Everyone,

I'm trying store a large string with 9 000 000 lines. Whe I do the insert, this not return a error, but when I do the select, there return null response. I wanna know why this is happening, cause in sqlite website the max lenght for a varchar colum is 500 millions.

Thx.

**Comment by dryganets** [comment]
9000000 symbols, or lines?
Could you give a little bit more details for example what kind of exception you are getting?
Maybe you have a repository with a simple repro handy?
Is it Android, iOS, both?

As a workaround, you could try blob, but it could be some weird bug.
It is around 18Mb string and given that there is some copy overhead in both JNI, react-native framework and JavaScriptCore the peak memory allocation could be pretty high.

**Comment by ricardodrs** [comment]
@dryganets I'm sorry, I mean 9 000 000 symbols, I'm using Android and already test with blob variable. On the SGBD I can do the insertion and selection, but on react native I just can do insertion.

**Comment by dryganets** [comment]
What kind of error you are getting?
You could run shell command adb logcat | grep AndroidRuntime

To see the crash info.

**Comment by ricardodrs** [comment]
@dryganets Any error, just a null response.

**Comment by ricardodrs** [comment]
Code of selection, remember, with small strings this works normally.  

` let result = new Promise((resolve)=> {
    db.transaction(function (tx) {
      
    
      tx.executeSql('SELECT feature FROM json WHERE id = ?', [1], (tx, results) => {
        
        console.log('Deu certo!(RELATIVAMENTE)');
        tx.finalized = false;
        var row = 0;
        var len = results.rows.length;
        for (let i = 0; i < len; i++) {
          row = results.rows.item(i).feature;

          console.log('RESULTS>>>', results);
          console.log('LEN>>>', len)
          resolve(results);

        }
        console.log('CROPLINES2>>>', JSON.parse(row));
      });
      
    });
  
  });
  result.then((res)=>{
    this.setState({features1:res.rows.item(0).feature});
    console.log('RES>>>',this.state.features1);
  });`

**Comment by dryganets** [comment]
I'm asking for the project I could use for debugging. Ideally, if it reproduces the issue and I could focus on the problem. It will take some time to prepare it, maybe not too much but I don't have that time now.

To be honest with you this is not a mainstream scenario.
I would avoid sending 18mb over the bridge in react-native.
I would rather process the data on the native layer and return needed chunks of data from my custom native module instead.

The same thing with the passing image blobs - there are many more efficient ways to solve the problem differently :)

**Comment by ricardodrs** [comment]
I solve my issue with react-native-fs, thx for the help 👍
