### ISSUE TITLE
Support for opening an existing sqlite file at runtime

### ISSUE THREAD

**Issue by mart2967** [andpor/react-native-sqlite-storage#31]
I'm developing an app (android first) that needs to fetch a remote database and read data from it. I'm not sure how or if that can be accomplished using this library, but I saw some promising discussions on the cordova-sqlite-storage repo and figured I'd better ask here before writing my own native module.

https://github.com/litehelpers/Cordova-sqlite-storage/issues/426 implies that this workflow is possible, if one knows the directory that the plugin searches for databases.

Is that also true for this library? Ideally I could copy the db to wherever, then open and use it.

**Comment by andpor** [comment]
Yeah that is a nice feature to have. I looked at Chris Brody's comments on the issue...will think about this one..

**Comment by andpor** [comment]
I have made some modifications to iOS implementation to support retrieval of the prebuild database from a number of place. There are 4 options:

- default, plugin will look in www directory of app bundle for a file with the same name as the database. This is for backward compatibility
- path provided starts with ~. This allows you to provide any relative path in app bundle.
- path starts with $tmp. This will make the plugin look in the app sandbox temp directory
- path starts with $docs. This will make plugin look in the Documents directory of app sandbox.

So this in assence will allow you to download a remote db file , save it in temp or documents and create a application db from it...
This is highly experimental and I have not adopted this for Android yet. I will commit something to this repo probably today.

**Comment by andpor** [comment]
ios and pure Java Android are updated.You can try with following openDatabase changes - three flavors as I described in my previous post...

1. ({name : "test.db", createFromLocation: "1"})
2.  ({name : "test.db", createFromLocation: "~/db/myfile.sqlite"})
3.  ({name : "test.db", createFromLocation: "/downloads/myfile.sqlite"})
