### ISSUE TITLE
Instructions for the projects developed using Expo toolchain.

### ISSUE THREAD

**Issue by Sudeepa14** [andpor/react-native-sqlite-storage#313]
I could not find any installation instructions for the project developed using **EXPO** toolchain. Can this module be used with it?

**Comment by andpor** [comment]
I suppose it can be but I do not support it or provide any instructions around integration. I have seen people having issues with Expo though...

**Comment by danieloi** [comment]
The expo managed workflow won't work with this library since it contains native code.
