### ISSUE TITLE
undefined is not an object (Evaluating 'NativeModules["SQLite"][method]')

### ISSUE THREAD

**Issue by Moussawi7** [andpor/react-native-sqlite-storage#32]
Hi,
Although that i followed the steps in the documentation, but i am unable to open the database.
```javascript
var db = SQLite.openDatabase("test.db", "1.0", "Test Database", 200000, openCB, errorCB);
```
please find the screenshot:
![screenshot_2016-02-27-13-45-54](https://cloud.githubusercontent.com/assets/5157060/13372705/b56087f4-dd58-11e5-8ff7-675fc2bc8b4a.png)
Note that i am using react native ***0.20***
Thank you.

**Comment by andpor** [comment]
From very little information you provided I conclude you are trying Android. Not sure if it is native or pure Java. The RSOD indicate you React Native plugin is not properly installed in your app. Can't help you there since you did not provide any information on how you coded there.

**Comment by mcnamee** [comment]
Hi @Moussawi7 
I had the same issue when upgrading React Native - when running `react-native upgrade`, it'll remove any previously linked libraries.

I needed to follow the install process again, and it's now back to working.

**Comment by Moussawi7** [comment]
@mcnamee ,
Thanks a lot, you are absolutely right.
I re-installed react-native and followed the installation process and everything gonna fine.

**Comment by iSimar** [comment]
having this issue (using react native 23.1), tried the solution suggested by @mcnamee 
no luck

**Comment by faizan-tariq-confiz** [comment]
I am having the same issue. Its working perfectly fine in iOS but having the exact same issue on android. I have also re-install react-native and sqlite but the issue still exists. 

react-native-cli: 0.2.0
react-native: 0.25.1

**Comment by ajithamp** [comment]
i am also having same issue
![screenshot_1478522181](https://cloud.githubusercontent.com/assets/20926992/20058046/e00f9da8-a514-11e6-919b-9bd47914c8be.png)

and my code is 

class Sqlite extends Component {
  componentWillMount() {
    SQLite.openDatabase({ name: "testDB", createFromLocation: 1 }).then((success) => { alert("success") });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

**Comment by andpor** [comment]
It is due to improper installation. Please follow instructions and verification from README.
