### ISSUE TITLE
Can't load new pre-populated database after app update

### ISSUE THREAD

**Issue by kee23** [andpor/react-native-sqlite-storage#322]
I'm able to open a database correctly using:

`let db = SQLite.openDatabase({ name: database_name, createFromLocation: 1 });
`
The file is located in android>app>src>main>assets>www folder.

However when I modify the prepopulated database, and replace the database in the same folder with the same filename, it will not use the updated database after an app update. This is expected behaviour since files in the assets folder are cached and don't refresh without a reinstall or manually clearing data: https://stackoverflow.com/a/33469764/1575151 

Additionally, it isn't possible to clear assets folder at runtime: https://stackoverflow.com/a/14000813/1575151

My solution thus far has been to update the filename each time there is an app update, however this is not ideal because it is causing the app file size to continually expand since each older version of the DB is still cached on the user device. They would have to manually clear data or reinstall to fix the file size issue.

Are there any solutions for this? If it were possible to read a pre-populated db from the res>raw folder instead, that might fix the issue.

Thanks

**Comment by brystfire08** [comment]
You should delete the previous database..

```
SQLite.deleteDatabase({
  name: "db",        
  location: "default"  
}, function (res) {
  if(res == "database removed") {
    //openDatabase call here
  }
}
```

**Comment by andpor** [comment]
Yes, @brystfire08 is correct. Delete the existing database in order to have it re-created with the pre-populated db.

**Comment by PentamapRainer** [comment]
How is it possible to change a pre-populated database without new installation of the App? I tried with the following code:

`SQLite.deleteDatabase({
  name: "db",        
  location: "default"  
}, function (res) {
  if(res == "DB deleted") {
    openDatabase({ name:db, createFromLocation : 1, location: 'Library'})
  }
}`

deleteDatabase correctly deletes the database. But openDatabase does reopen the old database again and not the new one in the iOS/AppName/www folder on iOS or the android/app/src/main/assets/www folder.

How can I achieve that the new database is opened from the www folder?
