### ISSUE TITLE
I tried 8 hours and I can not connect to pre-populated database.

### ISSUE THREAD

**Issue by hakkikonu** [andpor/react-native-sqlite-storage#326]
On my react-native project (react-native version 0.58.3) 

https://stackoverflow.com/questions/54647109/react-native-sqlite-can-not-find-pre-populated-database-file

I tried everything but I can not connect to my local SQLite database.

//These are not working. I uninstalled my android app for every try and installed again. But not working!!!!!
```
var db = SQLite.openDatabase({name : "players.db", createFromLocation : "~players.db"});
var db = SQLite.openDatabase({name : "players.db", createFromLocation :1});
var db = SQLite.openDatabase({name : "players", createFromLocation : "~players.db"});
```

pre-populated players.db is located under /www folder and I tried these ways but I'm getting this error:

`OPEN database: players failed, aborting any pending transactions`

**Comment by andpor** [comment]
The [documentation](https://github.com/andpor/react-native-sqlite-storage/blob/master/README.md#step-6---adjust-opendatabase-call) should clearly state you have to have a folder called www or data in your project where the prepopulated db file exists? 
Once you have ww created and place players.db in it "~data/mydbfile.sqlite", `var db = SQLite.openDatabase({name : "players.db", createFromLocation :1});` should work fine.

`var db = SQLite.openDatabase({name : "players.db", createFromLocation : "~www/players.db"});` should also work

**Comment by hakkikonu** [comment]
www or data folders don't solve my problem. /assets folder relative to www. so I just put my db file to assets folder and it works.

thanks

**Comment by AboutReact** [comment]
Here is the working example [Example to Load Pre Populated SQLite Database in React Native](https://aboutreact.com/example-of-pre-populated-sqlite-database-in-react-native/)

**Comment by kmahmou1** [comment]
One very important note:  After you fix the problem, you have to delete the application from the simulator.
It seems react-native, will create an empty default database file and load it into the application.

When I deleted the app on the simulator, and installed again after run, it will work.

This has more details: https://github.com/andpor/react-native-sqlite-storage/blob/master/README.md#step-6---adjust-opendatabase-call

This shows exact step-by-step how to do that.

**Comment by Kos-M** [comment]
i used this to open my db 
`
...
SQLite.openDatabase({ name: 'app.db', createFromLocation: '~/app.db' }, () => {  
.......`
app.db file is located in : /<project_root>/android/app/src/main/assets/app.db

**Comment by JeffreyGaydos** [comment]
I know this is an old thread, but for anyone else in my situation, note that the database file itself MUST be all lowercase in order for this package (or maybe something internal to react native) to find it. I don't know why this is a requirement, but I hope there is a valid technical reason for it within this package or android itself. So, an existing, pre-populated `.db` file called `App.db` will never be able to be opened by this package, but the same file renamed to `app.db` will. Note that your build might complain about duplicate assets when you rename the `.db` file in-place. Just delete the db files, rebuild, then add them back lowercased and rebuild. I am running Metro v0.80.1 using a non-emulated Android device.
