### ISSUE TITLE
Module support (specifically R*Tree)

### ISSUE THREAD

**Issue by RWOverdijk** [andpor/react-native-sqlite-storage#328]
I was wondering if it's possible to use modules for SQLite such as RTree using react-native-sqlite-storage. I wasn't able to find a clear guide.

If possible, it would be nice to document it. I don't mind writing it once I know how to do it.

**Comment by RWOverdijk** [comment]
R*Tree works ootb. Silly me.

**Comment by RWOverdijk** [comment]
Silly me again, it doesn't work on android. On android it doesn't come with the RTree module.

**Comment by andpor** [comment]
If you are referring to native Android implementation I suggest you raise a PR in cordova-sqlite-storage. I am using pre-built binaries from the owner of that repo.

**Comment by RWOverdijk** [comment]
Yeah so... I solved it by changing a couple of lines in the code. It's about `android.database.sqlite`. I made my own aar, but had to change some files to do so.

Would you consider adding that to the repo? It means adding your own aar, but allows you to compile it with whatever you want.

Right now I'll fork it, and you can see what changes I made.

**Comment by RWOverdijk** [comment]
https://github.com/RWOverdijk/rn-sqlite

Currently using this in my app and it works well so far. Made some minor changes, too.

**Comment by andpor** [comment]
If you tell me what you did exactly and how it works will consider for sure... :)
