### ISSUE TITLE
open downloaded pre-populated db on ios [question]

### ISSUE THREAD

**Issue by sinodko** [andpor/react-native-sqlite-storage#333]
Am I able to download a db file to the device and open in from device storage on ios? On Android there is no problem with it. Thanks :)

**Comment by andpor** [comment]
not enough details

**Comment by sinodko** [comment]
Thanks for fast response! So.. I would like to be able to download a fb file from api server and save this file to the device (for this part I'll use react-native-fs package). When the download is completed and file is ready I would like to open new database connection from this pre-populated db file.

**Comment by andpor** [comment]
Try referring to the docs for the location of the pre-pulated database on iOS

**Comment by sinodko** [comment]
So it definitely should be possible?

**Comment by brodybits** [comment]
Yes but I don't know if anyone has tested it, or if anyone will have some
"extra" time to test it.

**Comment by sinodko** [comment]
Thank you! I will test it and if there will be some problems I will let you know. I wil close the issue :)

**Comment by andpor** [comment]
[look here at option #3...](https://github.com/andpor/react-native-sqlite-storage#step-6---adjust-opendatabase-call)
