### ISSUE TITLE
DB opens in read-only mode even though I specified that it should be writable.

### ISSUE THREAD

**Issue by andrew-koster-** [andpor/react-native-sqlite-storage#341]
When I attempt to call `SQLite.openDatabase` with these parameters:

    {
        name: 'database.sqlite3',
        createFromLocation: '~/www/database.sqlite3',
        readOnly: false,
    }

I get this error message:

    Opening db in mode READ ONLY

And then when I attempt to do an insert on that open DB, I get this error message:

    'Error handler not provided: ', { message: 'attempt to write a readonly database', code: 0 }

Why is it read-only? I'm clearly specifying that it should not be, but the library is ignoring that parameter. I also checked to make sure that the file exists in the expected location at runtime: it does.

This only happens on iOS. Works fine on Android. Having a DB library that only works on Android kind of defeats the purpose of using React-Native.

Help please?

These are my dependencies in my package.json:

    "dependencies": {
          "braces": "^2.3.2",
          "react": "16.6.3",
          "react-native": "^0.58.5",
          "react-native-gesture-handler": "^1.0.15",
          "react-native-iap": "^2.4.0-beta12",
          "react-native-sqlite-storage": "^3.3.9",
          "react-navigation": "^3.1.2"
    },

**Comment by andpor** [comment]
Because readonly is not a true/false option.  Database is writable by default, so don't provide any options in regards to readonly.
