### ISSUE TITLE
can't store json object from this.state this will insert all null value

### ISSUE THREAD

**Issue by SachinJat** [andpor/react-native-sqlite-storage#343]
constructor(props){
    super(props);
    this.state = {
      smoke_detector: {image: {uri: ''}, test: 'NO', date: ''},
      carbon_mono_detector: {image: {uri: ''}, test: 'NO', date: ''},
      fire_extinguisher: {image: {uri: ''}, test: 'NO', date: ''},
      fire_blanket: {image: {uri: ''}, test: 'NO'}
    };
  }

from this state i am using in android app
var SQLite = require('react-native-sqlite-storage');
var DB = SQLite.openDatabase({name: 'InspectitDB.db', createFromLocation : "~InspectitDB.db", location: 'Library'});
let propertyDetailId = 1;
let inspection = {
      smoke_detector: this.state.smoke_detector,
      carbon_mono_detector: this.state.carbon_mono_detector,
      fire_extinguisher: this.state.fire_extinguisher,
      fire_blanket: this.state.fire_blanket
    };
    let inspectionData = JSON.stringify(inspection);
    db.transaction((txn) => {
      txn.executeSql(`insert into details ( propertyDetailId, inspectionData) values (?, ?);`, [propertyDetailId, inspectionData]);
    });

**Comment by SachinJat** [comment]
But i am try it with static json then this was inserted. Please help me.....i am stuck here

**Comment by andpor** [comment]
Not enough information. Closing.
