### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by NainalChauhan** [andpor/react-native-sqlite-storage#346]
```
Possible Unhandled Promise Rejection (id: 0):
Object {
  "code": 0,
  "message": "no such table: Scavenger (code 1): , while compiling: SELECT * FROM TableName",
}
```

I am getting above mentioned error when using Promise. When the table does not exists in database it should return a promise rejection, but it doesn't throw any promise rejection and the above error is shown. 
If the promise rejection is handled, then please provide the sample code to handle the promise rejection.

code:-

![imageedit_1_7075279362](https://user-images.githubusercontent.com/26924554/56282851-bb946d00-612d-11e9-844f-27aebdf0b271.png)

**Comment by rollsroyc3** [comment]
@NainalChauhan Why was this closed? Did you find a solution?
