### ISSUE TITLE
no such table

### ISSUE THREAD

**Issue by zverbeta** [andpor/react-native-sqlite-storage#35]
Hello, i'm created react-native project and add your component to my project 

I have a file structure 
![struct](https://cloud.githubusercontent.com/assets/6248327/13864567/18a6918a-ecab-11e5-9bf8-bc5705167462.png)

also i found copied db file in this path `/data/data/com.zrules/databases `

But if i run code from example, i have a error 
`Error handler not provided: ', { message: 'no such table:`

Sorry if similar issue exist. 

P/S Android platform

**Comment by andpor** [comment]
Not entirely sure what the issue is but definitely related to your local setup rather than being related to the module itself.

**Comment by commcepta** [comment]
I am trying hard to install pre-populated database in Android. I did the steps to install and the tests is running perfectly. But when I tried to access the pre-populated database I had the same error "Error handler not provided: ', { message: 'no such table:"

My database is in a folder called www inside my project root and i am using this command

“ SQLite.openDatabase({name : database_name, createFromLocation : 1}).then((DB) => { ..."

**Comment by andpor** [comment]
I am sorry but I don't understand what you did exactly. What does it mean that you tried to access the pre-pulated database while the test ran perfectly? Can you provide precise steps to repro the issue ?

**Comment by zverbeta** [comment]
@commcepta Hello, i solve my problem next steps 

1. Run `react-native start` and `react-native run-android / ios `
2. Next run cmd.exe
3. Go to project folder where you are have `NAME_YOUR_DB.sqlite`
3. In terminal run `adb push NAME_YOUR_DB.sqlite` data/data/PROJECT_NAME/databases/

Maybe need rerun project

**Comment by commcepta** [comment]
@andpor,
I'll try to explain better:
I’ve followed the installation instructions and have successfully tested the example code from ‘react-native-sqlite-storage/test/‘ folder (iOS and Android).
Now I’m trying to use a pre-populated database. The instructions for iOS setup worked.
I created the www folder and the database inside.
The problem is when I run it on Android. It’s giving me the “no such table” error.

**Comment by andpor** [comment]
make sure your asset gets bundled with that apk...
where do you place your www dir ?

**Comment by commcepta** [comment]
my www dir is at the root of the react native project.
Where do I find the apk?
I don't know how to check if my assets was bundled with the apk.

**Comment by zverbeta** [comment]
Where do I put the database file in order to make it available in the compiled application

OS Android

**Comment by andpor** [comment]
It is relative to the directory that Activity.getAssets() looks at.
http://developer.android.com/reference/android/content/Context.html

**Comment by zverbeta** [comment]
Please explain.

Let's say I create a new project `react-native init AwesomeProject` further install your module `npm install --save react-native-sqlite-storage` then I write in file index.android.js

`var db = SQLite.openDatabase("test.db", "1.0", "Test Database", 200000, openCB, errorCB);`

And now the question is, where should I put test.db in project dir.

I tried put file test.db in PROJECT_ROOT, PROJECT_ROOT/www, but nothing

**Comment by andpor** [comment]
As I have hinted in my previous note, the code looks at Assets directory in your Android app. That would be src/main/assets/

**Comment by zverbeta** [comment]
I've tried to use this way, there are no results.

My version, which I copy the database adb push `NAME_YOUR_DB.sqlite data / data / PROJECT_NAME/databases/` — works

Ie now the problem nablidaetsya in realese apk, probably he did not move in the apk from above path

**Comment by zverbeta** [comment]
WOW, now it's work. Thanks
