### ISSUE TITLE
Execute SQL not work when enable promise

### ISSUE THREAD

**Issue by anhhh11** [andpor/react-native-sqlite-storage#351]
I has the following code:

```
   SQLite.enablePromise(true);
   const db = await SQLite.openDatabase({name: 'app1.db', readonly: false, createFromLocation: 'app.db'});
    await db.transaction(this.initializeDbTables);
    const rs = await db.executeSql('SELECT count(*) AS count FROM f_news')
    const count = rs.rows.item(0).count;
```

after running; I've got error `rs` undefined; using callback it work as normally.
Must I use mixed callback and promise? It seems so confused @@

**Comment by rawtxapp** [comment]
@anhhh11  Try surrounding it by 

`try{
 <YOUR_CURRENT_CODE> 
}catch(err){
console.warn(err)
}`.
Chances are there's a bug somewhere and when you print it you'll see the problem.

**Comment by anhhh11** [comment]
@rawtxapp 
Not sure but I've wrapped around Promise eventually:
```
return new Promise((resolve, reject) => {
 db.executeSql(sql, [], (rs) => {
      resolve(rs.rows.raw()[0]);
    }, reject);
  });
```
