### ISSUE TITLE
COUNT AND MAX function not work

### ISSUE THREAD

**Issue by fujingjunben** [andpor/react-native-sqlite-storage#352]
hello, I use COUNT and MAX funciton in sql, but  not working.
my table like this:
```
       tx.executeSql('CREATE TABLE IF NOT EXISTS Messages( '
            + 'id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, '
            + 'message_type VARCHAR(20), '
            + 'category VARCHAR(20), '
            + 'origin VARCHAR(1000), '
            + 'format VARCHAR(1000), '
            + 'time INTEGER UNIQUE, '
            + 'resolved VARCHAR(20), '
            + 'append VARCHAR(200), '
            + 'operator_type VARCHAR(20),'
            + 'record_id VARCHAR(256),'
            + 'date VARCHAR(100)) ; '
            , [], this.successCB, this.errorCB`
```
run the following code
```
SELECT MAX(id) FROM Messages 
\\ or
SELECT Count(*) FROM Messages
```
always return
```
{"rows":{"length":1},"rowsAffected":0}
```

## Your Environment

* React Native SQLite Storage Version used: 3.3.9
* React Native version used: 0.59.6
* Operating System and version (simulator or device): Android
* IDE used: VSCODE
* Link to your project:

**Comment by wbercx** [comment]
Yes, that query would return one row. And the first column inside of that row would be the result of `MAX(id)` or `Count(*)`.

**Comment by andpor** [comment]
For questions about how to use SQL please post on stackoverflow. This is not a please to do it.

**Comment by HarshitMadhav** [comment]
Currently I am stuck with this same issue I am getting {Count(*): 0} which is correct in my case but I am wondering how to pick this value 0? Any idea?

**Comment by bilarslan** [comment]
> Currently I am stuck with this same issue I am getting {Count(*): 0} which is correct in my case but I am wondering how to pick this value 0? Any idea?

Same for me. Did you find a solution? @HarshitMadhav

**Comment by SMEETT** [comment]
hope this helps
```
tx.executeSql(
  'SELECT count(*) FROM table_name',
  [],
  (tx, results) => {
    console.log('count', results.rows.item(0));
  },
);
```

**Comment by iphonic** [comment]
The correct answer would be

```
db.executeSql('SELECT count(*) as count FROM tablename', [],
(tx,results) => {
  let count = tx.rows.item(0).count;
},
(error) => {
 
});
```

Cheers.

**Comment by yinwei525** [comment]
const results = await db.executeSql(`SELECT id FROM ${tableName}`);
return results[0].rows.length;
