### ISSUE TITLE
TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by action456789** [andpor/react-native-sqlite-storage#353]
I am getting an error in android: `TypeError: Cannot read property 'open' of undefined`, iOS is fine. My android is based on the instructions on the readme to integrate, can tell me how to solve this problem?

## Your Environment

* React Native SQLite Storage Version used:`3.3.10`
* React Native version used:`0.57.8`
* Operating System and version (simulator or device):`simulator `
* IDE used:`android studio`

**Comment by andpor** [comment]
You did not configure things properly on Android.

**Comment by action456789** [comment]
I deleted the app on the emulator and recompile and run everything.
