### ISSUE TITLE
Not open databse pre-populte db 

### ISSUE THREAD

**Issue by divyaaelius** [andpor/react-native-sqlite-storage#354]

**Comment by divyaaelius** [comment]
Error opening pre-populated DB asset in app bundle www subdirectory: storage/emulated/0/Download/OutstandingPayable.SQLITE

**Comment by andpor** [comment]
Please use issue filign template. There is nothing in your post that can be of any use. If you do not provide the details I will close it for insufficient information.

**Comment by divyaaelius** [comment]
Hello 

   var db = openDatabase({
                name:  'OutstandingPayable,
                createFromLocation: '/storage/emulated/0/Download/OutstandingPayable.SQLITE'
              })

i have to access sqlite from my 

- 

-  device path but getting error

Error opening pre-populated DB asset in app bundle www subdirectory: storage/emulated/0/Download/OutstandingPayable.SQLITE(My sqlite file name)

if i have add manually .SQLITE file paste in assets then working proper

**Comment by andpor** [comment]
Please refer to documentation regarding location of the template database file especially createFromLocation parameter in opening database section.

**Comment by divyaaelius** [comment]
ok thanx

**Comment by mitevdev** [comment]
Please close this issue, there is nothing wrong with database file opening.
