### ISSUE TITLE
Database takes too long to load

### ISSUE THREAD

**Issue by XEmAX32** [andpor/react-native-sqlite-storage#355]
Hi, my database takes too long to load, I need some data that's in there in the first view, but when it loads and it tries to call the db it isn't opened yet.
Is it possible to open the database sooner as AsyncStorage does, maybe via native code?
Thanks in advance!

**Comment by mitevdev** [comment]
The library is working fine, if you use it with React Native you should be also using Redux (or something like that) to handle the app's state. Using redux you can update your UI once the data is available meanwhile displaying a progress indicator.

**Comment by andpor** [comment]
This is not an issue with library.
