### ISSUE TITLE
no such table: Master

### ISSUE THREAD

**Issue by aniketlokhande07** [andpor/react-native-sqlite-storage#357]
## Your Environment

* React Native SQLite Storage Version used:
* React Native version used:
* Operating System and version (simulator or device):
* IDE used:
* Link to your project:

## Debug logs

Database OPENED
RCTLog.js:47 open cb finished ok
sqlite.core.js:479 Error handler not provided:  {message: "no such table:Master", code: 5}

**Comment by andpor** [comment]
Review you installation. No enough info provided to suggest anything else.
