### ISSUE TITLE
Runnable example

### ISSUE THREAD

**Issue by mkraft** [andpor/react-native-sqlite-storage#36]
Would it be possible to include a runnable example please? Thanks for all the hard work on this project.

**Comment by andpor** [comment]
Hi. Building blocks are here:
1. Create AwesomeProject (follow React Native Getting started)
2. Follow the instruction in this repo
3. Xopy index.ios.promise.js or index.ios.callback.js from react-native-sqlite-storage test dir to home dir of Awesome Project as index.ios.js

Run Awesome Project in simulator
