### ISSUE TITLE
Is it compatible with 0.60.X?

### ISSUE THREAD

**Issue by hakkikonu** [andpor/react-native-sqlite-storage#363]
I want to use this package for my app. Is it compatible with 0.60.x versions?

**Comment by carlosroberto555** [comment]
We are fixing the migration #361 
If you can help us testing compatibility, we will thank you very much

**Comment by shaheer88** [comment]
Is the issue fixed??
I was unable to get this working on 0.60.4 version.

**Comment by BravenxX** [comment]
Not working yet?

**Comment by BravenxX** [comment]
Some way it worked for me. Versions: 
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-sqlite-storage": "^3.3.11"

Just install the package but I had to omit 4 part of the guide, in MainAplication.java: 
     "   new SQLitePluginPackage(),   // register SQLite Plugin here"
or how it is now:
    packages.add(new SQLitePluginPackage());

Just dont add it  (it'll create a duplicate)  and it'll work

**Comment by carlosroberto555** [comment]
I did forked this repo and make changes to work with react-native 0.60.x (I've tested with 0.60.4)
This repo works with autolink, you don't need to do manual setup on Android.
[https://github.com/carlosroberto555/react-native-sqlite-storage](https://github.com/carlosroberto555/react-native-sqlite-storage)

I didn't tested with iOS yet, but if anybody can test it will be very helpfull.

You can install with:
```yarn add carlosroberto555/react-native-sqlite-storage#enable_autolink```

**Comment by carlosroberto555** [comment]
I tested this repo with iOS today, and seems work fine with none issue for me.
With this configuration 0.60.x autolink works like a charm for Android and iOS.

And for previous react-native versions isn't necessary Android manual configuration (only ```react-native link react-native-sqlite-storage```)

**Comment by andpor** [comment]
4.0.0 wit RN 0.60 compatibility fix released.
