### ISSUE TITLE
Update SQLite native libs

### ISSUE THREAD

**Issue by RAMart** [andpor/react-native-sqlite-storage#368]
Hi @andpor!

Thank you so much for bringing this project that far! Your work and effort is highly appreciated! And I bow to you!

I'd like to update the embedded native libs and found the branch `new-native-sqlite-libs`. I compiled and used that branch and it does almost exactly the things I needed.

Is there anything I can do to help you merging this branch? Did you stumble over certain obstacles which I may help to get rid of?
If you provide me a rough sketch of what to do, I'd be super happy to help!

Thanks again for your work

  Ingo

**Comment by andpor** [comment]
If you can test it thoroughly and confirm all is good I will merge the branch and cut a new release together with RN 0.60 support.

**Comment by RAMart** [comment]
To show some progress:

Tested branch `new-native-sqlite-libs` on React-Native 0.59.9 using `test` sources (Callback and Promises) on Android (classic and native) and iOS. Everything works as expected.

**Next:** Add some more tests. I'll be back...

**Comment by RAMart** [comment]
Okay, I've added a FTS5 test (Callback and Promises) and re-run all tests. Again, everything works as expected.
I've also tested one of our multi-platform applications switching the native sqlite libraries back and forth. Thumbs up here as well.

I think everything is set and ready to update the native libraries in a minor release or – as you suggested – together with RN 0.60 support or even both.

**Comment by RAMart** [comment]
Just to make sure: You did not include an updated version of the native libraries in the latest release 4.0.0, didn't you?

**Comment by RAMart** [comment]
Updated native libs now supported in V4.1.0.
Thank you so much!
