### ISSUE TITLE
foreign key delete cascade not working

### ISSUE THREAD

**Issue by Symous** [andpor/react-native-sqlite-storage#369]
When we set foreign keys to tables and make it delete cascade,  it will not delete related records when the parent table rows were deleted. even if we run sql: `PRAGMA foreign_keys = ON` before.
## Expected Behavior

The rows are supposed to deleted when rows of parent table were deleted.
## Current Behavior

Not deleted
## Possible Solution

I can not confirm, if we use adb to access the android database and run `PRAGMA foreign_keys = ON`, then delete parent rows, all are working fine as expected.

## Your Environment

* React Native SQLite Storage Version used: 3.3.11
* React Native version used: 0.59.8
* Operating System and version (simulator or device): Both Android and iOS devices/Simulators
* IDE used: VSCode
* Link to your project:

## Debug logs
No related logs.

**Comment by Symous** [comment]
just found out that we need to execute `PRAGMA foreign_keys = ON` in `executeSql()` instead of `transaction()`.

**Comment by brijesh-livebird** [comment]
@Symous  how to do that ? 
i tried with db.executeSql('PRAGMA foreign_keys = ON'); but not working
