### ISSUE TITLE
integer overflow

### ISSUE THREAD

**Issue by narychen** [andpor/react-native-sqlite-storage#37]
The sqlite integer value should stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.
But on android, I tried two of my android phones
create table bbb (b integer)
insert into bbb(b) values (1458743338878)  // time millisecond
select * from bbb

It turns out  b = -1545541762
I change the type integer to int int8 bigint and it is always the same result. unless I use real.
I'm not sure the problem related to this driver. But on ios it has no problem.

**Comment by narychen** [comment]
I check my sqlite version with 'select sqlite_version()'
It's   3.7.11

**Comment by andpor** [comment]
Did you try to debug the Android module and see what comes out of the db call?

**Comment by narychen** [comment]
I'm sorry but I dont know which android method to start debug with.
Could you tell me the code related to this function so I could use android studio to see the values come out.

**Comment by narychen** [comment]
I think it could be the problem as the result comes out as a java int type. It's only 4 bytes.

**Comment by andpor** [comment]
You can start here:
public void executeSqlBatch(ReadableMap args, Callback success, Callback error)

**Comment by andpor** [comment]
Did you try both pure java and native Android implementations ?

**Comment by narychen** [comment]
Yes, both android and android-native implementation I tried have this problem

**Comment by andpor** [comment]
Android impl always fetches values for colums of INT type as long....

**Comment by andpor** [comment]
i found something...maybe it will fix the issue...i should be able to commit it soon..

**Comment by andpor** [comment]
Can you check the pure Java implementation? I adjusted some conversions...

**Comment by narychen** [comment]
I've tried it. It fixed the problem. Really Awesome!

**Comment by andpor** [comment]
Great. I also updated native impl now.

**Comment by narychen** [comment]
Just one more question, should I use native impl in production environment or both impl will be ok?

**Comment by andpor** [comment]
both fully working. Your choice.

**Comment by andpor** [comment]
Fixed in 2.1.5

**Comment by kestasb** [comment]
Problem reappeared on Android devices in v3.3.5, though v3.3.4 is working fine.

**Comment by andpor** [comment]
yes, i spotted the issue. I will fix it and release 3.3.6 tomorrow - thanks for reporting..
