### ISSUE TITLE
Document how to use FTS5 on Android

### ISSUE THREAD

**Issue by jrr** [andpor/react-native-sqlite-storage#371]
Searching through Github issues, [it looks like](https://github.com/andpor/react-native-sqlite-storage/issues/344#issuecomment-484293027)  FTS5 is unsupported on Android.

[Here](https://github.com/andpor/react-native-sqlite-storage/issues/310#issuecomment-469357373) @brodybits references a repo that can be built to produce FTS5-supporting libs.

For this issue, I'd like:
- FTS5 support out-of-the-box on Android
 _-or-_
- An explanation as to why it's not offered, and advice how to work around it.

Would you _like_ to support it, or are you specifically avoiding it for some reason? (would you accept contributions enable it?)

**Comment by jrr** [comment]
It looks like I'm getting the _device's_ sqlite, not the one bundled with this library. Is this the "pure java" mode described in the readme? How can I use the bundled sqlite instead? (in order to attempt to replace it with my own build)

**Comment by carlosroberto555** [comment]
I think we can make a gradle script to reference it
I can try make it on this weekend

**Comment by jrr** [comment]
Got it working! (FTS5 on Android) Here's what I did:
- Cloned https://github.com/brodybits/Android-sqlite-ext-native-driver and built it. (I also raised _APP_PLATFORM_ to _android-16_ and dropped _armeabi_)
- Forked this repo, replaced its binaries with our new ones, and updated package.json's _sourceDir_ to _android-native_:
https://github.com/jrr/react-native-sqlite-storage/blob/75da0e331397c0be4ea250323b4755d79f77e12f/package.json#L39-L41
- Referenced the fork in my React Native project:
```js
    "react-native-sqlite-storage": "jrr/react-native-sqlite-storage#fts5",
```

For now, anyone facing this issue can do the same!

## Future
Long-term, I think my preference would be:

1) for `react-native-sqlite-storage`'s embedded binaries have FTS5 enabled, so anyone that uses `android-native` mode gets it. 
2) If that doesn't work for some reason, then I'd aim to keep a copy of the [sqlite amalgamation](https://www.sqlite.org/amalgamation.html) in my RN project and build it as part of my project. (instead of e.g. checking-in a binary or referencing a forked project) I'm not sure what that would take.

**Comment by RAMart** [comment]
Related to #368

**Comment by andpor** [comment]
auto-linking has been working with android version only (not native-android). I have been hinting to people to be careful submitting PR considering only android and leaving native-android behind. As of now I am not sure myself how to solve this.

**Comment by andpor** [comment]
FTS5 should be working with binaries I have under this branch. new-native-sqlite-libs
If you can test these binaries and confirm they are all good I will merge them into the master and release ..

**Comment by carlosroberto555** [comment]
Workaround on v4.0.0 is change sourceDir on ```./node_modules/react-native-sqlite-storage/react-native.config.js``` for use android-native project

```javascript
module.exports = {
  dependency: {
    platforms: {
      // ... another platforms
      android: {
        // sourceDir: './platforms/android'
        sourceDir: './platforms/android-native'
      }
    }
  }
}
```

**Comment by RAMart** [comment]
> FTS5 should be working with binaries I have under this branch: new-native-sqlite-libs
If you can test these binaries and confirm they are all good I will merge them into the master and release ..

These are the ones I checked in #368

**Comment by andpor** [comment]
ok. I will include them in the next release 4.1.0

**Comment by jrr** [comment]
Those binaries are working for me, too!:

- At first I tried out using the `"andpor/react-native-sqlite-storage#new-native-sqlite-libs"` branch directly, then realized it was out of date with master.
- So then I took the libs from `new-native-sqlite-libs`, and applied them to latest master ([commit](https://github.com/andpor/react-native-sqlite-storage/commit/716cd0f1ed640dc8d29287898c87bc9012494a79).
- And then applied @carlosroberto555 's [new workaround](https://github.com/andpor/react-native-sqlite-storage/issues/371#issuecomment-523870782) to access `android-native`.

With this in place, I can see the FTS5 module is available in my app.

**Comment by andpor** [comment]
yes, the branch has old structure...pre latest PR merge...

**Comment by jrr** [comment]
I propose a slight change to @carlosroberto555 's workaround, that would enable apps to opt in to _android-native_ without having to edit any files or fork any repositories:

```js
android: {
    sourceDir: `./platforms/android${process.env.USE_ANDROID_SQLITE_NATIVE ? "-native" : ""}`
}
```

This way you could e.g. `USE_ANDROID_SQLITE_NATIVE=1 react-native run-android`, or set it persistently via your environment config, however you set env vars in your project.

I would prefer some other, better-supported way of letting the consuming app configure libraries it depends on, but haven't found much documentation in this area. (it looks like maybe RN cli's [native_modules.gradle](https://github.com/react-native-community/cli/blob/master/packages/platform-android/native_modules.gradle) is responsible for reading the config?).

In the mean time, how do you feel about shipping the environment variable approach?

**Comment by andpor** [comment]
The new native libs have been merged and release under 4.1.0

**Comment by andpor** [comment]
I will work on your suggestion for env switch next...i like the approach ..

**Comment by jrr** [comment]
I went ahead and created a PR: https://github.com/andpor/react-native-sqlite-storage/pull/377

**Comment by jrr** [comment]
I prefer #393's approach to this problem, which has you edit a file instead of setting an environment var. Anyone subscribed to the thread have thoughts on this?
