### ISSUE TITLE
react-native-sqlite-storage using deprecated "rnpm" config

### ISSUE THREAD

**Issue by m0n-hash** [andpor/react-native-sqlite-storage#372]
warn: The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-sqlite-storage: https://github.com/andpor/react-native-sqlite-storage
![sqlite](https://user-images.githubusercontent.com/4024578/62929854-5140c000-bde1-11e9-8b0c-19f1f43cab3c.PNG)

**Comment by roshanadh** [comment]
Duplicate issue? #359
