### ISSUE TITLE
Column with Auto Increment not working

### ISSUE THREAD

**Issue by shashankjayajain** [andpor/react-native-sqlite-storage#373]
I am trying to use this library for my academic project. I am trying to use auto increment attribute for a column but unable to successfully run insert command. 

Please refer to below commands:

**Table Creation :**
CREATE TABLE "Account" (
 "accountID" INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL, 
 "type" varchar(20) NOT NULL, 
 "description" varchar(100) NOT NULL
);

**Insert SQL Query:**
INSERT INTO Account ("type","description") VALUES ("LOAN","LOAN ACC");

**Result**
Object {
  "code": 0,
  "message": "NOT NULL constraint failed: Account.accountID (code 1299 SQLITE_CONSTRAINT_NOTNULL)",
}

**Expectation**
Insert query should have worked with accountID having incremented value.

**Comment by SnehalAgrawal** [comment]
Instead of AUTO_INCREMENT use AUTOINCREMENT.
See this example [Example of SQLite Database in React Native](https://aboutreact.com/example-of-sqlite-database-in-react-native/)

**Comment by carlosroberto555** [comment]
@SnehalAgrawal good answer
More details about primary key with AUTOINCREMENT you can [see here](https://www.tutorialspoint.com/sqlite/sqlite_using_autoincrement.htm)

**Comment by shashankjayajain** [comment]
> Instead of AUTO_INCREMENT use AUTOINCREMENT.
> See this example [Example of SQLite Database in React Native](https://aboutreact.com/example-of-sqlite-database-in-react-native/)

**Gives me following error**

Object {
  "code": 0,
  "message": "near \"AUTOINCREMENT\": syntax error (code 1 SQLITE_ERROR): , while compiling: CREATE TABLE Account (accountID INTEGER PRIMARY KEY NOT AUTOINCREMENT, \"type\" varchar(20) NOT NULL, \"description\" varchar(100) NOT NULL);",
}

**Comment by andpor** [comment]
Closing as this is not an issue.
