### ISSUE TITLE
Android Pie release mode cannot open database or do any database operation

### ISSUE THREAD

**Issue by shikhars371** [andpor/react-native-sqlite-storage#378]
Cannot Read/write Database in android PIE release apk, on debug its working fine.

## Expected Behavior

On Anroid Oreo and below its version , sqlite storage is working fine, also when i run app in debug mode in pie then too its working fine, but when i make signed apk, and run on phone oreo and below its working fine but on android pie, its not reading from database what can be the issue?

**Comment by rafael096** [comment]
I have the same issue with android Pie any solution?

**Comment by shikhars371** [comment]
I found a solution, its working on pie, i was confused with https and http, pie does'nt support http in release mode so i changed it and database worked as expected :)
