### ISSUE TITLE
react-native-sqlite-storage installation issue in android

### ISSUE THREAD

**Issue by svsShiva** [andpor/react-native-sqlite-storage#384]
## Current Behavior
Running application in android (react-native run-android) gives following error

**> Could not resolve project :react-native-sqlite-storage.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-sqlite-storage:
          - None of the consumable configurations have attributes.**

## Possible Solution
change following path in settings.gradle
 from 
**project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android')**

to
**project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/platforms/android')**

## Steps to Reproduce (for bugs)
Installation in android as per docs

## Your Environment

* React Native SQLite Storage Version used: "^4.1.0"
* React Native version used: "0.60.5"
* Operating System and version (simulator or device): "android 9.0 "
* IDE used: "Visual studio code"

**Comment by gajjartejas** [comment]
Same here. Hope it will fix soon :)

**Comment by deborahhellen** [comment]
+1 also have the same issue with same environment setup.

**Comment by GRISHENK0** [comment]
+1 I have the same issue.

**Comment by sanjay-salunkhe** [comment]
+1 i have the same issue as well

**Comment by knspatel** [comment]
+1 i have the same issue as well.

    React Native SQLite Storage Version used: "^4.1.0"
    React Native version used: "0.59.8"
    Operating System and version (simulator or device): "android 9.0 "
    IDE used: "Visual studio code"

**Comment by Symous** [comment]
the solution provided by @svsShiva works for me:

change following path in settings.gradle
from
`
project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android')
`

to
`
project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/platforms/android')
`

**Comment by GRISHENK0** [comment]
> the solution provided by @svsShiva works for me:
> 
> change following path in settings.gradle
> from
> `project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android')`
> 
> to
> `project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/platforms/android')`
> 
> Thanks. :)

I've finally triés this ans or works for me !

**Comment by RobTheFiveNine** [comment]
+1 for changing the path as suggested by @svsShiva. Thanks :heart:

**Comment by SnehalAgrawal** [comment]
you can see the examples shared below. These are very easy and simple posts for the CRUD operations:

1. [Example of SQLite Database in React Native](https://aboutreact.com/example-of-sqlite-database-in-react-native/)
2. [Example to Load Pre Populated SQLite Database in React Native](https://aboutreact.com/example-of-pre-populated-sqlite-database-in-react-native/)
3. [How to See SQLite Database Data Saved in Device using Android Studio](https://aboutreact.com/see-saved-data-of-the-sqlite-database-in-device/)
