### ISSUE TITLE
RN 0.61.1: AndroidRuntime: java.lang.NoSuchMethodError: No interface method pushMap

### ISSUE THREAD

**Issue by jrr** [andpor/react-native-sqlite-storage#387]
After upgrading to RN 0.61.1, I'm getting this at runtime from Android:

```
I/ReactNativeJS: creating new connection
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.myapp, PID: 6821
    java.lang.NoSuchMethodError: No interface method pushMap(Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableArray; or its super classes (declaration of 'com.facebook.react.bridge.WritableArray' appears in /data/app/com.myapp-esZnhIVV3rrQc3ZkQympzg==/base.apk)
        at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlStatementNDK(SQLitePlugin.java:726)
        at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlBatch(SQLitePlugin.java:610)
        at io.liteglue.SQLitePlugin$DBRunner.run(SQLitePlugin.java:793)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Here's the code in question:

https://github.com/andpor/react-native-sqlite-storage/blob/716cd0f1ed640dc8d29287898c87bc9012494a79/platforms/android-native/src/main/java/io/liteglue/SQLitePlugin.java#L726

It looks like the behavior of`com.facebook.react.bridge` may have changed?

**Comment by jlemm45** [comment]
Same error 😢

**Comment by Serdans** [comment]
Possibly related: https://github.com/facebook/react-native/commit/1a2937151b8d36e8741ef9d4fbe7d2ebf65cb775#diff-5245d1955ab3db308d8457ee644d939c

Currently a `WritableMap` is being passed as parameter for `pushMap` but `pushMap` now accepts a `ReadableMap` instead of `WritableMap`.

**Comment by clytras** [comment]
Is there a workaround for this?

**Comment by jrr** [comment]
@jlemm45 @Serdans @clytras I have a candidate fix for this. Can you try it?

**Comment by clytras** [comment]
@jrr It's working! I've tested `openDatabase`, `db.transaction`, `tx.executeSql` and queries `CREATE TABLE`, `INSERT INTO`, `SELECT`. Everything seems to be working fine.

```
"react-native": "0.61.5"
...
"react-native-sqlite-storage": "andpor/react-native-sqlite-storage#404/head",
```

Here is my RN 0.61 test project: https://github.com/clytras/RNSQLiteStorage

**Comment by jrr** [comment]
@clytras thanks for testing it!

One more thing, can you check if you're still getting the `android-native` SQLite libraries? On my project it seems like the new React Native isn't respecting the `react-native.config.js` configuration any more.

E.g., can you `CREATE VIRTUAL TABLE email USING fts5(sender, title, body);` ?

Mine is now saying `Error: no such module: fts5`, which means it's using Android's SQLite 😒.

**Comment by jrr** [comment]
I tried your example project, and it's doing the same thing:

`java.sql.SQLException: sqlite3_step failure: no such module: fts5`

**Comment by clytras** [comment]
Thats strange because if you check inside `android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java`, you'll see:

```
// react-native-sqlite-storage
import io.liteglue.SQLitePluginPackage;

...

  public ArrayList<ReactPackage> getPackages() {
    return new ArrayList<>(Arrays.<ReactPackage>asList(
      new MainReactPackage(mConfig),
      new SQLitePluginPackage()
    ));
  }
```

so, RN does respect `react-native.config.js`; there is something else that prevents the usage of the bundled version.

**Comment by clytras** [comment]
After invastigating this, I found that after a gradle clean, I got a message:

```
> Configure project :react-native-sqlite-storage
WARNING: The following project options are deprecated and have been removed:
android.useDeprecatedNdk
NdkCompile is no longer supported
```

I then removed `android.useDeprecatedNdk=true` inside `react-native-sqlite-storage/platforms/android-native/gradle.properties` and the message went away, but I get the same error. I noticed on logcat a `not allowing consideration` message:

```
2423-2423/com.rnsqlitestorage D/ApkSoSource: not allowing consideration of lib/x86/libsqlc-native-driver.so: deferring to libdir
```

The emulator is an `x86` emulator.

Also something else I get while compiling the APK is about unabler to strip library, but I don't think this is related to the problem:

```
> Task :react-native-sqlite-storage:transformNativeLibsWithStripDebugSymbolForDebug
Unable to strip library '\RNSQLiteStorage\node_modules\react-native-sqlite-storage\platforms\android-native\build\intermediates\transforms\mergeJniLibs\debug\0\lib\armeabi\libsqlc-native-driver.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.
```

**Comment by jrr** [comment]
I was briefly hopeful, but I think that message is innocuous. I'm seeing it from my existing project, on the old version of RN:

> 2020-01-16 10:56:27.763 2514-2514/? D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libsqlc-native-driver.so: deferring to libdir

(the app then proceeds to use FTS5, so it must be loading the correct library)

It looks like the message comes from Facebook's [SoLoader](https://github.com/facebook/SoLoader/blob/3224384c15713f47952633fb009afc9186fae119/java/com/facebook/soloader/ApkSoSource.java#L106), should you want to dig further.

I guess the next thing to debug is how the app finds and loads native libraries at runtime.

**Comment by clytras** [comment]
I'm not sure about the logcat message, but [`SoLoader`](https://github.com/facebook/SoLoader) is how the app finds and loads native libraries at runtime.

> [facebook/SoLoader](https://github.com/facebook/SoLoader)
> Native code loader for Android

There seems to be an incompatibility of `.so` files bundled with RN 0.61, but again that is anly an assumption.

**Comment by clytras** [comment]
Btw, I get the same error when using `"react-native-sqlite-storage": "andpor/react-native-sqlite-storage#404/head"` with RN 0.60.0:

```
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-native-sqlite-storage": "andpor/react-native-sqlite-storage#404/head"
  },
```

```
sqlite3_step failure: no such module: fts5
```

**Comment by jrr** [comment]
Is this in your example project with config trying to use android-native?

https://github.com/clytras/RNSQLiteStorage/blob/fd77d939ae5bb5d57be74cd1dc0536fc871bcb58/react-native.config.js#L3-L11

**Comment by clytras** [comment]
Yes but it's a new project created with `npx react-native init RN060SQLiteStorage --version 0.60.0`.

The `react-native.config.js` is exactly as in [How to use (Android)](https://github.com/andpor/react-native-sqlite-storage#how-to-use-android) section at installation instractions.

I can upload the RN 0.60 project if you want.

**Comment by clytras** [comment]
I am starting to figure out why changing `implementation 'com.facebook.react:react-native:0.14.+'` to `implementation 'com.facebook.react:react-native:+'` works. It's because when not specifing the RN version, RN (_SoLoader maybe_) fails to use the bundled `.so` version which uses `*Array` and `*Map` conversions.

Within the RN 0.61 project, if I remove `react-native.config.js` and use `"react-native-sqlite-storage": "4.1.0"`, then everything compiles and runs because it uses the Android SQLite version. The problem here is that your PR does not use the bundled version, and if we manage to do so, we'll get back to the original issue, which of course is about `java.lang.NoSuchMethodError: No interface method pushMap(Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableArray; or its super classes`.

**Comment by andpor** [comment]
Guys - I am away and can't participate in this thread.. I will be back week of 27th and potentially cut a new release with changes...

**Comment by clytras** [comment]
@jrr you also have to add the google maven repositories.

Can you please test https://github.com/andpor/react-native-sqlite-storage/pull/405. I have updated the test [RN 0.61 project](https://github.com/clytras/RNSQLiteStorage) to use that PR and test `fts5` like you did. It works for me. No errors and successfully creates a virtual table using FTS5.

**Comment by jrr** [comment]
It works!

To be clear for anyone that landed here from google: referencing `"react-native-sqlite-storage": "andpor/react-native-sqlite-storage#405/head",` in my package.json, I'm able to use RN 0.61.5 and the [bundled sqlite libs](https://github.com/andpor/react-native-sqlite-storage#how-to-use-android) (with FTS5).

 Thanks for figuring this out, @clytras !

**Comment by clytras** [comment]
Well we did it together @jrr. You made the start I finished it! I thank you too!

**Comment by yhrun** [comment]
fixed `android-native/build.gradle` react-native version: 0.61.1
`dependencies {
    implementation 'com.facebook.react:react-native:0.61.5'
    implementation files('libs/sqlite-connector.jar')
}
`
