### ISSUE TITLE
How to install on RN 0.60> && docs?

### ISSUE THREAD

**Issue by ezranbayantemur** [andpor/react-native-sqlite-storage#389]
As we all know React Native autolink feature handles the linking operations. But should we still have to do install sequence, that on the readme? (If we have to please update the readme)
I tried to manually link but it gives multiple errors..

And is there any documentation for fully operation .etc?

**EDIT:** Autolink feature is enough, but readme isn't tell about it. If we can update readme it will be more helpful for avoiding mind confusing

**Comment by FlorianGG** [comment]
Do you have execute each step for the installation? Even the step 4 ?

**Comment by ezranbayantemur** [comment]
> Do you have execute each step for the installation? Even the step 4 ?

I had a problem while setup, on Windows and MacOS but right know I solved them.

But really, Installation guide on readme have MUST update. They still remain for below 0.49.3 version of React Native (index.android.js, index.ios.js ...)
And maybe there could be solutions for most common errors (like "no such table", "Cannot read property 'open' of undefined" or etc..)
This library using for 1.5k people..

**Comment by gvanderclay** [comment]
My recent pull request #393 should address most of your concerns. Please let me know if you have any feedback!

**Comment by tberghuis** [comment]
@gvanderclay I am trying to get a fresh project running on 0.61 by following your instructions but am having problems with the app crashing when I run executeSql. Do you have a working example repo I could copy and learn from?

**Comment by SnehalAgrawal** [comment]
@ezranbayantemur Have you did it? else you can see the examples shared below. These are very easy and simple posts for the CRUD operations:
1. [Example of SQLite Database in React Native](https://aboutreact.com/example-of-sqlite-database-in-react-native/)
2. [Example to Load Pre Populated SQLite Database in React Native](https://aboutreact.com/example-of-pre-populated-sqlite-database-in-react-native/)
3. [How to See SQLite Database Data Saved in Device using Android Studio](https://aboutreact.com/see-saved-data-of-the-sqlite-database-in-device/)
