### ISSUE TITLE
NativeModule Sqlite tried to override SQlite plugin check the getPackage() method in mainApplication.java

### ISSUE THREAD

**Issue by faridkamaljewel** [andpor/react-native-sqlite-storage#391]
## MainApplication.java
MainApplication.js file
    import org.pgsqlite.SQLitePluginPackage;
    @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
           packages.add(new SQLitePluginPackage());
           return packages;
        } 

## Package.json
  "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-elements": "^1.2.0",
    "react-native-firebase": "^5.5.6",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-magic-move": "^0.6.6",
    "react-native-modal": "^11.4.0",
    "react-native-numeric-input": "^1.8.3",
    "react-native-router-flux": "^4.0.6",
    "react-native-shadow": "^1.2.2",
    "react-native-sqlite-storage": "^4.1.0",
## Your Environment

* React Native SQLite Storage Version used:
* React Native version used:
* Operating System and version (simulator or device):
* IDE used:
* Link to your project:

**Comment by alipm** [comment]
cd android 
./gradlew clean
cd.. - again back

this worked for me.
