### ISSUE TITLE
How can I connect to database only once?

### ISSUE THREAD

**Issue by DiegoBittencourtOfficial** [andpor/react-native-sqlite-storage#398]
Every time that one component needs to use the database I use this code on my Constructor to create a connection::

```
SQLite.openDatabase({ name: "DBNAME.db", createFromLocation: "~/DBNAME.db" }).then((DB) => {
            if (db) {
                db = DB
                return db
            }
            else
                return null

        }).catch((error) => {

            console.log(error);
        })
```

What I want is refactor the code, so I need to put this code only in one place and if I need it, I'll import to my component. How can I do this? I was thinking about create a 'connection.js' and inside of it create a 'function' that do the job, but it always returns undefined.

This is the code:

```
import {
    Platform,
} from 'react-native'

import SQLite from 'react-native-sqlite-storage'

SQLite.DEBUG(true)
SQLite.enablePromise(true)

const banco = () => {

    return (Platform.OS == `ios` ?
        SQLite.openDatabase({ name: "DBNAME.db", createFromLocation: 1 }).then((DB) => {

            if (db) {
                db = DB
                return db
            }
            else
                return null

        }).catch((error) => {
            console.log(error);
            return null
        })
        :
        SQLite.openDatabase({ name: "DBNAME.db", createFromLocation: "~/DBNAME.db" }).then((DB) => {

            if (db) {
                db = DB
                return db
            }
            else
                return null

        }).catch((error) => {

            console.log(error);
        })
    )
}

export default banco
```

And then in my component I do: `import { banco } from './connection` and then `let db = banco` the problem is that `banco` is returning me undefined.

**Comment by AboutReact** [comment]
Ideally, it should work I have done something like this in Firebase connection. Can you please try it without braces? (I know it's silly but sometimes its works :p )
import banco  from './connection;

What I am thinking is maybe it is taking time as it has a callback and you are taking the value and checking it just after using it. You should use async-await or call it as a callback.

-Snehal Agrawal
[Find my example of SQLite Database in React Native](https://aboutreact.com/example-of-sqlite-database-in-react-native/)

**Comment by DiegoBittencourtOfficial** [comment]
`Await` did the trick, thanks man!

**Comment by meowmon** [comment]
> `Await` did the trick, thanks man!

sir! can u tell me how u use component pls? its only throw 'noti_db.transaction is not a function' when i try to call `noti_db.transaction(function(query){})` from the component.
