### ISSUE TITLE
create table  same column

### ISSUE THREAD

**Issue by shanxj** [andpor/react-native-sqlite-storage#400]
this is my sql
export const CREATE_TABLE_POWERPOINT =
  'CREATE TABLE IF NOT EXISTS POWERPOINT(' +

  'id INTEGER PRIMARY KEY' +
  ')'

when I create table  it will show. same column

sqlite db
POWERPOINT 
id     id

**Comment by SnehalAgrawal** [comment]
Try to make the PRIMARY KEY AUTOINCREMENT, 
like
CREATE TABLE IF NOT EXISTS table_user(user_id INTEGER PRIMARY KEY AUTOINCREMENT, user_name VARCHAR(20), user_contact INT(10), user_address VARCHAR(255))

If you have any doubt and you are new have a look at the [Example of SQLite Database in React Native
](https://aboutreact.com/example-of-sqlite-database-in-react-native/)
If you are still facing the issue then you can see the database in the device using Android Studio. You can follow [How to See SQLite Database Data Saved in Device using Android Studio](https://aboutreact.com/see-saved-data-of-the-sqlite-database-in-device/)
