### ISSUE TITLE
make installable / linkable by `rnpm`

### ISSUE THREAD

**Issue by zachguo** [andpor/react-native-sqlite-storage#41]
https://github.com/rnpm/rnpm

**Comment by itinance** [comment]
+1 @zachguo

**Comment by andpor** [comment]
Not sure I will have time to work on this but you are more than welcome to make a contribution :)

**Comment by yanghuxiao** [comment]
+1

**Comment by andpor** [comment]
rnpm linking for iOS added courtesy of @clozr . Thanks.

**Comment by itinance** [comment]
+1 @clozr Thx a lot!
