### ISSUE TITLE
Importing a pre-populated database (Android)

### ISSUE THREAD

**Issue by sfreeman28** [andpor/react-native-sqlite-storage#412]
## Expected Behavior
After following instructions on ReadMe to import a pre-populated database from files directory on device (after downloading from remote url) it should open the database.

## Current Behavior
The database on files directory fails to open.

## Steps to Reproduce
Only tested on Android so far, have not setup for iOS.
Use RNFetchBlob to download db file from remote server and store to CacheDir.
This code results in error:
```
const pathToDB = '/data/user/0/com.mytoursapp.android.app2047/cache/www/map.mbtiles'
this._db = SQLite.openDatabase(
	{ name: "map.mbtiles", location: "default", readOnly: true, createFromLocation: pathToDB },
	() => { console.log('database created') },
	(e: SQLError) => { console.log('error when creating db', e) }
);
```

## Possible Solution
Tested with db files included in app assets under folder structure main/assets/www/map.mbtiles works correctly. Just change the pathToDB and rest of code is the same.
```
const pathToDB = 1
```
However I cannot use this solution as I need the ability to download new database from remote server and store on device internal storage, without making a new apk with the database in assets.

## Your Environment
```
Android Pixel 3a device
"react-native-sqlite-storage": "^4.1.0"
"react-native": "0.59.10"
Visual Studio Code - v1.42.1
macOS - v10.14.5
```

## Debug logs
```
2020-02-21 10:19:06.469 E/unknown:SQLitePlugin: Error opening pre-populated DB asset in app bundle www subdirectory: data/user/0/com.mytoursapp.android.app2047/cache/www/map.mbtiles
2020-02-21 10:19:06.470 E/unknown:SQLitePlugin: Unable to import pre-populated db asset
2020-02-21 10:19:06.470 E/unknown:SQLitePlugin: Unexpected error opening database, stopping db thread
    java.lang.Exception: Unable to import pre-populated db asset
        at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:395)
        at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:49)
        at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:904)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by sfreeman28** [comment]
Solved!

The Android native code was looking in the wrong place for my database.
I was passing in the full path for createFromLocation, and then the native code was adding the Files Directory to the front of it.

File: [SQLitePlugin.java](https://github.com/andpor/react-native-sqlite-storage/blob/master/platforms/android/src/main/java/org/pgsqlite/SQLitePlugin.java)

Logs:
```
SQLitePlugin: filesDir: /data/user/0/{packageName}/files
SQLitePlugin: assetFilePath: data/user/0/{packageName}/cache/maps/8321.db
SQLitePlugin: assetFile: /data/user/0/{packageName}/files/data/user/0/{packageName}/cache/maps/8321.db
```

As you can see it prepended the FilesDir to start of my location, which causes this issue when you store in another folder on the device storage like I am.

---
Solution:

I edited SQLitePlugin to instead just use my path location as is, without prepending the FilesDir.
`File assetFile = new File(assetFilePath);`

patch file:
```
--- SQLitePlugin.java	2020-02-20 15:43:13.000000000 +1300
+++ SQLitePlugin_new.java	2020-02-25 10:54:38.000000000 +1300
@@ -368,10 +368,8 @@
                         FLog.e(TAG, "pre-populated DB asset NOT FOUND in app bundle www subdirectory: " + assetFilePath);
                     }
                 } else {
-                    File filesDir = this.getContext().getFilesDir();
-                    assetFilePath = assetFilePath.startsWith("/") ? assetFilePath.substring(1) : assetFilePath;
                     try {
-                        File assetFile = new File(filesDir, assetFilePath);
+                        File assetFile = new File(assetFilePath);
                         in = new FileInputStream(assetFile);
                         FLog.v(TAG, "Pre-populated DB asset FOUND in Files subdirectory: " + assetFile.getCanonicalPath());
                         if (openFlags == SQLiteDatabase.OPEN_READONLY) {
@@ -380,7 +378,7 @@
                         }
                     } catch (Exception ex){
                         assetImportError = true;
-                        FLog.e(TAG, "Error opening pre-populated DB asset in app bundle www subdirectory: " + assetFilePath);
+                        FLog.e(TAG, "Error opening pre-populated DB asset in Files subdirectory: " + assetFilePath);
                     }
                 }
             }
```
_Note I also changed the error log as it was very misleading saying it couldn't open asset from app bundle, when it actually is looking in local storage._

I can make a merge request if you think this would be a good change as it allows the user to store db file anywhere on device storage, not just in the FilesDir.

**Comment by sfreeman28** [comment]
Turns out had the same issue on iOS once I tested it out on an iPhone.

The native iOS code appends the NSDocumentDirectory path to the start of the assetFilePath that you pass through. This is not good when you save your db file to the cache folder or some other internal directory.

Here is the second patch file I made to fix this and allow the user to pass through the exact path to your db file.
```
--- SQLite.m	2020-02-25 12:05:04.000000000 +1300
+++ SQLite_new.m	2020-02-25 12:05:16.000000000 +1300
@@ -178,9 +178,6 @@
               assetFilePath = [targetBundleDirPath stringByAppendingPathComponent: assetFilePath];
               RCTLog(@"Built path to pre-populated DB asset from app bundle subdirectory: %@",assetFilePath);
             } else {
-              NSURL * documentsDirUrl = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory
-                                                                        inDomains:NSUserDomainMask] lastObject];
-              assetFilePath = [documentsDirUrl.path stringByAppendingPathComponent:assetFilePath];
               RCTLog(@"Built path to pre-populated DB asset from app sandbox documents directory: %@",assetFilePath);
             }
           } @catch(NSException *ex){

```

Will close this issue now.

**Comment by ErHarinderSingh** [comment]
I created I demo video for this. I was working in a project & faced that issue too. After solve the issue, I have created a video on my channel to show how we can achieve it on both iOS & Android. Check out this video: https://youtu.be/x8-b4WpYBsQ
