### ISSUE TITLE
android.useDeprecatedNdk. Ndkcompiler is no longer supported

### ISSUE THREAD

**Issue by TheRakeshPurohit** [andpor/react-native-sqlite-storage#413]
getting this error while running `npx react-native run-android` on my windows

## Current Behavior
> Configure project :react-native-sqlite-storage
WARNING: The following project options are deprecated and have been removed:
android.useDeprecatedNdk
NdkCompile is no longer supported

## Possible Solution
- add supported or alternative way

## Steps to Reproduce (for bugs)
create react-native.config.js file in root of project directory.
paste the code mentioned in ReadMe of this repo for android for react-native >0.60
run project on android in windows

## Context
takes too much time and not installing the app on my android phone

## Your Environment
* React Native SQLite Storage Version used: 4.1.0
* React Native version used: 0.61.5
* Operating System and version (simulator or device): Windows 10, Android 9 Pie(virtual)
* IDE used: VS Code

## Debug logs
> Configure project :react-native-sqlite-storage
WARNING: The following project options are deprecated and have been removed:
android.useDeprecatedNdk
NdkCompile is no longer supported

**Comment by phongit1995** [comment]
same issue
