### ISSUE TITLE
Bug with JSON1 extension

### ISSUE THREAD

**Issue by spektron-x** [andpor/react-native-sqlite-storage#418]
Hello, good night! 
I need to report a bug, I'm trying to use the JSON1 extension 'JSON_OBJECT' and it's not working (keeps saying that the function was not found) ... I tested with the git repository and the same problem occurred, thank you for your attention

`error:  {"code": 0, "message": "no such function: JSON_OBJECT (code 1 SQLITE_ERROR): , while compiling: SELECT JSON_OBJECT('name', e.name, 'office_id', e.office, 'department_id', e.department) AS data FROM Employees e"}`

**Comment by andpor** [comment]
Can you stick to instructions on how to submit the bug? I will close this an not an issue unless you file a proper bug report.

**Comment by spektron-x** [comment]
> Hello, good night!
> I need to report a bug, I'm trying to use the JSON1 extension 'JSON_OBJECT' and it's not working (keeps saying that the function was not found) ... I tested with the git repository and the same problem occurred, thank you for your attention
> 
> `error: {"code": 0, "message": "no such function: JSON_OBJECT (code 1 SQLITE_ERROR): , while compiling: SELECT JSON_OBJECT('name', e.name, 'office_id', e.office, 'department_id', e.department) AS data FROM Employees e"}`
