### ISSUE TITLE
Cannot load pre-populated DB on iOS

### ISSUE THREAD

**Issue by fleissigal** [andpor/react-native-sqlite-storage#419]
Hello everyone,

I am trying to load a pre-populated DB from a db file on iOS. No matter what I tried (including changing the names, locations etc. of the file), it would not read it properly.

Any help would be appreciated. Thank you.

## Expected Behavior
I am expecting to be able to read the db file I am providing

## Current Behavior
Currently I cannot read from a file. However in many of the cases it does say "database opened" and then it lets me interact with a different database that is stored somewhere. In the code example below, when I add a table to it and elements programmatically, it does let me query them successfully, but I can't refer to the file and I don't know where it is being saved.

## Steps to Reproduce (for bugs)

Here is the code I am using:

```
var db = SQLite.openDatabase({name : "local.db", createFromLocation : 1}, okCallback,errorCallback);

db.transaction((tx) => {
  tx.executeSql('SELECT * FROM Games;', [], (tx, results) => {
      console.log("Query completed");

      // Get rows with Web SQL Database spec compliance.

      var len = results.rows.length;
      for (let i = 0; i < len; i++) {
        let row = results.rows.item(i);
        console.log(`name: ${row.name}, id: ${row.id}`);
      }

    });
});
```

## Your Environment
* React Native SQLite Storage Version used: 5.0.0
* React Native version used: over 0.60
* Operating System and version (simulator or device): iOS 13, iPhone 11
* IDE used: VSCode

**Comment by mitevdev** [comment]
You have to copy the database file from bundle into app's documents folder. What I am doing is
1. check if the file already exists and remove it
2. copy from bundle into documents folders 
3. use it ...

```
const updatesFilePath = RNFS.DocumentDirectoryPath + '/updates.db';

const isUpdateDbExisting = await RNFS.exists(updatesFilePath);
if (isUpdateDbExisting) {
       console.log('Removing existing updates database.');
       await RNFS.unlink(updatesFilePath);
}

const bundleUpdateDbPath = RNFS.MainBundlePath + '/updates.db';
await RNFS.copyFile(bundleUpdateDbPath, updatesFilePath);

console.log('Updates database has been copied into documents folder');

const dbFilePath = RNFS.DocumentDirectoryPath + '/data.db';
const isDatabaseExisting = await RNFS.exists(dbFilePath);
```

**Comment by ErHarinderSingh** [comment]
I created I demo video for this. I was working in a project & faced that issue too. After solve the issue, I have created a video on my channel to show how we can achieve it on both iOS & Android. Check out this video: https://youtu.be/x8-b4WpYBsQ

**Comment by nikhilkumar6** [comment]
@ErHarinderSingh When I add the www folder via xcode I get the ? beside it. What does this mean? I think this is the reason why it's still unable to access the db file

**Comment by ErHarinderSingh** [comment]
> @ErHarinderSingh When I add the www folder via xcode I get the '?' beside it. What does this mean? I think this is the reason why it's still unable to access the db file

hey bro, follow the video step by step. I told everything in video. You will not get any error.
Let me know how are you doing it?
- You must assure that you have latest version of react-native-sqlite-storage
-  cd ios; pod install; cd ..

After that let me know if you have any issue with app. Thanks

**Comment by nikhilkumar6** [comment]
I've all the latest packages. And I followed the exact steps but still not working

**Comment by nikhilkumar6** [comment]
So, when I run 'SELECT * FROM sqlite_master' it returns empty array even though there are tables.

**Comment by ErHarinderSingh** [comment]
Open db in dbbrowser. https://sqlitebrowser.org/
Try to run command there. may be something wrong with query. 
Also please try to remove * and then check it.

**Comment by nikhilkumar6** [comment]
Okay, this is what I did. I created a test table in the same db and then opened the db file in www folder through sqlite browser. The new table doesn't show up here. But the db query says that the table test already exits

**Comment by ErHarinderSingh** [comment]
Show me code.

**Comment by fleissigal** [comment]
What solved my issue was on the iOS simulator to go to:
`Device > Erase All Content and Settings` and click on `Erase` (Backup as needed)
Then the DB was recognizing my table and data.

We think that the library opens the pre-populated DB file as a different local file and therefore changes on the data will not be reflected on the original DB file, however they will be saved throughout the lifecycles of the app on the local file so users can access them (probably until the app's data gets deleted from the phone).

**Comment by nikhilkumar6** [comment]
> What solved my issue was on the iOS simulator to go to:
> `Device > Erase All Content and Settings` and click on `Erase` (Backup as needed).
> Then the DB was recognizing my table and data.
> 
> We think that the library opens the pre-populated DB file as a different local file and therefore changes on the data will not be reflected on the original DB file, however they will be saved throughout the lifecycles of the app on the local file so users can access them (probably until the app's data gets deleted from the phone).

Thank you. It was precisely the issue.

**Comment by andpor** [comment]
Indeed, the pre-populated database is only read once on initial launch. It is then copied over to the application sandbox and remain there until the app is deleted.
