### ISSUE TITLE
is there any full example about react native sqlite storage?

### ISSUE THREAD

**Issue by yanghuxiao** [andpor/react-native-sqlite-storage#42]
I want to know how to add databases file into android project.
but there is't any example for me to learn.

**Comment by andpor** [comment]
You can review Setting up your project to import a pre-populated SQLite database from application for iOS - if you want to add pre-populated db file. If you are creating db from scratch there is nothing extra you need ot do besides project setup ...example JS code is in the repo.

**Comment by yanghuxiao** [comment]
In IOS I do like this:
In XCode I import sqlite database file into my project,the file path like '/www/testdb.sqlite'.
and the javascript code like`
var db = SQLite.openDatabase({
            name: "main",
            createFromLocation: "~www/testdb.sqlite"
        }, this.openCB, this.errorCB);`
It's all right.

but I copy the file testdb.sqlite to the android project path like '/MyProject/android/app/src/main/assets/www/testdb.sqlite'.
I use the same javascript code.but it show error like '"no such table: XXXX (code 1)'.
and I remove the '/MyProject/android/app/build',and restart my project,It also can't works fine.

**Comment by yanghuxiao** [comment]
I have know why I can't do now.
In android system,the plugin will create an empty database file.
I use 'adb shell',to remove the file '/data/data/com.loadapp/databases/main',and rebuild the apk.
then it's OK!
thanks your plugin.I wish it to be better!...
