### ISSUE TITLE
App crashed while retrieving image from database.

### ISSUE THREAD

**Issue by Ahmed-ab96** [andpor/react-native-sqlite-storage#425]
I want to retrieve Images from my Sqlite database, but while select Image column the app will be crash without getting any error, All images below < 1 MB, but without selecting Images column its fine... Did I something wrong ? thanks for help.

![database](https://user-images.githubusercontent.com/31816755/81909719-a9f0f380-95d3-11ea-8703-0ced3d33f107.png)

```
const callData = ()=>{
        db.transaction(tx=>{
            tx.executeSql('select ID, Names, Images from Subjects', [], (tx, results) => {
                console.log("Query completed")
                let data = results.rows.raw() 
                // console.log(data)
                dispatch({type:CALLD_ATA,data})

                },(err=>console.log(err,'from calling data')))
            })
        }
```

**Comment by andpor** [comment]
Things you are doing wrong may include that you are not following the bug submission template. There is nothing that can be done using information you provided.

Second, there is a native log that the app writes - you need to check that.
