### ISSUE TITLE
I can't add id with autoincrement 

### ISSUE THREAD

**Issue by hinciler** [andpor/react-native-sqlite-storage#426]
I want to create table with 
`"id INTEGER PRIMARY KEY AUTOINCREMENT" `
but when I add new row for this table, error comes up and it says:
> table product_groups has 9 columns but 8 values were supplied

## Expected Behavior
```
tx.executeSql(
   'CREATE TABLE IF NOT EXISTS product_groups (
         id INTEGER PRIMARY KEY AUTOINCREMENT, 
         group_id TEXT, 
         name TEXT, 
         color TEXT, 
         foreground TEXT, 
         image TEXT, 
         header TEXT, 
         menuId TEXT, 
         isFastMenu TEXT)' );
```
And to insert in table my query is :
```
tx.executeSql(
              'INSERT INTO product_groups VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
              [
                prod.groupId,
                prod.name,
                prod.color,
                prod.foreground,
                prod.image,
                prod.header,
                prod.menuId,
                prod.isFastMenu,
              ],
            )
```
and I got error 

> table product_groups has 9 columns but 8 values were supplied

**Comment by andpor** [comment]
Suggest you try these SQL in some online SQL test db to verify it is working.

**Comment by hinciler** [comment]
I tried @andpor  and it works.

**Comment by deflexable** [comment]
thanks alot @hinciler , you just saved me hours of debugging
