### ISSUE TITLE
Update types for sqlBatch

### ISSUE THREAD

**Issue by jdnichollsc** [andpor/react-native-sqlite-storage#427]
## Expected Behavior
Having types for `sqlBatch` method

## Current Behavior
As you can see we don't have types here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-sqlite-storage/index.d.ts

Thanks for your help!

**Comment by andpor** [comment]
Hello there @jdnichollsc . I do not own those type defs. Suggest you file a PR in that repo to have them updated.
