### ISSUE TITLE
Question: this vs WebSQL (vs IndexedDB shim)?

### ISSUE THREAD

**Issue by rulatir** [andpor/react-native-sqlite-storage#43]
Is this package an implementation of the WebSQL standard?

I see this in readme: "The original Cordova plugin was written so well and **adhered to latest WebSQL API** that there was no need to come up with anything much different. So the Cordova plugin was ported to React Native." (emphasis mine)

Does this mean that this package also "adheres to WebSQL API"?

In particular, I am looking into feasibility of porting an existing IndexedDB shim that uses WebSQL as backend. Do you think it makes sense to try to port/reconfigure said shim to use RNSS as backend?

**Comment by rulatir** [comment]
After one day of struggle, the answer is generally positive; will file separate issues for things that I had to fix/shim/workaround.

**Comment by andpor** [comment]
Hi @rulatir  - I think general WebSQL API standard is adhered to with a few minor deviations around changing version and supporting sync operations.
