### ISSUE TITLE
Can not use json1 extension in android

### ISSUE THREAD

**Issue by FatemeMirzaeii** [andpor/react-native-sqlite-storage#437]
I have tried index.android.json1.js in a brand new project to test json1 feature, but I got [no such function] error for queries like 'select JSON_OBJECT  ...'.

I pushed test project here:
 https://github.com/FatemeMirzaeii/json1-test

lib version: 5.0.0
react-native version: 0.62.2

I will appreciate any help in order to fix this.

![Screenshot_1591983903](https://user-images.githubusercontent.com/33895649/84648444-4df2f500-af1a-11ea-8e1b-36181ef5495b.png)

**Comment by andpor** [comment]
JSON is only supported with NATIVE android implementation. Is this what you are using?

**Comment by FatemeMirzaeii** [comment]
thank you,fixed!

**Comment by deepakaggarwal7** [comment]
> thank you,fixed!

How did you fix it? Could you please share steps? I get the same error for any json_* operation in Android.
