### ISSUE TITLE
react-native-web support

### ISSUE THREAD

**Issue by jasonivers** [andpor/react-native-sqlite-storage#440]
Does this support [react-native-web](https://github.com/necolas/react-native-web)?  I'm having issues with trying to build for it... it appears that the plugin is not functional (SQLite.echoTest() fails).  Is there something that I can do to make it work, or do I need to find a different SQLite package for that portion of my app?

**Comment by igedeadisaputrayasa** [comment]
Up

**Comment by andymatuschak** [comment]
Just noting as a passer-by: it's not really possible for this package to support the web as a target. Web browsers don't expose a relational database API; they offer IndexedDB, akin to LevelDB. There are some attempts to shim SQL support on IDB, but they're conceptually quite different, so those wrappers will always be troublesome. You'll probably need to implement a separate database layer for the web.

**Comment by andpor** [comment]
No it does not and no plans to support it.
