### ISSUE TITLE
Problems with booleans

### ISSUE THREAD

**Issue by rulatir** [andpor/react-native-sqlite-storage#45]
At line 421:

```
params.push((v === null || v === void 0 || t === 'number' || t === 'string' ? v : v instanceof Blob ? v.valueOf() : v.toString()));
```

If it is neither `null` nor `0` nor `number` nor `string` but `boolean`, then the `v instanceof Blob` condition is evaluated. There is no Blob in React Native (at least on Android), so this throws, but the exception is caught somewhere down the stack and converted to console warning (took a while to notice!) w/o fixing the problem.

Shimming Blob = function(){} seems to quickfix the exception but doesn't really help handle booleans. WebSQL is supposed to be able to store booleans but the code above will probably end up storing strings `"true"` and `"false"`, which will both evaluate to true to an application that expects actual booleans returned from the database.

**Comment by andpor** [comment]
@rulatir I added a check for boolean and will figure out what to do with Blob... Thanks.

**Comment by rulatir** [comment]
I don't think there's anything left to be done with Blob other than an existence check to avoid exception. If there is no Blob on the platform then the app won't be storing Blobs, period.

**Comment by andpor** [comment]
SQLite does not distinguish booleans from ints. So you can just use bind_int. The only real storage classes are NULL, INTEGER, REAL, TEXT, and BLOB. 

So I suppose the option would be to convert a JS boolean type to int and use 0/1 in the database...you would get 0/1 in result set as well...
