### ISSUE TITLE
Sql query shows only row amount not row data

### ISSUE THREAD

**Issue by binhchili** [andpor/react-native-sqlite-storage#453]
## Expected Behavior
When I log the `result` in `executeSql` method I should receive data of all rows

## Current Behavior
Instead it log this :`item: {"rows":{"length":70},"rowsAffected":0}`

## Steps to Reproduce (for bugs)
Here is my code : 
```
let db;
...
useEffect(()=>{
 db = SQLite.openDatabase({
            name: 'highschool.db',
            createFromLocation: '~highschool.db',
        }, okCallback, errorCallback);
        db.transaction((trans => {
            trans.executeSql('select distinct field2 from highschool', [], (trans, result) => {
                console.log('item: ' + JSON.stringify(result));
            })
        }));
...
},[])
...
```
## Your Environment

* React Native SQLite Storage Version used:5.0.0
* React Native version used: 0.63.2
* Operating System : Android Simulator

**Comment by henrineken** [comment]
Try **result.rows.raw()** without JSON.stringify

**Comment by andpor** [comment]
@binhchili - has @henrineken hint help resolve your concern?
