### ISSUE TITLE
Where are the examples? I don't think there is an "example" folder

### ISSUE THREAD

**Issue by 814704261** [andpor/react-native-sqlite-storage#483]

**Comment by 814704261** [comment]
Where are the examples? I don't think there is an "example" folder

**Comment by kroggen** [comment]
Indeed, the README needs a rewrite.

I made a PR [here](https://github.com/andpor/react-native-sqlite-storage/pull/482) but no review yet

**Comment by andpor** [comment]
@kroggen just reviewed your PR. Please resolve conflicts and I will merge it. There is a test directory with examples for basic functional tests.
