### ISSUE TITLE
Replace or remove Jcenter() 

### ISSUE THREAD

**Issue by HerickRaposo** [andpor/react-native-sqlite-storage#485]
## Expected Behavior

Build Success 

## Current Behavior
Build falure.After React Native upgrade to 0.65 jcenter was deprecied causing build fail.

## Possible Solution
Repacle jcenter to mavenCentral()

## Steps to Reproduce (for bugs)
Do gradlew bundleRelease or gradlew cleanBuildCache

## Your Environment
* React Native SQLite Storage Version used: 5.0.0
* React Native version used:0.65.1
* Operating System of development: Windows
* Device: XIAOMI Redmi note 9t
* IDE used:Visual Studio

## Debug logs
```
WARNING:: Please remove usages of jcenter() Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
```

**Comment by andpor** [comment]
Feel free to submit a PR.

**Comment by YOEL311** [comment]
@andpor 
this code 
I did not see Maven
only jcenter

https://github.com/andpor/react-native-sqlite-storage/blob/b6aeac439b9d038bbb9d2e16812d512c38246775/platforms/android/build.gradle#L4
