### ISSUE TITLE
error while trying to roll back: cannot rollback - no transaction is active 

### ISSUE THREAD

**Issue by karthinidc** [andpor/react-native-sqlite-storage#493]
Getting the error - error while trying to roll back: cannot rollback - no transaction is active 

    "react-native-sqlite-storage": "3.3.6",

    "react": "16.8.3",
    "react-native": "0.59.9",
<img width="1218" alt="Screenshot 2021-10-14 at 4 13 03 PM" src="https://user-images.githubusercontent.com/59463519/137302642-27c96185-3bce-443c-a6dc-bef502222303.png">

**Comment by andpor** [comment]
Based on the information you provided it seems like no transaction is active.
