### ISSUE TITLE
Replace argument FragmentActivity to Activity in SQLitePlugin

### ISSUE THREAD

**Issue by barbarosh** [andpor/react-native-sqlite-storage#5]
I think Activity must be by default as type of this argument.

**Comment by andpor** [comment]
i will take a look at this.

**Comment by andpor** [comment]
Yes agree. I should have been an Activity from start. I am making this change now.

**Comment by andpor** [comment]
Done. Thanks for your suggestion Alex.

**Comment by barbarosh** [comment]
@andpor Thanks you for good module ! This module helped me on ios with improve sqlite performance! From 2m to 2s for 20k rows, timing on react-native code ! I expected will the same result on Android, but that did not happen, may be you known methods to fetch 10k rows with time 0.5s ? Now is time 6s.
P.S.: Sorry for my English,  is not my native language.

**Comment by andpor** [comment]
Well, I will have a supposedly faster adapter for Android ready within the next few days. Hopefully it will give you the spread improvement you are looking for I hope. I do not know the exact timings unfortunately. Very excited about this myself too. Спасибо тебе друг.

**Comment by andpor** [comment]
... and I can't take full credit - core work done by Chris Brody

**Comment by andpor** [comment]
@barbarosh - check out the project under android-native and tell me what kind of timings you experience vs the original Android implementation. Hope it will be much better - fingers crossed.
