### ISSUE TITLE
When i query ?

### ISSUE THREAD

**Issue by HuuThang98tn** [andpor/react-native-sqlite-storage#502]
{"db": {"dbname": "name.db", "openError": [Function anonymous], "openSuccess": [Function anonymous], "openargs": {"dblocation": "nosync", "location": "default", "name": "name.db"}}, "error": undefined, "executes": [{"error": [Function anonymous], "params": [Array], "sql": "BEGIN", "success": null}], "fn": [Function anonymous], "readOnly": false, "success": undefined, "txlock": true}

**Comment by andpor** [comment]
??
