### ISSUE TITLE
How to add new column to existing table?

### ISSUE THREAD

**Issue by gurjnderSingh** [andpor/react-native-sqlite-storage#520]
I want to add new column in my db. My app is live. when i add new column it throw error
`error: {"message":"no such column: todoStar","code":5}`
Please guide how to do this?

**Comment by huyhai** [comment]
if (error.message.indexOf('no such column: todoStar') > -1) {
          db.transaction(this.updateColumn)
 }
 updateColumn = (tx) => {
    tx.executeSql('ALTER TABLE todo ADD todoStar varchar(55);')
 }
this work for me but not work for column UNIQUE

**Comment by gurjnderSingh** [comment]
Thanks! @huyhai
