### ISSUE TITLE
DB changes are lost when Reload JS

### ISSUE THREAD

**Issue by AleCaste** [andpor/react-native-sqlite-storage#53]
Hello!
Great module! 
I have a problem when using it on android though.
When I am on debug mode, every time I hit the "Reload JS" option, all the changes that I may have done to the SQLite database are lost. The packager seems to replace the database file in the www folder with the original copy of it.
This is a pain since when you are debugging you want to make changes to the DB and it is quite normal you may want those changes to be preserved on future runs.
Is there a way to prevent this?
Please note that the "close" method is NOT being called in my case. I normally select "Reload JS" at different points of the execution of my app.

**Comment by andpor** [comment]
I think the packager is doing what it is supposed to do. But the plugin should only copy over the prepopulated db if the target db does not already exist. If it has been already created it will no longer do anything with the db file from www.

**Comment by AleCaste** [comment]
Thanks for the clarification. 
It is just that sometimes you need to make modifications to the DB on debug mode, make changes to the code and reload the package wishing the data you just manipulated would still be there in order to carry on with further steps.
But well, I can also understand what the packager does and why. Sometimes is not convenient but it is the right behavior.
Thanks for your answer! And again, great module.

**Comment by andpor** [comment]
i would have thought the db and data your write to it is there between reloads. I tried this with my test sample and clearly the sample data does not get deleted. The only way that data would disappear is if the database got deleted...

**Comment by AleCaste** [comment]
Hmmmm... that's strange... Are you testing that on an Android device? I am not using an emulator, and I am running react native 0.24.1.
In my case, whenever I reload the JS package, the database goes back to its original state (the original file on the www folder).
Then again, I am NOT closing the DB, just hitting "Reload JS" after a few INSERTS. I can see the new rows are there, but as soon as I reload the JS, those rows are gone.

**Comment by andpor** [comment]
is your database name the same each time you reload ? Can you attach  code sample where you open the database?

**Comment by AleCaste** [comment]
Yes of course.
I have a class that is in charge of the DB manipulation. That class has the following async method to open the database:
```
var dbm = require('react-native-sqlite-storage');
class DB {
  ...
  async $db_init() {
    var sql;
    try { 
      dbm.DEBUG(false);
      dbm.enablePromise(true);
      sql = await dbm.openDatabase({name:'data.sqlite', createFromLocation:1});
      // ... from here I have code that inserts several rows and then the DB is queried to check that those rows have been properly inserted
    } catch(e) {
      console.log('ERROR [$db_init]: '+(typeof e==='string' ? e : e.stack));
    }
  }
}
```

**Comment by andpor** [comment]
There are couple of log stmts I am interested in...can you attach them as you see them locally

1. Copied prepopulated DB content to: 
2. Open sqlite db: 

Do you see same exact values logged for these statements when you do Reload ?

**Comment by AleCaste** [comment]
I will try to send you more info in a couple of hours since I gotta go now.
But this is worse than I thought initially:
If -instead of forcing a JS reload- I start the app, populate the DB with some records, check that those records are there, exit the app, start the app again, and check if the records are still there.... I can see the DB is actually empty.
I will investigate this further in a couple of hours.
Thanks for you fast response!

**Comment by AleCaste** [comment]
Hello.
Good news! The module is perfectly fine!
As it is normally the case, the dumb programmer is to blame.
I forgot to delete some testing code that deleted all records from most of the tables.
After I got rid of that piece of code I tested if database changes would preserve and you can bet they do:

- When reloading the JS at any point of the app execution, changes are kept.
- When closing the app without closing the DB, changes are kept.
- And of course if you do the proper housekeeping and close the DB before exiting the app, DB changes are kept.

So you can close this issue and accept my apologies for wasting your time.
