### ISSUE TITLE
undefined is not an object (Evaluating 'NativeModules["SQLite"][method]')

### ISSUE THREAD

**Issue by faizan-tariq-confiz** [andpor/react-native-sqlite-storage#56]
Exact the same issue: https://github.com/andpor/react-native-sqlite-storage/issues/32

I am having the same issue. Its working perfectly fine in iOS but having the exact same issue on android. I have also re-install react-native and sqlite but the issue still exists.

react-native-cli: 0.2.0
react-native: 0.25.1

**Comment by andpor** [comment]
Not sure what your setup looks like I am afraid. This works on Android - maybe double check instructions.

**Comment by sumeet-ru** [comment]
Hi, I am getting the same issue  #32 
here is my package.json Please help me.. :(

[package.txt](https://github.com/andpor/react-native-sqlite-storage/files/811708/package.txt)

**Comment by xahon** [comment]
same issue. I cannot resolve that ^(
