### ISSUE TITLE
[Query] Support for new Architecture

### ISSUE THREAD

**Issue by vbansal-bb** [andpor/react-native-sqlite-storage#569]
Library Maintainers please help to know about the plan for New Architecture support

**Comment by LaGregance** [comment]
Maybe I'm wrong but I think we can already use the library with the new Architecture no ?
But indeed having a turbo module can greatly increase performance...

**Comment by niteshbalusu11** [comment]
For those looking for new architecture support. 

https://github.com/hsjoberg/react-native-turbo-sqlite

**Comment by vbansal-bb** [comment]
I can confirm that this react-native-sqlite-storage module is working fine in react native 0.74.x fine on new architecture for both platform with out any issue as inter op is default there.

**Comment by gentlee** [comment]
@vbansal-bb the question is about supporting JSI, without using bridge. Seems that this library doesn't support that which makes it slow.
