### ISSUE TITLE
single quote in string

### ISSUE THREAD

**Issue by narychen** [andpor/react-native-sqlite-storage#59]
It will cause the compiling error such as
syntax error (code 1): , while compiling

I tried replacing single quote with two single quote, but it has no effect. The library will still use backslash to escape one single quote and drop the other one.

**Comment by andpor** [comment]
I am not sure I understand what is the issue and where ?

**Comment by narychen** [comment]
check this http://stackoverflow.com/questions/603572/how-to-properly-escape-a-single-quote-for-a-sqlite-database

**Comment by andpor** [comment]
Everything seems to be working fine.

**Comment by narychen** [comment]
@andpor  the link says NOT backslash escape BUT two single quotes.
A string constant is formed by enclosing the string in single quotes ('). A single quote within the string can be encoded by putting ## two single quotes in a row - as in Pascal. C-style escapes using the backslash character are not supported because they are not standard SQL. BLOB literals are string literals containing hexadecimal data and preceded by a single "x" or "X" character. ... A literal value can also be the token "NULL".

**Comment by andpor** [comment]
tx.executeSql('INSERT INTO Employees (name, office, department) VALUES (?,?,?)',["Sylvester Sta'llone's Game", 2,  4]);

What is not working here ? I think you are confusing JS string syntax rules with SQLite..

**Comment by narychen** [comment]
I'm didn't see this use of escaping in your code demo. So I just thought it couldn't be used like this.
Sorry for missing it.
