### ISSUE TITLE
usage in Newer Syntax

### ISSUE THREAD

**Issue by ataomega** [andpor/react-native-sqlite-storage#64]
I'm newbie in React Native, i need to store user data in SQLite.

Unfortunately almost all documentations and examples of React Native SQLite usage are in old syntax and i don't know exactly how to use them in newer ES6 Syntax.

here is my code :
```
'use strict';
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TabBarIOS,
  NavigatorIOS,
} from 'react-native';

import SQLite from 'react-native-sqlite-storage';
SQLite.DEBUG(true);

var Courses = require("./courses.ios");
var Evaluation = require("./evaluation.ios");
var Schedule = require("./schedule.ios");
var More = require("./more.ios");
var Register = require("./register.ios");
var Login = require("./login.ios");
var AuthService = require("./AuthService");

class OpenCampus extends Component {

  constructor(props){
    super(props);
    this.state = {
      selectedTab: 'courses',
      isLoggedIn: false,
    };
  }

  /////// Database
  callDB(){
    SQLite.open("oc.db", function(error, database){
      if (error) {
        console.log("Failed to open database:", error);
        return;
      }
    });
  }
  /////// End Database


  onLogin(results) {
    this.setState({
      isLoggedIn: true,
    });
  }

  render() {
    callDB();
    
    if(!this.state.isLoggedIn){
      return(
        <Login onLogin={this.onLogin.bind(this)} />
      );
    } else {

      return(
        <TabBarIOS
        selectedTab={this.state.selectedTab}
        >

        <TabBarIOS.Item
        icon={{uri: 'courses.png', scale: 5}}
        title="Courses"
        badge={undefined}
        selected={this.state.selectedTab === 'courses'}
        onPress={() => {
          this.setState({
            selectedTab: 'courses',
          });
        }}>
        <Courses />
        </TabBarIOS.Item>

        <TabBarIOS.Item
        icon={{uri: 'register.png', scale: 5}}
        title="Register"
        badge={undefined}
        selected={this.state.selectedTab === 'register'}
        onPress={() => {
          this.setState({
            selectedTab: 'register',
          });
        }}>
        <Register />
        </TabBarIOS.Item>

        <TabBarIOS.Item
          title="Evaluation"
          icon={{uri: 'evaluate.png', scale: 10}}
          badge={undefined}
          selected={this.state.selectedTab === 'evaluation'}
          onPress={() => {
            this.setState({
              selectedTab: 'evaluation',
            });
          }}>
          <Evaluation />
          </TabBarIOS.Item>

          <TabBarIOS.Item
            title="Schedule"
            icon={{uri: 'schedule.png', scale: 5}}
            badge={undefined}
            selected={this.state.selectedTab === 'schedule'}
            onPress={() => {
              this.setState({
                selectedTab: 'schedule',
              });
            }}>
            <Schedule />
            </TabBarIOS.Item>

            <TabBarIOS.Item
              systemIcon="more"
              badge={undefined}
              selected={this.state.selectedTab === 'more'}
              onPress={() => {
                this.setState({
                  selectedTab: 'more',
                });
              }}>
              <More />
              </TabBarIOS.Item>

        </TabBarIOS>
      );
    }
  }
}

AppRegistry.registerComponent('OpenCampus', () => OpenCampus);
```

I tried defining and calling it inside render like this :
```
render(){
SQLite.open("oc.db", function(error, database){
      if (error) {
        console.log("Failed to open database:", error);
        return;
      }
    });
.
.
.

```

and when i run it in emulator, it says >
_reactNativeSqliteStorage2.default.open is not a function

Im sorry if im asking this in a wrong place. 

looking forward to hearing from you

also it would be great if somebody could write a simple usage of SQLite in this syntax (add a value to sqlite, then call it)

**Comment by andpor** [comment]
This is a valid error because there is no open() method. You need to refer to the documentation and cross-reference the sample code.

**Comment by ataomega** [comment]
Yeah you are right. now my code is :
```
'use strict';

import React, { Component } from 'react';
import SQLite from 'react-native-sqlite-storage';
SQLite.DEBUG(true);
SQLite.enablePromise(true);
SQLite.enablePromise(false);

class AuthService extends Component {
  constructor(props) {
        super(props);
        this.errorCB = this.errorCB.bind(this);
        this.successCB = this.successCB.bind(this);
    }

  errorCB(err) {
        console.log("error: ", err);
        this.state.progress.push("Error: " + (err.message || err));
        return false;
  }
  successCB() {
        console.log("SQL executed ...");
  }

  componentWillUnmount(){
        this.closeDatabase();
    }

  login(creds, cb){

    SQLite.openDatabase({name: 'oc.db', location: 'default'}, this.successCB.bind(this), this.errorCB.bind(this));
```

But when executing, it gives this error >
sqlite.core.js:82
SQLite.open({"name":"oc.db","location":"default","dblocation":"nosync"})


Error is in sqlite.core.js its trying to call SQLite.open, not SQLite.openDatabase

should i change it manually? is it a bug or a problem from my side?

**Comment by andpor** [comment]
What is the error ??

**Comment by ataomega** [comment]
See the screenshot please 
![screen shot 2016-06-29 at 09 58 00](https://cloud.githubusercontent.com/assets/16841537/16444786/14a77cda-3de0-11e6-8de6-41a46843394c.png)

**Comment by andpor** [comment]
Please attach screenshots of your xcode project structure showing the SQLite subproject and established linkage with libSQLIte.a

**Comment by ataomega** [comment]
Here you are
![screen shot 2016-06-29 at 10 15 26](https://cloud.githubusercontent.com/assets/16841537/16445318/7fe36818-3de2-11e6-8ccd-eca1c97dda71.png)

**Comment by ataomega** [comment]
And also this :
![screen shot 2016-06-29 at 10 16 55](https://cloud.githubusercontent.com/assets/16841537/16445382/b3bea3fa-3de2-11e6-825a-58a73824ce73.png)

**Comment by andpor** [comment]
1. Not sure why you included lib/sqlite.core.js under Frameworks - you should remove it
2. libSQLite.a does not seem to have a correct icon in the Linked Binary With Libraries. It should have the same icon as the rest of the  .a there. File icon for libsqlite3.0.tbd is ok. Not sure how you added libSQLite.a to this list...please follow instructions...try to remove it and add back in.

The error i due to improper installation of the native module so JS and ReactNative do not see it.

**Comment by ataomega** [comment]
i did it as you said :
![screen shot 2016-06-29 at 10 42 52](https://cloud.githubusercontent.com/assets/16841537/16446128/6032616e-3de6-11e6-93a0-fbf13766281e.png)
but then this error happened :
![screen shot 2016-06-29 at 10 43 36](https://cloud.githubusercontent.com/assets/16841537/16446144/6cb217c2-3de6-11e6-8bd2-86ef033f5cfb.png)

**Comment by andpor** [comment]
1. Which dir are you running nm start from?
2. It seems you react-native-sqlite-storage installation is corrupt. How did you install it ? Did you follow instructions ?

**Comment by ataomega** [comment]
i just run , react-native run-ios from project folder.
i installed react-native-sqlite-storage like your instructions :
npm install --save react-native-sqlite-storage
rnpm link

(executed from inside project folder)

should i run installation again?

**Comment by ataomega** [comment]
i did run the installation commands again :
```
OpenCampussMini:OpenCampus ata$ npm install --save react-native-sqlite-storage
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
OpenCampussMini:OpenCampus ata$ rnpm link
rnpm-link info iOS module react-native-sqlite-storage is already linked 
OpenCampussMini:OpenCampus ata$ 
```
but still gives same error. any solutions please?

**Comment by andpor** [comment]
where are you running the npm start from ?
did you try suggestions from the error screen?

**Comment by ataomega** [comment]
i dont run npm start, i just run react-native run-ios from project folder.
now i deleted noode_modules folder from project folder. im running npm install again and then will try to install react-native-sqlite-storage and will update here. thanks!

**Comment by andpor** [comment]
you should run npm start from your project dir before you run anything else

**Comment by ataomega** [comment]
I had removed node_modules folder, and i did install npm again (npm install) as you see here >
![screen shot 2016-06-29 at 11 04 16](https://cloud.githubusercontent.com/assets/16841537/16446779/8e5bd9a0-3de9-11e6-8cb6-74167dd239f4.png)

then i installed sqlite-storage like this >
![screen shot 2016-06-29 at 11 04 40](https://cloud.githubusercontent.com/assets/16841537/16446793/a3b7e640-3de9-11e6-83a4-3ec436d8e8ae.png)

and now xcode project looks like this >
![screen shot 2016-06-29 at 11 05 00](https://cloud.githubusercontent.com/assets/16841537/16446796/abbe1f80-3de9-11e6-8443-8af8d47fb365.png)

results >
![screen shot 2016-06-29 at 11 09 36](https://cloud.githubusercontent.com/assets/16841537/16446844/07dd0da8-3dea-11e6-9b74-df715c20e2f3.png)



Thanks for all your helps!! It's working now.

**Comment by infinitbility** [comment]
Checkout below documentation, hope it helps you

https://infinitbility.com/react-native-sqlite-storage-examples-of-query
