### ISSUE TITLE
Question: where to place prepopulated database file on Android?

### ISSUE THREAD

**Issue by itinance** [andpor/react-native-sqlite-storage#67]
For iOS it's working fine to place the prepulated database within "www" folder and it to the Project, that it will appear also in "Copy bundle resources".

But what are the necessary steps to include the prepopulated database file also for android?
I tried to put the www folder under "android/app/src/main/assets", but it won't work.

**Comment by andpor** [comment]
That's where it should go.

**Comment by itinance** [comment]
When obmitting the "www"-Folder and just place the sqlite-file direct under android/app/src/main/assets, everything works as expected 👍

**Comment by andpor** [comment]
it's like throwing darts...which openDatabase call did you use when you file is located under assets and how does the filename related to dbname?
