### ISSUE TITLE
Database adb push location changed

### ISSUE THREAD

**Issue by micksabox** [andpor/react-native-sqlite-storage#68]
Hey everyone,

Great component here. I noticed that when I tried to use the library, I kept getting an error about the database not being able to be opened. Previous issues (#35) recommended using `adb push DATABASE.sqlite data/data/PROJECT_NAME/databases/` to ensure the database exists in apk package.

But as you can see in exception in logcat below, this path that your pushing to is not what where the app is expecting to find the database file. Specifically, it's looking here:
`/data/user/0/PROJECT_NAME/files/`

When I tried `adb push` to this new folder path, the database was able to be found and everything worked. I noticed this using RN 0.29 and emulator. Not sure if its an issue, but if anyone can help understand why this happened it could help a fix or help future users.

Thanks!

```
07-08 12:37:02.633  4264  4361 I ReactNativeJS: Promise based runtime ready
07-08 12:37:02.633  4264  4361 I ReactNativeJS: 'Setting debug to:', true
07-08 12:37:02.634  4264  4361 I ReactNativeJS: OPEN database: fmdatabase.sqlite
07-08 12:37:02.634  4264  4361 I ReactNativeJS: SQLite.open({"name":"fmdatabase.sqlite","createFromLocation":"fmdatabase.sqlite","readOnly":false,"dblocation":"nosync","assetFilename":"fmdatabase.sqlite"})
07-08 12:37:02.634  4264  4362 V info    : Hey Michael Nolivos
07-08 12:37:02.635  4264  4364 E SQLitePlugin: unexpected error, stopping db thread
07-08 12:37:02.635  4264  4364 E SQLitePlugin: java.io.FileNotFoundException: /data/user/0/com.sayingwhenrn/files/fmdatabase.sqlite: open failed: ENOENT (No such file or directory)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at libcore.io.IoBridge.open(IoBridge.java:452)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:385)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:50)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:1034)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at java.lang.Thread.run(Thread.java:818)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at libcore.io.Posix.open(Native Method)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	at libcore.io.IoBridge.open(IoBridge.java:438)
07-08 12:37:02.635  4264  4364 E SQLitePlugin: 	... 7 more
07-08 12:37:02.658  4264  4361 I ReactNativeJS: Opened database
07-08 12:37:02.658  4264  4361 I ReactNativeJS: new transaction is waiting for open operation
07-08 12:37:02.667  4264  4361 I ReactNativeJS: Running application "SayingWhenRN" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

**Comment by andpor** [comment]
Did you by any chance read the documentation? In particular section on importing db files...
https://github.com/andpor/react-native-sqlite-storage#importing-a-pre-populated-database

If you are telling the module to look in FilesDir, and it looks like you are, do you expect the db file to appear there automatically? However, if you use of the alternative methods, and you include the db file with the app bundle then that's what the module will automatically find without doing any manual adb work.

**Comment by micksabox** [comment]
@andpor yes, I did read the docs. I'm not an experienced Android dev so some of the concepts might be new to me. I wouldn't know what/where FilesDir is, for example. I tried including the db file with the app bundle, but it did not work for me, at least initially.

**Comment by andpor** [comment]
@micksabox  - suggest google "filesDir Android" .

I am afraid you did not follow directions in the documentation thus the problem you are having. I recommend you re-read the section I had highlighted in previous post and try to learn from massive amount of documentation on the net if something does not sound familiar (like filesDir or app bundle or app sandbox)..

**Comment by micksabox** [comment]
@andpor fair enough, the issue can be closed. Since the file path changed I thought opening an issue was the best way to understand why, and if the library was affected by the new RN version. Thanks for the help anyway.

**Comment by andpor** [comment]
Use a different flavor of openDatabase and include your db file in app bundle. This section should have everything you need..you tried one, it did not work, try the other two...

https://github.com/andpor/react-native-sqlite-storage#importing-a-pre-populated-database
