### ISSUE TITLE
SQLite extensions?

### ISSUE THREAD

**Issue by efkan** [andpor/react-native-sqlite-storage#69]
Hello,

I wonder that can I use SQLite extensions (like [json1 extension](https://www.sqlite.org/json1.html)) with `react-native-sqlite-storage` ?

**Comment by andpor** [comment]
This is not currently supported.

**Comment by freemanon** [comment]
I'm willing to take this on :) Could you maybe give me some tips on how to make it work?

**Comment by ffrm** [comment]
I'm wondering how the files from the ```common``` folder are generated.

I've already tried rebuilding the ```.c``` and ```.h``` file from the original [sqlcipher](https://github.com/sqlcipher/sqlcipher) repository and added the extensions flags inside the sqlite3.c file but it didn't worked within the ```react-native-sqlcipher-plugin```.

Would you give some tipos about it? Thanks!

**Comment by ilyafriedman** [comment]
Hello! Any progress on this? I would also like to know

**Comment by naushad-madakiya** [comment]
There is new PR for Json1 support on Android, can we all test this? #392

**Comment by panda0603** [comment]
I am trying to use json_extract function in android, but I get error `"message": "no such function: JSON_EXTRACT (code 1 SQLITE_ERROR):`
Same code seems to work fine in ios. 
What may be the problem?
