### ISSUE TITLE
Benchmarks, limits, contrains ?

### ISSUE THREAD

**Issue by rturk** [andpor/react-native-sqlite-storage#70]
Hi @andpor,

Can you share any Benchmarks, limits or constrains related to this module? Overall I'm trying to assess if I can use it for my app that can easily reach 300k small rows spread within approx 8 tables. Comments, user likes, user images, product metadata.

**Comment by andpor** [comment]
Hi @rturk 

You can find some [benchmarks](https://realm.io/news/introducing-realm-react-native/#benchmarks) here. Other than that you can browse through the issue list and see what user's had to say about the module. Google is also an good source.
