### ISSUE TITLE
Cannot find database from mobile internal memory

### ISSUE THREAD

**Issue by susylPearl** [andpor/react-native-sqlite-storage#76]
i have written this code to find database from device internal storage as:
               
             var dbPath = RNFS.ExternalDirectoryPath + '/AUVparts.sqlite';
                  console.log(dbPath);

         //where dbPath = /storage/emulated/0/Android/data/com.newproject/files/AUVparts.sqlite
               var db = SQLite.openDatabase({name : "AUVparts",
                  dbPath}, ()=>this.okCallback(),()=>this.errorCallback());`

          db.transaction((tx) => {
            tx.executeSql('SELECT * FROM products WHERE partnr=1000228', [], (tx, results) => {
                console.log("Query completed");
                console.log(results);
                // Get rows with Web SQL Database spec compliance.
                var len = results.rows.length;
                for (let i = 0; i < len; i++) {
                  let row = results.rows.item(i);
                  console.log(row);
                }`

when i run this query in sqlite manager of firefox extension, it gives me result. But when i run this code ,in console it gives me error as no such table 'products'. What happens to my code? is there any mistakes while giving correct path to sqlite database? 

I have kept sqlite file in device internal storage Android/data/com.newProject/files

please suggest some tips. Thanks

**Comment by andpor** [comment]
Can you review the documentation regarding the openDatabase call and see if your code matches up?

**Comment by andpor** [comment]
I am tempted to close this issue since i have not heard back from you for some time. Assume the documentation cleared the problems?

**Comment by susylPearl** [comment]
I have thoroughly read all the documents there but i cannot get
reaults.please once read my question correctly and try to give answer, dont
be too eager to close the issue without finding solutions.

**Comment by andpor** [comment]
Your openDatabase call does not match anything that is supported.
