### ISSUE TITLE
getting an error in while executing sql

### ISSUE THREAD

**Issue by shaikhussian** [andpor/react-native-sqlite-storage#77]
hai i am using this repo i got an sucess message, but while executing the sql query i got an error like no such table,changed my sqlite file to testDB and paste it in IOS folder, as given in the repo.
in sqlite i created a database and table in sqlite, here is the code which i wrote
```
var db = SQLite.openDatabase({name : "testDB", createFromLocation :1}, this.successCB,this.errorCB);
      db.executeSql('SELECT * FROM words', [], (results) => {
       alert("results:"+results)
      },(error)=>{
        alert("error:"+JSON.stringify(error))
      })
```
please give me suggestions that how to solve this problem

**Comment by andpor** [comment]
i suggest you read the documentation and double make sure you understand Step 6 - Adjust openDatabase call, especially what it means when createFromLocation is 1.

**Comment by andpor** [comment]
I am tempted to close this issue since i have not heard back from you for some time. Assume the documentation cleared the problems?
