### ISSUE TITLE
new transaction is waiting for open operation

### ISSUE THREAD

**Issue by shubhambatra** [andpor/react-native-sqlite-storage#82]
What i need to do to get rid of this.

**Comment by andpor** [comment]
Sorry but I can't tell what the problem is. Please provide a simple test case demonstrating the issue.

**Comment by shubhambatra** [comment]
moved to REALM. Hence closing the issue.

**Comment by vmarquet** [comment]
See #184.

**Comment by ShaikhKabeer** [comment]
HI @shubhambatra , How to open created schema on another screen in realm.
