### ISSUE TITLE
Upgrade to NPM Podspec

### ISSUE THREAD

**Issue by donald-jackson** [andpor/react-native-sqlite-storage#84]
Hi there,

The current React Native CocoaPod mechanism has been deprecated in order to move to NPM for all building. Could you please assist in moving this over?

I have tried myself but I can't seem to get things working properly.

I removed the 'React' dependency from the react-native-sqlite-storage podspec and added:

```
pod 'React', :path => './node_modules/react-native'
```

To my main project podspec which seems to use the latest React but no joy in functioning.

Thanks

**Comment by nevir** [comment]
Do you have a reference for the deprecation?  Would be curious to hear the background there

**Comment by andpor** [comment]
CocoaPods set-up instructions are corrected in 3.2.2
