### ISSUE TITLE
Changing Pre-Populated Database

### ISSUE THREAD

**Issue by afreel** [andpor/react-native-sqlite-storage#88]
After updating my sqlite3 db to have a new column, the openDB call seemed to still be opening the old db.  Even after removing the old file and generating a new sqlite3 db file under a different name, I cannot access the new database (getting a table not found error).  Opening and running the project in XCode allows me to call the new database, so I'm assuming that it is storing the old db somewhere.  Is there anyway to force it to forget the old db and recognize the new one?

**Comment by afreel** [comment]
Looking deeper this may not be related at all actually.  If I change the simulated device (i.e. to iPhone 5 instead of 6), it finds the db and works.  But if I change back to iPhone 6, it still throws a 'no such table: deckitems' error message.  Is this possibly related?

**Comment by andpor** [comment]
can you provide some code sample that seems to be causing issues?

**Comment by afreel** [comment]
`var db_name = "mainDB";
var db;

db = SQLite.openDatabase(
  {name : db_name, createFromLocation : "~data/mainDB"},
  () => console.log("SQL Database Opened"),
  (err) => console.log("SQL Error: " + err),
);`

The above code is where I open the database, which works if I am running simulator on iPhone 5 but not on iPhone 6.

**Comment by andpor** [comment]
There is lots of relevant debug printed regarding db opening in the console. Can you check what it says and compare on both simulators. This is nothing device specific in the library.

**Comment by afreel** [comment]
When I run on iPhone 5 simulator everything works, so it has the 'SQL Database Opened' (my success log), as well as 'OPEN database: mainDB', which is the name of my database.

When I run on iPhone 6, it still logs the 'SQL Database Opened', but then also logs
'''<Notice>: 'Error handler not provided: ', { code: 5, message: 'no such table: deckitems' }'''

'deckitems' is the name of one of my tables in the database.

**Comment by afreel** [comment]
So I changed the table schema once again, and have run into this problem again.  It seems each device is caching its own version of the table.  On the iPhone 5 simulator now, it does not see my new schema, but instead only sees the old one (and reads from the old table, which I have already dropped).  So, iPhone 6 simulator has the original, iPhone 5 has v2, and now I have moved to iPhone 4 which finally recognizes my new table because I have yet to use it yet.  I know you said this library has no device specific logic, so perhaps it is just react native?  Let me know if you have any ideas!

**Comment by afreel** [comment]
Also, I've noticed that when I run an insert command like
```executeSql('INSERT INTO deckitems ...```
the new row is not actually inserted/written into my db file located at "~data/mainDB".  Is there a way to write out to this file?

**Comment by andpor** [comment]
There is lots of debug in the Xcode console - have you looked at it? It will tell you which db it opened and which path it used...

I still do not understand what you did - the code sample is insufficient...

**Comment by andpor** [comment]
when you use createFromLocation , it does not mean that the library will wire in your database. What is happening is that the database at the path you provided is used as template for creating a real database in the one of the 3 locations used by the library. the db you provide in createFromLocation will be copied into that internal location.

**Comment by andpor** [comment]
use deleteDatabase({name : db_name, location : 'default'}) to delete the existing database that was created in default location

**Comment by andpor** [comment]
@afreel - please update the status of this issue and close if all issues are resolved.

**Comment by afreel** [comment]
Hello, sorry for the late response.  Yes, SQLite.deleteDatabase indeed worked, that makes sense that it is being copied internally, thanks for the responses.

**Comment by kaushalmarakana** [comment]
> use SQLite.deleteDatabase({name : db_name, location : 'default'}) to delete the existing database that was created in default location. Then subsequent openDatabase call will recreate the internal copy of the database based on the new template you provide in that call.

@andpor Thanks for this, this is working.

**Comment by infinitbility** [comment]
When you want pre-populate database then every time you have to create a new database file and delete previous database or re build application.

check out below documentation

https://infinitbility.com/react-native-sqlite-storage-examples-of-query
