### ISSUE TITLE
No errors, no data, frustrated.  :(

### ISSUE THREAD

**Issue by dovy** [andpor/react-native-sqlite-storage#94]
I've tried for days to get this to work. I have a pre-populated database properly added to my ios project. The library is linked and seems to load without issues. I turned on debug mode for good measure just so I could watch my output.

To simplify things, I tired running a basic query to find out the makeup of the database, removing my tables completely. This is the output I get in the console:

```
OPEN database: data2.db
sqlite.core.js:82 SQLite.open({"name":"data2.db","readOnly":true,"location":"default","dblocation":"nosync"})
PresentationScreen.js:75 SQL executed ...
sqlite.core.js:82 SQLite.backgroundExecuteSqlBatch({"dbargs":{"dbname":"data2.db"},"executes":[{"qid":1111,"sql":"BEGIN","params":[]},{"qid":1111,"sql":"SELECT * FROM sqlite_master;","params":[]}]})
sqlite.core.js:82 SQLite.backgroundExecuteSqlBatch({"dbargs":{"dbname":"data2.db"},"executes":[{"qid":1111,"sql":"COMMIT","params":[]}]})
```

I also get the following in my actual console.log call: 
```
rows:{}
length:0
rowsAffected:0
```

For good measure I created my DB via SQLite3 and also tried doing a SQLite2 version of the same DB. The DB works in every editor I can find.

I put everything in a www directory, and added properly to my xcode project: https://cloudup.com/czfY3suqaAG

The source code I am running is as follows:
```
db = SQLite.openDatabase({name: 'data2.db', readOnly: true, location: 'default'}, this.successCB.bind(this), this.errorCB.bind(this));
        db.transaction((tx) => {
            tx.executeSql("SELECT * FROM sqlite_master;", [], (tx, results) => {
                console.tron.log(tx);
                console.tron.log(results);

                // Get rows with Web SQL Database spec compliance.

                var len = results.rows.length;
                for (let i = 0; i < len; i++) {
                    let row = results.rows.item(i);
                    console.tron.log(row);
                }

            });
        });
```

Again, this should be pretty strait forward, but I can't get it to read my database at all. Can someone help?

**Comment by dovy** [comment]
When I try to select any of MY tables I get this:

```
Error handler not provided:  Objectcode: 5message: "no such table: file"__proto__: Object
sqlite.core.js:503 warning - exception while invoking a callback: {"code":5}
```

Editor output: https://cloudup.com/c7mc395c7Pe

Am I missing something here?

**Comment by itinance** [comment]
It seems that the prepopulated database was not found and thus the table "file" isn't present.
In XCode, turn on the debug console. Both, the final database file and also the prepopulated file be dumped there. 

Just copy the full path, go into the terminal and run "sqlite3 filename" ("filename" should be replaced with the real filename including the whole path)
Then type ".schema". If nothing happens, no tables are present, what means, that the prepopulated database can't be found in your setup.

**Comment by andpor** [comment]
@dovy - in the [README file section](https://github.com/andpor/react-native-sqlite-storage#step-6---adjust-opendatabase-call) opening databases there are some examples for openDatabase call. The important param is createFromLocation. It seems you have not included this param in your call?

**Comment by dovy** [comment]
@andpor I've tried all variations. My current one is:
```
var db = SQLite.openDatabase({name : "data", createFromLocation : 1}, this.openCB, this.errorCB);
        db.transaction((tx) => {
            tx.executeSql('SELECT * FROM sqlite_master', [], (tx, results) => {
                console.log("Query completed");
                console.log(tx)
                console.log(results)

            });
        });
```

Still nothing.

I'm pretty sure the file is loading, because the debug output is quite different than when I choose another path.

**Comment by dovy** [comment]
Do you have a working example app? Perhaps something is just off. :(

**Comment by itinance** [comment]
I created a working example app right now. Will also provide the android version and then post the repo-link soon. just some minutes...

**Comment by dovy** [comment]
Thank you so much. I think that will help you all going forward. I know it will be useful for me.  ;)

P.S. Only using iOS right now myself.  ;)

**Comment by itinance** [comment]
Please find the example application here: https://github.com/itinance/react-native-sqlite-storage/tree/example-with-prepopulation/examples/PrepopulatedDatabaseExample

I've also provided a Pull Request for this example because i found it very usefully.

**Comment by andpor** [comment]
@dovy is the filename just 'data' ? You used {name : "data"....}

**Comment by brodybits** [comment]
Thanks @itinance for the contribution, I am sure it will help a number of other users. A small nit: "Good to now" should be "Good to know" in your README.md changes.

As a side comment: I added pre-populated database support to the cordova-sqlite-ext plugin version due to popular demand. I would personally favor downloading the initial data over JSON in order to save installation size.

**Comment by itinance** [comment]
Damn... thanks for the hint, @brodybits . Just added the missing "k" :)

Regarding your side comment. It depends on the needs. There are two different usecases for a prepopulated database:

1. prepare the DB initially with a schema with less effort
2. create the database also with lots of content 

In my company we decided for #2 to prebundle lot of content directly into the app. Yes, it makes the installation file larger. But our reason was the following. We are an edtech-company providing an app to learn chinese characters. Imagine, that the user is on the airport, downloads the application, but launch it the first time after the plane started (just as an example, take trains, subways, bars and cafes without wlan and everything else), the experience would be damaged if another download of content would be necessary to launch the app initially. The transfered data would be the same in both cases (installation + separate download vs. installation all-in). In a combined version the app can be used completely after installation without and further necessary downloads. In some cases it would make sense, in some not :)

**Comment by andpor** [comment]
@itinance - I would like to keep this repo as lean as possible and keep full example applications separate. I created a dedicated repo for this purpose [react-native-sqlite-storage-examples](https://github.com/andpor/react-native-sqlite-storage-examples). Let's put the examples there.

**Comment by dovy** [comment]
Agreed, don't pollute the project with this. Just keep it in sync.

**Comment by itinance** [comment]
Ok, will do so

**Comment by brodybits** [comment]
Thanks @itinance for the explanation, I have to admit it does make sense for you and a number of other app developers. An extra alternative could be to keep the data in a compressed dump asset file. Maybe I am getting carried away here:)

**Comment by andpor** [comment]
@itinance Hagen - can you move your attach example to the new repo as well?

**Comment by itinance** [comment]
will do so

**Comment by itinance** [comment]
PR for this Repo already done. PR on the example-repo will follow up tomorrow because i want to rename it first

**Comment by andpor** [comment]
@dovy - can you update this issue if all is sorted out?
