### ISSUE TITLE
[Question] Can I?

### ISSUE THREAD

**Issue by andresKM** [andpor/react-native-sqlite-storage#96]
Can I use it for react-native-web? So when I make web-app I can slightly modify to get Android version?
Also, does it support FTS?

**Comment by andpor** [comment]
I apologize but I have no idea what you're asking...

**Comment by itinance** [comment]
Same here. @andresKM can you clarify a bit more precisely what you're really asking for?
FTS = https://www.sqlite.org/fts3.html ?

**Comment by andresKM** [comment]
Yep, full-text search. I want to use react-native-web from https://github.com/necolas/react-native-web 
and use fts on sqlite, and maybe modify it for android app. Is it possible? Or I should use pouchdb with react native + some kind of REST backend with db that supports fts?

**Comment by itinance** [comment]
First you speak about react-native-web (which is for web, means: browser, html), but in the same breath you're talking about an android-app. 
I think your topic is outside of the scope of this project.

**Comment by andpor** [comment]
Beyond the scope of this project.
