### ISSUE TITLE
Replace sqlite file....

### ISSUE THREAD

**Issue by edolfuchs** [andpor/react-native-sqlite-storage#99]
I am downloading a remote sqlite file and saving it to: DocumentDirectoryPath/. I want to know if it is possible to move this file to the MainBundlePath/.

I used react-native-fs to move the file, but the iphone does not allow saving in the main bundle directory. In the simulator it works.

**Comment by itinance** [comment]
When you download this file to the document directory path, have you tried to open the database from Document-Path? 

`SQLite.openDatabase({name: 'my-downloaded-database.db', location: 'Document'}, successcb, errorcb);`

Further information on how to open a database is listed in this section of readme: [https://github.com/andpor/react-native-sqlite-storage#opening-a-database](https://github.com/andpor/react-native-sqlite-storage#opening-a-database)

**Comment by edolfuchs** [comment]
I tried and it worked, but I need the database to be in one place. DocumentDirectoryPath or MainBundlePath.

I am using a pre-populated database and only accept when the file is in MainBundlePath.

If I can put a pre-populated database in DocumentDirectoryPath it would solve my problem.

**Comment by andpor** [comment]
you cannot move any file into the main bundle.

**Comment by itinance** [comment]
We could try make it possible to put databases for pre-population into the document directory instead of "www"-directory.
If you both find it usefully, I will have a look on it in upcoming days and provide PR if possible

**Comment by itinance** [comment]
We could try to support other filepaths for pre-population instead of www-subdirectory.
If you both find it usefully, i would look for a solution in upcoming days and provide a solution (we could use this feature also at zizzle in near future)

**Comment by andpor** [comment]
This is all already supported. Prepopulated database does not have to exist in www folder under main bundle. Instructions and examples are already in the readme.

**Comment by edolfuchs** [comment]
I copied the sqlite files from main bundle to library path and opened database from it. Now everything is working.
